### ISSUE TITLE
Backend reports no longer show at all

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#101]
Backend reports for vendors no longer work at all. The menu item doesn't even show up. This is since version 2.3 of WooCommerce.

**Comment by bentasm1** [comment]
Good!  Probably better this way.

**Comment by danycrup85** [comment]
There is a fix for this bug? Thanks

**Comment by bentasm1** [comment]
There is not yet, no.  Most site admins dont even use back-end reports because reports are already visible on the front-end dashboard.  We will look at this one soon, it's just been a very low priority.

**Comment by danycrup85** [comment]
Ok. great work! :)

**Comment by digitalchild** [comment]
This feature has been depreciated and will be removed.
