### ISSUE TITLE
js issues with WC Vendors and the API Manager

### ISSUE THREAD

**Issue by svenl77** [wcvendors/wcvendors#102]
In the front-end checkout the order is spinning for ever.
It looks like all select2 fields are broken.
In the product edit screen If I try to add "Up-Sells" it search for ever.
In the order edit screen its not possible to add new products.

I first recognised the issues in the API Manager from Todd. It's not possible to add new License Keys.

Actually all the js looks damaged.

**Comment by bentasm1** [comment]
Who is Todd and what is a license key required for?  WC Vendors is free and doesnt need a license key, not sure who Todd is. :)

**Comment by svenl77** [comment]
You misunderstood me. I first recognised the issue with the api manager. Than I did some tests to find the issue and landed by wc vendors

http://www.woothemes.com/products/woocommerce-api-manager/

**Comment by bentasm1** [comment]
Aah, that makes more sense now, thanks.  Jamie works on all the JavaScript stuff, so this one will be up to him to detect and fix any issue.  I'll let him know.

**Comment by svenl77** [comment]
After more deeply testing we found out it's the combination from wc vendors and the api manager which create the issues. Not BuddyPress. I will post the result here.

**Comment by svenl77** [comment]
Thanks to Todd for finding the issue:

Here we go
![screenshot 2015-02-20 15 35 05](https://cloud.githubusercontent.com/assets/645567/6311413/9b4e14fa-b962-11e4-8870-09e4db0dfa34.png)

Vendors is calling the chosen jQuery plugin, but it won't work in WooCommerce 2.3, which now only loads the Select2 jQuery plugin for drop down menus.
That it appears to be breaking the JavaScript
Call Select2 for WC => 2.3, else Chosen.
