### ISSUE TITLE
Table Rate Shipping 2.8.2 Compatibility

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#103]
classes/class-shipping.php under trs2_clear_transients -- If is_checkout, we dont need to do anything.

I commented out the clear transients line, even after updating it to non-deprecated functions, and that makes the error go away and TRS2 still loads at checkout.

This is my hack.  Is it the best way to do it?  I dont know.  All yours Jamie. ;)

PS -- trs2 is on dev now and installed.

**Comment by bentasm1** [comment]
http://www.wcvendors.com/help/topic/crashing-checkout-page/ See comments and fix posted.  Customer says fix appears to work.  Asked him to test a bit more to confirm just in case.

**Comment by digitalchild** [comment]
I haven't used TRS2 either but I will remove this function for the time being.
