### ISSUE TITLE
Duplicate column name on activation

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#104]
Reported by the author of the WooCommerce API Manager:

On plugin activation
[6:10:02 PM] Todd Lahman: WordPress database error: [Duplicate column name 'qty']
ALTER TABLE `wp_1210fdksl_pv_commission` ADD `qty` BIGINT( 20 ) NOT NULL AFTER `total_due`

WordPress database error: [Duplicate column name 'total_shipping']
ALTER TABLE `wp_1210fdksl_pv_commission` ADD `total_shipping` decimal(20,2) NOT NULL AFTER `total_due`

WordPress database error: [Duplicate column name 'tax']
ALTER TABLE `wp_1210fdksl_pv_commission` ADD `tax` decimal(20,2) NOT NULL AFTER `total_shipping`

WordPress database error: [Duplicate column name 'tax']
ALTER TABLE `wp_1210fdksl_pv_commission` ADD `tax` decimal(20,2) NOT NULL AFTER `total_shipping`

**Comment by digitalchild** [comment]
What version of the plugin?

**Comment by svenl77** [comment]
Version 1.4.4

**Comment by bentasm1** [comment]
This was from the api manager guy, Todd/  Chances are he was in debug mode too.

**Comment by digitalchild** [comment]
If this is a fresh install or an update from any of the 1.4 versions there should be no ALTER table statements run at all as those upgrades are only run on updates of the plugin.

**Comment by bentasm1** [comment]
I'm sure it was a fresh install on his own dev website not a live site.  I wouldnt really even worry.

**Comment by digitalchild** [comment]
I think this is actually a bug in our db init.
