### ISSUE TITLE
Low stock notifications to vendors

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#114]
Currently low stock notifications go to the admin. These need to go whoever owns the product.

**Comment by bentasm1** [comment]
https://github.com/woothemes/woocommerce/blob/09676934d69002e231d3fdd3ce00dbcddb4f4911/includes/class-wc-emails.php

L106-107:
add_action( 'woocommerce_low_stock_notification', array( $this, 'low_stock' ) );
add_action( 'woocommerce_no_stock_notification', array( $this, 'no_stock' ) );

**Comment by digitalchild** [comment]
These actions only allow us to change the contents of the email, not who this is triggered to. I think we want to use these filters instead: 

`apply_filters( 'woocommerce_email_recipient_low_stock', get_option( 'woocommerce_stock_email_recipient' ), $product )`

`apply_filters( 'woocommerce_email_recipient_no_stock', get_option( 'woocommerce_stock_email_recipient' ), $product )` 

The product is provided here so we should be able to do based on owner of the product.

**Comment by chomomahesh** [comment]
Hi, can i know how to use woo-commerce default email template for send this out of stock email. i put this filter it sent only text email. i want to use email template for this.

**Comment by fervous** [comment]
Please ask your support questions in our help forums, not on Github.  https://www.wcvendors.com/help/
