### ISSUE TITLE
Specific product fails to appear after about 300 test sales transactions

### ISSUE THREAD

**Issue by Frankenmint** [wcvendors/wcvendors#129]
I wasnt paying too much attention to it, until my test orders stopped appearing.  I presumed it had to do with the vendor user, but I now realize it was an issue with my product itself.  I'm not sure if its a broken row on the meta_table but I suspect that is the culprit.

**Comment by bentasm1** [comment]
Could you please provide some details?  This is too vague to really be able to investigate properly......

Thanks!

**Comment by Frankenmint** [comment]
I have product with variable options with stock options DISABLED.  It was working fine up until this morning. Now whenever orders are placed on this item, it never appears on the wp-vendors dashboard but it appears on the backend.  Its only on this product and not on others, I haven't yet tried another variation so I'm going to try that now

**Comment by Frankenmint** [comment]
also, this is my meta _product_attributes tag in the DB.  I'm new to WP on this level so I'm not sure if having duplicate values like it shows here is a problem or not:

    a:1:{s:5:"sizes";a:6:{s:4:"name";s:5:"Sizes";s:5:"value";s:46:"half gram | gram | 8th | quarter | 1 OZ | 4      OZ";s:8:"position";s:1:"0";s:10:"is_visible";i:0;s:12:"is_variation";i:1;s:11:"is_taxonomy";i:0;}}

**Comment by digitalchild** [comment]
What happens if you delete and recreate the product?

**Comment by Frankenmint** [comment]
probably works.  I did this with a different item and its been working okay for my testing purposes
Sincerely,

Frankenmint
www.honeybadgerofmoney.com <http://www.honeybadgerofmoney.com/>
Spread Awareness | Spread Adoption
