### ISSUE TITLE
Hide Notice Error

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#133]
Notice: Undefined variable: submit_link in /wp-content/plugins/wc-vendors/classes/front/dashboard/class-vendor-dashboard.php on line 208
Notice: Undefined variable: edit_link in /wp-content/plugins/wc-vendors/classes/front/dashboard/class-vendor-dashboard.php on line 209

Note:  We might make better use of this with WordPress 4.2:

https://wordpress.org/news/2015/04/wordpress-4-2-beta-4/
Added the ability to make admin notices dismissible. Plugin and theme authors: adding .notice and .is-dismissible as adjacent classes to your notice containers should automatically make them dismissible. Please test.

However, this of course would only work for 4.2+

**Comment by digitalchild** [comment]
The hide admin notices will only work in the dashboard.
