### ISSUE TITLE
Add support for plain text email templates

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#134]
Currently all email classes only support html emails. Need to add support for plain text emails and add the relevant templates.

**Comment by bentasm1** [comment]
Curious, but does anyone even use plain text emails anymore?  I cant think of the last time I've ever received one, at least not in the last 5 years!

**Comment by digitalchild** [comment]
Required for accessibility reasons mostly. screen readers and such. Also we should be supporting whatever the parent plugin is.

**Comment by bentasm1** [comment]
Meh, we've never had a single request for this.  Time better spent elsewhere.  Closing.
