### ISSUE TITLE
WC_Email_Notify_Vendor email template is not within plugin templates

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#135]
Currently the plugin looks for the templates in the woocommerce directory. This should be within our plugin template tree. This would allow store owners to better manage their WC Vendors emails.

**Comment by digitalchild** [comment]
Also add plain text email template for this class

**Comment by digitalchild** [comment]
Text email templates will become its own issue.

**Comment by digitalchild** [comment]
Still not working

**Comment by digitalchild** [comment]
Need to find how to check theme for email templates outside of the woocommerce tree as these seem to be hard coded into the WC_Email class.

**Comment by bentasm1** [comment]
Wouldn't they go in /themes/yourtheme/woocommerce/emails/?

**Comment by digitalchild** [comment]
Yes currently that is where they need to be located but it would make more sense for them to be in /themes/yourtheme/wc-vendors/emails/ to keep the consistency of template overrides for the plugin

**Comment by digitalchild** [comment]
Woocommerce does not support putting these email templates anywhere but in woocommerce/emails within the theme.
