### ISSUE TITLE
Vendors Not Receiving Shipping Charges

### ISSUE THREAD

**Issue by darlaburns** [wcvendors/wcvendors#136]
When buyer purchases something from a vendor, the shipping is going to the store owner even though in WC Vendors settings, the "Give Vendors any shipping collected per-product" is checked. Tested through Sandbox at Paypal and indeed the shipping and commission is going to the store owner and not the vendor. Using table rate shipping plugin - Table Rate Shipping by Mangohour.

**Comment by bentasm1** [comment]
As already instructed, you need WooThemes Per Product Shipping in order to use the shipping to vendors feature.  Table Rate Shipping is not supported, because Mangohour does not include WC Vendors support in it.  You can ask him to include support, but that is up to him to do. :)

**Comment by darlaburns** [comment]
Very new to this and did do some research but missed that.  Thank you!

**Comment by bentasm1** [comment]
No worries at all. :)  GItHub is more for submitting code changes or reporting bugs, you'll find www.wcvendors.com to be very helpful, there's a full help forum and a knowledgebase with a wealth of info. :-)
