### ISSUE TITLE
Add Notice if Shop Settings & Order Pages not set

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#137]
When an admin deletes the shop settings and orders pages (bad admin!) you will get a login redirect loop.  So, let's add a notice if those pages arent set telling them they must be set otherwise they will experience problems.

**Comment by digitalchild** [comment]
The login redirect loop is actually due to the permalink settings not the pages not being set. However we can add a notice for this.

**Comment by digitalchild** [comment]
This was fixed in 1.7.0
