### ISSUE TITLE
Add Tax to Notify Vendors Email

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#146]
In the version 1.7.2 of WC-Vendor, even if I have enabled the option to transfer the Tax to the Vendor, it is not included in the email to the vendor. But in the report, under the Commission that is due, it is included. So, it appears that it is working but it is just missing in the email template that is generated.

http://www.wcvendors.com/help/topic/tax-not-included-in-the-email-to-vendor/

**Comment by eric-enrico-roy** [comment]
Hi Ben,
thanks to have created this ticket on my behalf.
Eric
