### ISSUE TITLE
Payments Tab Translation Bug?

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#155]
http://www.wcvendors.com/help/topic/commission-problem/#post-5518

When the string for Total Commissions Due is translated, it appears that the commission doesnt show the correct totals, but shows $0 instead.

**Comment by digitalchild** [comment]
%s should not be overridden in the translated string. I wonder if because its defined as a string and not a number that it is failing on translation.

**Comment by digitalchild** [comment]
It appears the test for ensuring we're on the right tab before doing the total_due query was checking against an english word. I made that translatable as well and can confirm we now have working commissions in spanish.
