### ISSUE TITLE
Add filter for "Order marked shipped." text

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#164]
https://github.com/wcvendors/wcvendors/blob/ab98aa80207042990ab615573116a0af17e28984/classes/front/dashboard/class-vendor-dashboard.php#L46

**Comment by digitalchild** [comment]
If we're going to add filters for that wc notice we should add filters for EVERY notice. They are already translatable strings.

**Comment by dej888** [comment]
This would be fantastic!

**Comment by bentasm1** [comment]
It won't be since it's already a translatable string.
