### ISSUE TITLE
Update Compatibility for Shipment Tracking for v1.3.5

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#167]
http://www.wcvendors.com/help/topic/vendor-adding-tracking/#post-5844

Version 1.2.9 works, version 1.3.5 (latest) does not.

V1.2.9:  http://dev.wcvendors.com/wp-content/plugins/woocommerce-shipment-tracking/old.txt

v1.3.5:  http://dev.wcvendors.com/wp-content/plugins/woocommerce-shipment-tracking/new.txt

Figure out what's changed in the two to cause it not to load on vendor dashboard, v1.3.5 will not show the Add Tracking Info text.......

**Comment by digitalchild** [comment]
Need to fix tracking on main dashboard, also need to support updating tracking on multiple products in an order. Currently this is not supported.
