### ISSUE TITLE
Add vendor link to my-account order pages

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#17]
Currently when an order is processed and the buyer views the order in the my account section there is NO mention of who the vendor was.
This is asking for a million support requests that should be directed at the vendor. I suggest the following
Order items and totals are shown.
The NAME of the vendor for each item.
The transaction ID from the gateway.
IMPORTANT! A button to “Contact the seller” (to avoid store admin being contacted for issues not concerning them)
In addition admin side in orders there needs to be a clear way to see vendors involved with an order with links to their user account.
I feel this is a fairly important change.

http://www.wcvendors.com/help/topic/definition-of-vendor-on-customer-order-page/

**Comment by digitalchild** [comment]
Has this been fixed with the recent sold_by filters ?

**Comment by bentasm1** [comment]
Yes!
