### ISSUE TITLE
InstantPay Issue

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#174]
Continues to pay vendors even when instant pay is turned off. See http://www.wcvendors.com/help/topic/instantly-pay/

**Comment by elvinlee** [comment]
I also face same problem. Because the last update is 24 June and I install it on 25 June, is it only happen in the latest version?

**Comment by digitalchild** [comment]
This is a known issue and will be addressed in the next release, it has been happening for a few releases now.

**Comment by elvinlee** [comment]
Looking forward the update. By the way, this is a nice plugin! Will help to feedback more based on my user experience. =)
