### ISSUE TITLE
Vendor Terms & Conditions Checkbox Bug

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#182]
On /my-account/ if you register, and do not check the approve of terms and conditions checkbox, registration still continues and registers the user.  Oddly, the "You must accept the terms and conditions to become a vendor." notice does appear, but it appears on the /my-account/ page after they are already now a vendor.  It should block registration from occurring as it did before.  Woo probably changed something somewhere......

**Comment by nicogaldo** [comment]
I hope it is resolved soon!
