### ISSUE TITLE
Commissions Page - Add # of times sold after product

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#184]
Where it shows product link as:

Bicycle

Change to:

Bicycle (10)

....where 10 is the total_sales from the product meta.  It's like a little extra reporting for free.

**Comment by MattyLB** [comment]
Can this be configurable?  From a customer viewpoint "Bicycle (10)" could
either mean there are 10 options or only 10 available. Adding a post-title
tag that says "total sold: 10" - (configurable text) - would be a much less
confusing way of getting this same great info out to the customer. It can
add a level of trust in the product when reviews are hard to get.

Thanks for hearing me out.

**Comment by bentasm1** [comment]
@MattyLB -- The customer would never see this.  It's on the wp-admin > WooCommerce > Commission page.  The vendors already see the quantity of an item sold on their Vendor Dashboard on the first set of reports that appear.

**Comment by MattyLB** [comment]
Ok, sorry for missing the "commissions page" part. That makes more sense. :+1:

**Comment by bentasm1** [comment]
No worries at all. :-) :-)
