### ISSUE TITLE
Feature Request: Dwolla (w/ optional white label) Vendor Payout Gateway

### ISSUE THREAD

**Issue by MattyLB** [wcvendors/wcvendors#185]
I've been following the Dwolla payment gateway for quite a while and have it incorporated in a site as a customer payment gateway - and it's a very slick, easy to use gateway - yet it's not a widely known payment brand like PayPal, etc, so it's lacking some traction on the customer end.

That said, it IS a very attractive, low cost if not free ACH (bank or credit union) payment method with mass pay, white label and many other options that are a perfect fit for vendor payout scenarios like those in WC Vendors.

They are a friendly and motivated group to work with and have offered the help of a lead developer on a gateway for MarketPress, so I'm fairly certain they would be interested in helping you guys develop a mass pay with white label capable vendor payout gateway for your Pro version if you're interested.

Here's a link to more information on the white label options: http://blog.dwolla.com/white-label-coming/

Thanks for considering this!

**Comment by digitalchild** [comment]
Once pro is out we will look at other payment and shipping options as additional add-ons based on demand and ease of implementation.

**Comment by MattyLB** [comment]
Sounds good. Can we keep this open to allow others to vote it :+1:  or :-1: in the meantime?

**Comment by bentasm1** [comment]
Yup.

**Comment by MattyLB** [comment]
sweet!  here's mine ... :+1:  - lol

**Comment by bentasm1** [comment]
Not much love for Dwolla.  Closed.

**Comment by MattyLB** [comment]
It's better as a mass-pay tool anyway (no transaction fees). Not as a
customer-facing payment gateway.

I'm learning how to code so I may tackle this one on my own. =)

**Comment by bentasm1** [comment]
If you want to code it we'd be happy to accept a pull request to add it to core.

**Comment by MattyLB** [comment]
+1

Will start working on it this weekend and submit a PR when ready. :)
