### ISSUE TITLE
wcv_footer() for admin pages

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#186]
Create a footer function that will echo out neat stuff.  Like (c) WC Vendors - www.WCVendors.com - Rate us on WordPress 5 Stars link etc....  Then we can use wcv_footer() after our pages in the admin section.

Extra credit:  Create an if wcv_pro_footer() function exists and if it does, use that instead, that way we can have a separate one for Pro.

**Comment by digitalchild** [comment]
This has been added
