### ISSUE TITLE
remove_filter doesnt work for Sold By: in email notifications

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#188]
https://wordpress.org/support/topic/sold-by-still-showing-via-order-email?replies=6

**Comment by digitalchild** [comment]
This will always add it to the item meta everywhere which is why the other filter wasn't working. 

remove_action( 'woocommerce_add_order_item_meta', array('WCV_Vendor_Shop', 'add_vendor_to_order_item_meta'), 10, 2 );
