### ISSUE TITLE
Major resource usage

### ISSUE THREAD

**Issue by archonic** [wcvendors/wcvendors#189]
I'm finding WC Vendors to be very slow, and I believe it's largely responsible for hitting my hosts resource limits. I'm on a shared cloud linux instance which spits out a 500 error when total memory usage exceeds 1GB. It's hitting that limit with just 7 users on the site. I'm using WC Vendors in a rebuild for an existing site, so once launched it will have thousands of users. Using P3 Plugin Performance Profiler, this was generated.

![resources](https://cloud.githubusercontent.com/assets/588846/9209433/58a2289e-402b-11e5-9cb0-ab922378d1c1.JPG)

On some shop pages, it takes an extraordinarily long time: 6+ seconds
![detailed resources](https://cloud.githubusercontent.com/assets/588846/9209484/98c3f2d6-402b-11e5-9d0e-e8e72dfbc2fa.png)

Has anyone else noticed this? Perhaps someone could give New Relic a try and see which lines of code are causing the spikes in load time and memory allocation?

**Comment by digitalchild** [comment]
You're the first to report this issue and we have a lot of people using WC Vendors with very large user sets and 10s of thousands of products. 

There are a lot of factors that could be causing the slow down. As I can see you have a lot of plugins running on the site and WC Vendors does have a lot to do however it shouldn't be taking 6 seconds to do anything. Unless you have a terrible webhost. Have you tested the resource usage with just the bare minimum running? WP + WC + WCV ? 

It's possible one of the plugins running in tandem with WC Vendors is slowing things down. WC Vendors hooks into woocommerce in the same places most plugins do. 

I don't have a dedicated host I can run new relic on at the moment but I'm always looking for ways to speed up the plugin. I will see what I can do to run some tests but unless we have a lot of people reporting performance issues it won't get the highest of priorities while work on pro continues.

**Comment by bentasm1** [comment]
3 Performance Profile is an EXCELLENT plugin if you are bad at statistical math.

Why?

It doesnt give you any useful data.

All it shows you is that out of all the things your page needed to load, WC Vendors too up about 70% of those resource loading times. And then it puts it in a fancy pie chart so you think you can see what plugins are “hurting” you performance-wise. Very useless!

What it does not do, is tell you a pie chart of what percentage of the page requires a plugin and then show performance data vs that chart. Look at all the other plugins you have — they all do basically nothing. 😉

If you disabled WC Vendors, all of a sudden your pie chart would show WooCommerce as taking up 40% of the pie chart. Does that mean WooCommerce is slow? No!

If you want to test performance, test load times. ( tools.pingdom.com/fpt/ ). Or, better yet, install “Query Monitor” plugin from the free wordpress repository. That will tell you what SQL queries are slow, and that’s what actually impacts your site loading time.

You should safely uninstall P3, delete it, burn it, and send it to its grave. 😉 Query Monitor will be much more useful for you.

Cheers

**Comment by archonic** [comment]
I'm also running query monitor and find it much more useful. There's a fair number of plugins but I'm in development and some will be removed before launch. The scan with P3 happens as an admin. Obviously most users are not admins and won't be loading the majority of these plugins. Once caching is setup, the experience will be totally different.

I recently fixed an issue that had my host spitting out 500 errors due to exceeding resources. I believe it was related to WP 4.2 and had to do with orphaned transients.

https://wordpress.org/support/topic/woocommerce-extremely-slow-after-wordpress-42-update/page/3?replies=65#post-7287798

After seeing P3 saying WC Vendors was the biggest hog, I figured I'd check if anyone else had the same experience. The site seems to be fine now. I'll uninstall P3 and close this. Thanks guys!

**Comment by archonic** [comment]
This may help someone with a similar issue - Admin Tweaks used to be in my good books but is was slowing down dashboard pages horribly. There was also an environment issue with Imagemagick. A recent version fixes security issues but causes an infinite loop with images over 1MB. We had to move to a VPS to isolate the imagemagick version but it was required for how busy the site is anyways.
