### ISSUE TITLE
Tracking Numbers

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#19]
http://www.wcvendors.com/help/topic/mark-shipped-and-tracking-number/

For vendor when they mark as shipped they can’t add a tracking number + UPS or DHl or an other for the customer can receive the tracking number.
Peraphs it s must be great if thy can add it, what do you think ?
+ send an email to the admin site when the vendor mark as shipped

**Comment by digitalchild** [comment]
Support for the WooThemes Shipment Tracking plugin is now integrated. Plugin is available here: 
http://www.woothemes.com/products/shipment-tracking/

see e48fcda
