### ISSUE TITLE
Can't pay commissions, cannot redeclare class OAuthException

### ISSUE THREAD

**Issue by archonic** [wcvendors/wcvendors#190]
I imagine this wouldn't be an issue if I had the PP Adaptive Payments gateway installed and configured, but this is what happens when I go to WC Vendors > Payments, select "Now" and try to pay out commissions:

    [12-Aug-2015 03:17:11 UTC] PHP Fatal error:  Cannot redeclare class OAuthException in /home/wedding-recyclejail/home/wedding-recycle/public_html/wp-content/plugins/wc-vendors/classes/gateways/PayPal_Masspay/api/lib/auth/PPAuth.php on line 42

**Comment by bentasm1** [comment]
If PayPal isnt configured, how do you expect the "now" button to work? :)

**Comment by archonic** [comment]
I have the free paypal gateway configured. If that gateway can't handle mass payments, that function shouldn't be available.

**Comment by bentasm1** [comment]
The PayPal gateway WooCommerce includes for free cant handle the payments.  It is not PayPal Adaptive Payments, which is required, by PayPal, to be setup in order to handle commissions.  The free one included in WooCommerce is just for sending one payment to your own PayPal account.  It's a completely separate API and plugin.  The PayPal Adaptive Payments gateway included free with WC Vendors is what you must use if you want to pay vendors on a schedule.

**Comment by bentasm1** [comment]
PS -- If you are using WC Vendors "paypalap" gateway, the error message is likely referring to a conflict with some facebook or twitter gateway, as they use OAuth as well, and PayPal only wants PayPal's OAuth to be enabled.  Something to inspect....

**Comment by archonic** [comment]
Was there any inspection before closing this? I've disabled my only social OAuth plugin (YITH WooCommerce Social Login) and the paypalap gateway is still choking on the fatal error above when attempting to pay commissions.

**Comment by bentasm1** [comment]
With 7000 websites running WC Vendors, and a large percentage of them using PayPalAP, if this was a WC Vendors issue, we'd hear about it non stop every day all day until it was fixed.  It's something on your site, what it is, is the question........

**Comment by archonic** [comment]
I did a grep on my wp-content folder and found a twitter OAuth.php in my theme which has a ton of duplicate class names with PPAuth.php. Obviously these OAuth class names are copypasta. Would it not make sense to namespace something as important as payment gateway classes?

**Comment by archonic** [comment]
I've fixed the issue for now by wrapping each class declaration in PayPal_Masspay/.../PPAuth with `if (!class_exists("ClassName")` like is done in PayPal_AdvPayments/.../PPAuth.php. If the code in these classes disagree, it could break billing - huge problem.

Themes often have social integration and there's a ton of other social login plugins and such that people should still be able to take advantage of. I think it makes a world of sense to either namespace each OAuth class or wrap everything in a unique class by the name of the "WcVendors" or something like that. Billing is important and it's a good policy to not be a part of the problem.
