### ISSUE TITLE
Lots of vendors, only 1 shows up with [wcv_vendorslist]

### ISSUE THREAD

**Issue by archonic** [wcvendors/wcvendors#191]
I have almost 1200 registered vendors but the `[wcv_vendorslist]` shortcode displays just one.

https://github.com/wcvendors/wcvendors/blob/69712555ebd1e5e7d06fab0e4eae422b095de952/classes/includes/class-wcv-shortcodes.php#L551

What are the options available other than "registered"? I believe the other vendors aren't showing up because they were created in the backend and assigned the role of "vendor", and therefore aren't "registered".

**Comment by bentasm1** [comment]
"registered" doesnt mean a user role, it means the date they registered.  You can use any combination of order/orderby parameters, all are native to WordPress and fully supported:

https://codex.wordpress.org/Class_Reference/WP_User_Query

Order & Orderby Parameters

orderby (string) - Sort retrieved users by parameter. Defaults to 'login'.
'ID' - Order by user id.
'display_name' - Order by user display name.
'name' / 'user_name' - Order by user name.
'login' / 'user_login' - Order by user login.
'nicename' / 'user_nicename' - Order by user nicename.
'email' / 'user_email' - Order by user email.
'url' / 'user_url' - Order by user url.
'registered' / 'user_registered' - Order by user registered date.
'post_count' - Order by user post count.
'meta_value' - Note that a 'meta_key=keyname' must also be present in the query (available with Version 3.7).

order (string) - Designates the ascending or descending order of the 'orderby' parameter. Defaults to 'ASC'.
'ASC' - ascending order from lowest to highest values (1, 2, 3; a, b, c).
'DESC' - descending order from highest to lowest values (3, 2, 1; c, b, a).

You say you have 1200 vendors registered but only see one with the shortcode.  Do all the vendors have products?  Try with [wcv_vendorslist showproducts=no] and see if that changes anything for you.

**Comment by archonic** [comment]
I guess it has nothing to do with `order_by`. Plenty of vendors have assigned products. `[wcv_vendorslist showproducts=no]` is still showing just one vendor. The one vendor that's showing is my personal test vendor which was done through the /my-account/ checkbox instead of assigning a vendor role to an existing user or registering a new user as a vendor in the dashboard. There has to be the difference between the two methods and the `wcv_vendorslist` query isn't picking up the latter.

**Comment by digitalchild** [comment]
If their role is vendor then the shortcode should pick them up. If they are a vendor but don't have their shop name set and saved then it won't show them. If they are showing up in sold by: then they are vendors and you have something else modifying the query before it gets to the shortcode. 

What plugins are you using?

**Comment by archonic** [comment]
That's it - shop name needs to be populated for them to show up. I think that's poor usability. Do you guys think it's reasonable to just use their username in place of their shop name if shop name isn't populated?

**Comment by bentasm1** [comment]
You could always write a quick filter upon registration to add their username as the store name automatically.  Or duplicate the shortcode and remove the parameter that checks for that.

**Comment by archonic** [comment]
That doesn't solve the problem of the ~1100 vendors I have with no shop name. But more importantly, this is a usability issue. Someone who registers as a seller and adds their products, isn't listed on the vendors page. I could inform users to visit the shop settings page and create / save their shop name, but that's a poor solution and not very intuitive as the reason for why they wouldn't appear on the vendors page.

**Comment by bentasm1** [comment]
https://gist.github.com/bentasm1/6c54ee4f6dffae9f77e8 might help.  This would be a modification to the /dashboard/links.php template.  Shows an alert to the Vendor when their store name is not set.

-or-

For the 1100 vendors you already have, you could just add the custom meta key in bulk with phpmyadmin, or with any meta plugins that would do it in bulk too for each user.  The meta key for the usersmeta is "pv_shop_name" and the value would be whatever you like.

**Comment by digitalchild** [comment]
You could easily write code to update the 1100 vendors using the required user meta to input into the required wc vendors user meta. Then as @bentasm1 suggests, create a filter to hook into new registered users. 

The only 'usability issue' here is that we allow vendors to publish products without those fields populated. This is legacy from when we took over the plugin and in the future publishing products will be disabled until those fields are populated.

**Comment by archonic** [comment]
Writing migrations in php kind of sketches me out. I think I'll go the route of informing (very loudly) sellers after they sign in that they should populate their paypal email and shop name.

I still consider this and #192 to be bugs. It shouldn't require little hacks to direct users to fill out things that weren't asked of them at registration in order for their experience to work - i.e. to get listed on the store page and get paid. If I were paying $99/year for that experience, I'd be disappointed.
