### ISSUE TITLE
Feature request: No paypal email address, assume user email

### ISSUE THREAD

**Issue by archonic** [wcvendors/wcvendors#192]
My client is moving from a different system to one with WC Vendors. We started out with Product Vendors and wasted a good amount of time trying to make it fit before finding WC Vendors. All of the vendors were entered when we had Product Vendors.

Product Vendors assumes the users email is their paypal address. I like that WC Vendors offers the choice of a different paypal email but because these vendors were created by an admin in the backend, the paypal address and shop name isn't populated.

In the event that a paypal address isn't present, could we assume the users email for comissions?

**Comment by bentasm1** [comment]
No, unfortunately we can not add that functionality because doing that would break many other sites where not all vendors use PayPal and that would give them nothing but checkout errors.

You could modify the PayPalAP gateway that instead of checking for the shop settings paypal email, to just use the user_email from the usermeta.  You'd have to modify the core, and keep it up to date each WC Vendors update, though.....  But should still be a simple one line change.  Or perhaps @digitalchild  could add a filter that you can use to insert your own email address function, I'm not sure how all that would work though.

**Comment by archonic** [comment]
Assuming the usermeta email as the paypal address creates problems with the existing paypal email field. I would have to remove it and ensure all my users have a valid paypal address as their usermeta email. Wouldn't it be easier to, when running commissions payments, check for the paypal gateway, check for the presence of the paypal email and if empty, assume the usermeta email?

**Comment by bentasm1** [comment]
You could remove the PayPal email field from the Shop Settings by emptying out the /dashboard/settings/paypal-email-form.php file.

We can't add this code for you because it would break many sites that use the plugin already.  What works for you might not be what works for all sites. :)

**Comment by MattyLB** [comment]
Josh,

Your best bet might be to send an email out to all vendors explaining an
update to the site requires them to create a store name and specify a
PayPal email address. Anyone who doesn't add this on their own by a certain
date would have default info used which may not fit their branding, etc.

This way you won't get bombarded by support calls asking why you
automatically used X for their store name, etc without asking them first,
and will make the transition a happier experience for them.

Just a thought and it will cover you from must complaints.

**Comment by digitalchild** [comment]
What I would do is this. 

Step 1. Write a custom bit of code to update all vendors pv_paypal with their user email address. This runs once and updates all existing vendors

Step 2. Write an action that hooks into set_user_role (https://codex.wordpress.org/Plugin_API/Action_Reference/set_user_role) and check if the role is vendor and update the pv_paypal user meta with this. You would use the same function to update the user meta when they change their settings in the wp-dashboard or front end (although it's a required field on the front end). 

I know this is a little more work but will solve your current issue. I will look into possibly having a fall back to user email in the future.

**Comment by archonic** [comment]
Here's the solution I came up with for this and #191 in functions.php:


    # Remove WC Vendor redirect, add my own
    remove_filter( 'woocommerce_registration_redirect', array( 'WCV_Vendor_Signup', 'redirect_to_vendor_dash' ) );
    add_filter('woocommerce_registration_redirect', 'wr_wc_registration_redirect', 12);
    function wr_wc_registration_redirect( $redirect_to ) {
      $redirect_to = '/my-account';
      return $redirect_to;
    }

    # Add notice about unpopulated vendor data
    add_action( 'woocommerce_before_my_account', 'fill_in_shop_settings_message' );
    function fill_in_shop_settings_message() {
      $shop_settings_page = "/seller-dashboard/shop_settings/";
      $author_id = get_current_user_id();

      $shop_name_set = WCV_Vendors::get_vendor_shop_name( $author_id );

      $paypal_email = get_user_meta( $author_id, 'pv_paypal', true);
      $paypal_email_set = !empty($paypal_email);

      $vendor_login = get_userdata($author_id);

      if ( ($shop_name_set == $vendor_login->user_login) || !$paypal_email_set ) {
        echo '<div class="alert alert-info" role="alert">';
        echo '<a href="'.$shop_settings_page.'" class="btn btn-danger pull-right"><span class="dashicons dashicons-admin-generic"></span> Store settings</a>';
        if ($shop_name_set == $vendor_login->user_login)
          echo '<strong>Your store name is not set!</strong> We need this to list you on the stores page.<br>';
        if(!$paypal_email_set)
          echo '<strong>Your PayPal email is not set!</strong> We need this to send you your commission.' . $paypal_email_set;
        echo '</div>';
      }
    }

Until there's a consistent experience either on the backend with WC Vendors free or on the frontend with WC Vendors Pro, I think this is decent default behaviour.

**Comment by MattyLB** [comment]
Brilliant! Great solution, Josh.  😃

**Comment by archonic** [comment]
Can someone tell me if the paypal address field is required in WC Vendors Pro? The above solution is only a notice and there's still users falling through the cracks and money being held by paypal in some kind of mystery non-account. This is my number 1 concern on an active site with ~1700 vendors.

**Comment by bentasm1** [comment]
@archonic Yes, the PayPal field is required on the Shop Settings page.

**Comment by MattyLB** [comment]
@archonic <https://github.com/archonic> - i thought this was understood
when i suggested you give them a timeframe before migration that they
needed to supply you with a desired PayPal address or it would be
automatically populated with the address pulled from their old account.
Sounds like you have a mini mess on your hands unless the WCV guys or
PayPal knows how to account for the misguided funds. Actually, it surprises
me that PayPal would even allow the transaction without an address for each
part of the transaction - but that's another issue.

Good luck.

**Comment by bentasm1** [comment]
I thought of a rather simple fix for this.  Just edit the /dashboard/links.php file which is the menu bar for WC Vendors.  Just wrap the buttons in an if statement to check if the vendor has set their PayPal email, then show buttons, otherwise only show the Shop Settings button and a big note saying before they can list products they must add their PayPal email address.  Should be a pretty easy solution and take just a minute to write.

With this method, vendors wont be able to add or edit products till their PP email is set.

**Comment by MattyLB** [comment]
That is a good second step. But the first step is to disable all products
from vendors who do not have a PayPal address setup, because apparently not
all vendors are logging in to do their part before sales of their items are
taking place. Simple solution: they used their old account address for
PayPal before the migration, set it as their PayPal address now since they
missed the migration boat. They can always change it later. This is based
on my understanding of the scenario from Josh that led to my suggestions
from my own migration experiences.

**Comment by bentasm1** [comment]
Here is the replacement /dashboard/links.php code for this @archonic 

https://gist.github.com/bentasm1/495fb30da2a848a33b00

**Comment by archonic** [comment]
Part of the problem is the vendors were entered by a team of people migrating data from a different system. Some of these migrators didn't realize the paypal address should be filled in.

My client miscommunicated (big surprise) - there's no payments to a mystery account or void. The commission's transactions that fail are held on paypal by the application and can be reattempted from the WooCommerce>WC Vendors > Payments.

There was one order that was curious - this was the reason my client thought there was lost money. The commission was marked paid for a vendor that had no paypal address. I checked the IPN history and the commission payment was successfully sent to the email that was in the user field. Is there any kind of fall back email sent by WC Vendors to paypal? Or is the only way that was possible was the vendor had their paypal address filled in at the time of the order, then later removed it? If it was the earlier method, then that's great cause that's what this issue is about - a graceful fall back to the user email field.

@bentasm1 Thanks for the code, but this is the same kind of solution I mentioned above - dropped into functions.php, it will show a loud (with bootstrap styles) notice to vendors to visit shop settings and fill in their paypal address to get paid, and their shop name to be shown on the stores page. The redirect stuff is to make sure that vendors see this message on the my-account page right after both registering and logging in. Hiding the add products button helps a bit, but I have other add products buttons. I consider this a bandaid solution.

There's a few other ways to solve this that would be more ideal. A graceful fallback to the user email is a decent last resort. Another solution would be a required field for the paypal address on the register form, and/or not allowing the posting of products unless a vendor has a valid paypal address - this could / should be checked through the API. A valid email isn't necessarily a valid paypal address. I'd personally like to see all of these solutions implemented.

I think that's all we (developers) could do to ensure commission payment happens. It would still be possible to register with a valid paypal address, post a product, then remove the paypal address, but you have to draw the line somewhere.
