### ISSUE TITLE
Variations Product Images

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#194]
When adding variations for a new product, clicking the blue "Upload an image" button does not allow vendors to upload an image.  It errors with "You don't have permission to attach files to this post.".  Vendors can choose existing images from the media library, but simply can not add upload new images.

As reported here by Drew:

https://www.wcvendors.com/help/topic/upload-permission-issues-on-variations/

**Comment by bentasm1** [comment]
Assigning the the "edit_product" capability and update the Vendor role will fix this, but I'm not sure what else it will allow at the same time, so need a little more investigation on it.  That will allow the uploader to work on variations.  On dev box the capability is added, and user role editor is installed to toggle it.  

Note:  We already allow the "edit_products" capability.  What's the deal with edit_product and edit_products in the code?  Is it both or one or what?  Hard to tell browsing Woo's source code.

**Comment by drewgierach** [comment]
Please do not hesitate to reach out to me if additional information is required. The role change fix suggested above is working while this is being resolved.

**Comment by bentasm1** [comment]
@drewgierach Thanks much.  The role change appears to only be related to ajax calls for adding product images, so most likely, the permanent bug fix will be to add this capability to the Vendor role.  I'll have Jamie triple check my work of course, but browsing Woo's code I cant see anything else this capability actually does.  So what appears to be a temporary fix for your site, is likely going to be the permanent fix automatically upgraded in the next version of WC Vendors.

If you find anything out of the ordinary that a Vendor should *not* be able to do, that's where we'd have to get creative and run some checks before allowing the capability.  So let us know if you do!

Cheers
