### ISSUE TITLE
get order items per vendor

### ISSUE THREAD

**Issue by Spreeuw** [wcvendors/wcvendors#196]
I have received several request to print out invoices and packing slips for WC vendor orders with [WooCommerce PDF Invoices & Packing Slips](https://wordpress.org/support/plugin/woocommerce-pdf-invoices-packing-slips). These documents should only include the order items for a particular vendor.
Your data structure makes it difficult to do this, and I was thinking of ways to solve this.

I see two options:

1) Storing the vendor ID in each line item so that it is easier to get the selection of order items for a particular vendor. This is the easy solution in terms of added code, but it doesn't add much usefulness and total cost and taxes per vendor would still need to be calculated manually.

2) Creating separate child orders for each vendor. This would work exactly how WooCommerce refunds currently work: a new order is created, that is not directly visible to the user (or shop manager). Because the refund class extends the order class, this means that you can use all the same functions.

Option 2 is by far the most flexible and probably also provides you with many useful other features (at the very least it makes your existing vendor admin code much more transparant and flexible). If you look at the implementation of refunds in Woocommerce (main class [here](https://github.com/woothemes/woocommerce/blob/master/includes/class-wc-order-refund.php), refund creation [here](https://github.com/woothemes/woocommerce/blob/630c14124c40aedbaf812001565fc662250aca8f/includes/wc-order-functions.php#L600))  you will see that it is not very difficult to implement.

I'd love to hear your thoughts!

**Comment by GoTeamScotch** [comment]
I'd like to bump this topic if I can and lend a hand where I can. In researching this I found several other threads asking the same thing. My site absolutely needs this so I'm going to make it work one way or another, and it would be great if others can benefit from my work, right? I have been working on this lately and have made some progress towards a band-aid hack that gets the two plugins to work with each other but it would be great to get official support from both plugins because from what I can tell both require updates in order to be compatible, but it's nothing crazy.

Here's a list of a few hurdles to overcome:
- PDF plugin: permissions need to change to allow a user who is a vendor to be able to get PDFs generated. Their plugin uses the following check that gets in the way:

File: woocommerce-pdf-invoices-packing-slips\includes\class-wcpdf-export.php line 352
```
// Check the user privileges
if( !current_user_can( 'manage_woocommerce_orders' ) && !current_user_can( 'edit_shop_orders' ) && !isset( $_GET['my-account'] ) ) {
	wp_die( __( 'You do not have sufficient permissions to access this page.', 'wpo_wcpdf' ) );
}
```
If you're a vendor, you don't have the capabilities to go forward so it stops here. I changed this part to:
```
if( !current_user_can( 'manage_woocommerce_orders' ) && !current_user_can( 'edit_shop_orders' ) && !isset( $_GET['my-account'] ) && !in_array('vendor', $GLOBALS['current_user']->roles) ) {
	wp_die( __( 'You do not have sufficient permissions to access this page.', 'wpo_wcpdf' ) );
}
```
Ideally, the author would add a filter here that could let us hook in and do additional checks but this works for now.

- Vendor needs a way to get PDFs when needed. This one is actually rather easy. Copy the file wc-vendors\templates\dashboard\order.php to your theme under a folder called "wc-vendors" then open it up. Go down to the last TD tag in the table's body. Should be at about line 61. For this next part, I just copied code from the PDF plugin to generate the PDF links. This is the same code that generates the buttons in the Orders admin area.
```
if (class_exists('WooCommerce_PDF_Invoices')) {
	$listing_actions = array(
		'invoice'		=> array (
			'url'		=> wp_nonce_url( admin_url( 'admin-ajax.php?action=generate_wpo_wcpdf&template_type=invoice&order_ids=' . $order->id ), 'generate_wpo_wcpdf' ),
			'img'		=> WooCommerce_PDF_Invoices::$plugin_url . 'images/invoice.png',
			'alt'		=> __( 'PDF Invoice', 'wpo_wcpdf' ),
		),
		'packing-slip'	=> array (
			'url'		=> wp_nonce_url( admin_url( 'admin-ajax.php?action=generate_wpo_wcpdf&template_type=packing-slip&order_ids=' . $order->id ), 'generate_wpo_wcpdf' ),
			'img'		=> WooCommerce_PDF_Invoices::$plugin_url . 'images/packing-slip.png',
			'alt'		=> __( 'PDF Packing Slip', 'wpo_wcpdf' ),
		),
	);
	
	$listing_actions = apply_filters( 'wpo_wcpdf_listing_actions', $listing_actions, $order );			
	
	foreach ($listing_actions as $action => $data) {
		?>
		<a href="<?php echo $data['url']; ?>" class="button tips wpo_wcpdf <?php echo $action; ?>" target="_blank" alt="<?php echo $data['alt']; ?>" data-tip="<?php echo $data['alt']; ?>">
			<img src="<?php echo $data['img']; ?>" alt="<?php echo $data['alt']; ?>" width="16">
		</a>
		<?php
	}
}
```
After you paste this in there, you'll notice there will be two new buttons on the vendor's dashboard page. If you made the other edit discussed above, then you should now be able to click on this and get a PDF as a vendor.

- The PDF generated needs to be filtered to only the vendor's products. For this, we can use WooCommerce's filters "woocommerce_order_get_items" and "woocommerce_get_order_item_totals". You can put this code in your theme's functions.php or make a separate plugin to house it.
```
if (defined('DOING_AJAX') && DOING_AJAX && isset($_GET['action']) && $_GET['action'] == 'generate_wpo_wcpdf') {
	if (!class_exists('WCV_Vendors'))
		require_once(WP_PLUGIN_DIR . '/wc-vendors/classes/class-vendors.php');
	
	// this filter is fired any time a order PDF is generated, we only need it to run for vendors...
	if (WCV_Vendors::is_vendor(get_current_user_id())) {
		add_filter('woocommerce_order_get_items', array($this, 'check_items'), 15, 2);
		add_filter('woocommerce_get_order_item_totals', array( $this, 'check_order_totals' ), 15, 2);
	}
}
// from WC Vendors class-wc-notify-vendor.php
function check_items( $items, $order )
{	
	foreach ( $items as $key => $product ) {

		//  If this is a line item 
		if ($product['type'] == 'line_item') { 

			$author = WCV_Vendors::get_vendor_from_product( $product[ 'product_id' ] );

			if ( get_current_user_id() != $author) {
				unset( $items[ $key ] );
				continue;
			} else {
				$commission_due = WCV_Commission::calculate_commission( $product[ 'line_subtotal' ], $product[ 'product_id' ], $order );

				$items[ $key ][ 'line_subtotal' ] = $commission_due;
				$items[ $key ][ 'line_total' ]    = $commission_due;
				// Don't display tax if give tax is not enabled. 
				// if ( !WC_Vendors::$pv_options->get_option( 'give_tax' ) ) { 
				// 	unset($items[ $key ][ 'line_tax' ]) ; 
				// }
			}
		}

	}


	return $items;
}

// from WC Vendors class-wc-notify-vendor.php
function check_order_totals( $total_rows, $order )
{

	$commission_label 	= apply_filters('wcv_notify_vendor_commission_label', __( 'Commission Subtotal:', 'wcvendors' ) ) ;
	$return[ 'cart_subtotal' ]            = $total_rows[ 'cart_subtotal' ];
	$return[ 'cart_subtotal' ][ 'label' ] = $commission_label; 

	if ( WC_Vendors::$pv_options->get_option( 'give_tax' ) ) {
		$return['tax_subtotal'] = array( 'label' => '', 'value' => ''); 
		$return[ 'tax_subtotal']['label'] = apply_filters('wcv_notify_vendor_tax_label', __( 'Tax Subtotal:', 'wcvendors' ) ) ;
	} 

	$dues = WCV_Vendors::get_vendor_dues_from_order( $order );
	$current_user_id = get_current_user_id();
	foreach ( $dues as $due ) {
		if ( $current_user_id == $due['vendor_id'] ) {
			if (!empty($return[ 'shipping' ]))	$return[ 'shipping' ]          = $total_rows[ 'shipping' ];
			$return[ 'shipping' ]['label']   = __( 'Shipping Subtotal:', 'wcvendors' );
			$return[ 'shipping' ][ 'value' ] = woocommerce_price( $due['shipping'] );
			if ( WC_Vendors::$pv_options->get_option( 'give_tax' ) ) {
				$return[ 'tax_subtotal']['value'] += $due['tax']; 
			}
			break;
		}
	}
	// Format tax price 
	if ( WC_Vendors::$pv_options->get_option( 'give_tax' ) ) { 
		$return[ 'tax_subtotal']['value'] = woocommerce_price( $return[ 'tax_subtotal']['value'] ); 
	} 

	return $return;
}
```
- PDF needs to be attached to emails when vendors are notified of new orders. This is one I have yet to solve just from lack of time. Once my two vendors were able to get the PDFs I kind of stopped trying as hard on this. But from what I can see, we need to hook into WooCommerce's action "woocommerce_email_attachments" which passes three variables: $attachments, $status , and $order. So from that we need to determine if the order contains vendor products and then trigger a PDF to be generated and stored somewhere temporarily. Also, when the PDF is made it's going to fire those same filters I spoke of earlier, so maybe the IF statement needs to changed so that it fires even where that DO_AJAX line exists. This part I could use a hand with if anybody is willing.

I hope that helped get the conversation started. Like I said, I've seen the question asked a bunch of times but no solution as of yet. If anyone sees anything horrendous in my code please let me know!

Thanks,
Jordan

**Comment by digitalchild** [comment]
@GoTeamScotch Unless you've modified those two functions from ``` class-wc-notify-vendor.php``` you can actually just reference them in your filter. 

``` add_filter('woocommerce_order_get_items', array( 'WC_Email_Notify_Vendor', 'check_items'), 15, 2);
    add_filter('woocommerce_get_order_item_totals', array( 'WC_Email_Notify_Vendor', 'check_order_totals' ), 15, 2);```

I'll take a look further regarding how we do orders. This is something that has been this way since we forked the plugin and I just haven't had time to look at how we manage orders, but it is on my roadmap to address after we've released pro on the 1st of October.

**Comment by Spreeuw** [comment]
@GoTeamScotch thanks for your input!

1) Adding the buttons in the vendor admin. This should be much simpler as soon as the VC Vendor devs add an action hook to output vendor-order specific links/actions, much like the `woocommerce_admin_order_actions_end` hook.

2) I wouldn't use the `woocommerce_order_get_items` and  `woocommerce_get_order_item_totals` directly, as this will then apply to all woocommerce output. This doesn't matter in how you currently use it, but this would mess up things as soon as you want to attach it to an email (as there won't be any vendor user active). You could either use  `wpo_wcpdf_raw_order_totals` & `wpo_wcpdf_order_items_data` (<= with an extra wrapper), or put the filters in `wpo_wcpdf_process_template`, to make sure they only run when a PDF is created.

3) Attaching to emails. Rather than using `woocommerce_email_attachments`, I would use `wpo_wcpdf_email_allowed_statuses`, and add the email ID for the vendor emails. You could then set some global variable to indicate that the invoice should be filtered for the vender (with the vendor ID).

The bad news is that I cannot add it like this to the core plugin, because the order totals and order items filter are only part of what needs to be added to have full support. This is where my suggestion to use child orders comes in.

Hope the above helps you get a little further though!

**Comment by GoTeamScotch** [comment]
@digitalchild good call. I don't know why that didn't occur to me. Using that works as expected. Thanks!

@Spreeuw I've submitted a [pull request] (https://github.com/wcvendors/wcvendors/pull/201) based on a change I did my [fork] (https://github.com/GoTeamScotch/wcvendors) that addresses this. I've put the links on the Orders table into a filterable array that is later looped through and displayed in the table. Using this, you can add/remove links (like a PDF button) as needed. See the example in my [pull request] (https://github.com/wcvendors/wcvendors/pull/201) for details.
Great idea about using those other filters you mentioned. That would cut down some overhead. I haven't scoured the PDF plugin's docs and source code nearly as much as I should so that's very helpful. I've begun trying to reach out to the PDF plugin's author to see if he/she is willing to assist, even if it's nothing more than accepting a pull request made by me (or one of you guys). I've linked this thread to them.

Overall though, the idea of using child orders is very interesting. I am curious what kind of changes that would require of this plugin.

**Comment by digitalchild** [comment]
I'll take a look at the pull request sometime this weekend. With regards to using child orders would require a massive re-write. As it fundamentally changes how the plugin functions.

**Comment by Spreeuw** [comment]
> I've begun trying to reach out to the PDF plugin's author
That would be me :grin:

**Comment by GoTeamScotch** [comment]
Ohh I see. I thought you were just someone trying to request a new feature. That would explain your knowledge of the pdf plugin! :P

**Comment by digitalchild** [comment]
@Spreeuw with regards to changing how orders work, it would require a lot of work as the way orders are currently referenced would mean pretty much all of this would need to change. Yes I could start with a soft change. I'll be looking to re-write the order management in version 2.0 of free but for now it doesn't have a high priority. 

The information regarding an order and a vendor and item is all available on our commissions table so it is currently possible to glue the information you require together.

**Comment by Spreeuw** [comment]
@digitalchild I understand. I know I can glue the information together, but it would require me to filter the result for every single function call that normally refers to the $order object. I'd rather not do that as it will make it quite hard to maintain this code (and still be a band-aid solution).

Either way, I think this should be a fun project to make our plugins compatible, so I will fork your project and make a proposal for this child-order implementation. From a compatibility point of view it may not be a bad idea to introduce this concept to the current version (again, as a complementary system at first), then fully adopt it (or not) by the time you are ready for 2.0.
I'll post here when I have the basic system ready, then we have something to shoot at and we can discuss pros/cons/next steps.

**Comment by Spreeuw** [comment]
@GoTeamScotch 
With the new privs check filter you added, you can use the following code, based on your own code above. It's still somewhat hacky (calling the non-static functions statically for example), but it does work. 
```php
add_filter( 'wpo_wcpdf_check_privs', 'wpo_wcpdf_wcvendor_privs', 10, 2 );
function wpo_wcpdf_wcvendor_privs ( $not_allowed, $order_ids ) {
	// check if user is vendor
	if ( $not_allowed && in_array('vendor', $GLOBALS['current_user']->roles) ) {
		// get all vendor orders by vendor products
		// method is non-static, ignore for now: @
		$vendor_products = @WCV_Vendor_Order_Page::get_vendor_products( get_current_user_id() );
		$product_ids = array();
		foreach ($vendor_products as $_product) {
			$product_ids[] = $_product->ID;
		}
		$vendor_orders = @WCV_Vendor_Order_Page::get_orders_for_vendor_products( $product_ids );
		// extract order_id from objects
		$vendor_order_ids = array();
		foreach ($vendor_orders as $vendor_order) {
			$vendor_order_ids[] = $vendor_order->order_id;
		}

		// check if all order_ids are from vendor
		foreach ($order_ids as $order_id) {
			if (!in_array( $order_id, $vendor_order_ids)) {
				// one of the order_ids is not from the vendor!
				return true; // not allowed!
			}
		}

		// if we got here, that means the user is a vendor and all orders belong to this vendor
		return false; // allowed!
	} else {
		return $not_allowed; // preserve original check result
	}
}

add_filter( 'wpo_wcpdf_process_template', 'wpo_wcpdf_filter_vendors' );
function wpo_wcpdf_filter_vendors ($template_type) {
	if (!class_exists('WCV_Vendors'))
		require_once(WP_PLUGIN_DIR . '/wc-vendors/classes/class-vendors.php');

	// this filter is fired any time a order PDF is generated, we only need it to run for vendors...
	if (WCV_Vendors::is_vendor(get_current_user_id())) {
		$vendor_email = new WC_Email_Notify_Vendor;
		$vendor_email->current_vendor = get_current_user_id();
		add_filter('woocommerce_order_get_items', array( $vendor_email, 'check_items'), 15, 2);
		add_filter('woocommerce_get_order_item_totals', array( $vendor_email, 'check_order_totals' ), 15, 2);
	}
}

add_filter( 'wcvendors_order_actions', 'wpo_wcpdf_vendor_actions', 10, 2 );
function wpo_wcpdf_vendor_actions ( $order_actions, $order ) {
	$vendor_pdf_actions = array(
		'invoice'       => array (
			'class'     => 'button tips wpo_wcpdf invoice',
			'url'       => wp_nonce_url( admin_url( 'admin-ajax.php?action=generate_wpo_wcpdf&template_type=invoice&order_ids=' . $order->id ), 'generate_wpo_wcpdf' ),
			'content'   => sprintf( '<img src="%s" width="16">', WooCommerce_PDF_Invoices::$plugin_url . 'images/invoice.png'),
		),
		'packing-slip'       => array (
			'class'     => 'button tips wpo_wcpdf packing-slip',
			'url'       => wp_nonce_url( admin_url( 'admin-ajax.php?action=generate_wpo_wcpdf&template_type=packing-slip&order_ids=' . $order->id ), 'generate_wpo_wcpdf' ),
			'content'   => sprintf( '<img src="%s" width="16">', WooCommerce_PDF_Invoices::$plugin_url . 'images/packing-slip.png'),
		),
	);

	return array_merge( $order_actions, $vendor_pdf_actions);
}
```

**Comment by Spreeuw** [comment]
@GoTeamScotch : for my understanding: would you like to get an invoice with the commission prices, or with the prices that the customer paid? For whom is it intended? Because if the invoice should show commission prices, I guess it is a way for the vendor to create an invoice to send to the show owner? Should the vendor address then be on it? Vice versa, if it is an invoice for the customer, would it not make more sense to display the prices he/she paid?

Lot's of questions, I hope you can clarify this for me :)

**Comment by bentasm1** [comment]
Perhaps add a filter that would set whether it shows the full price of the product, or the price of the commission of the product, then the admin can choose which price the PDF Invoice would show?

**Comment by GoTeamScotch** [comment]
In my case I am trying to display the prices that the customer paid, not the commission amount the vendor earned. However, I can imagine that feature will be requested by someone eventually so it might be good to think about supporting.

I'm with @bentasm1, setting an option somewhere seems like a good way to meet multiple needs.

**Comment by Spreeuw** [comment]
@GoTeamScotch many people use the invoices not only for internal use, but also include it in the box when they ship the items. Some people prefer not to do this (for example when the products are a gift) and send the packing slip. Others use the packing slip only internally for order picking.

However, I don't run a marketplace, so I have no idea of wc-vendor specific requirements.
I asked this, because you applied the items filter from the vendor emails, which uses the commisions rather than the actual prices, which made me wonder what that would be used for.

**Comment by GoTeamScotch** [comment]
Oh ok I didn't even catch that. All my vendors currently get 100% commission right now so that's why I didn't catch it. Other people may want to show commission OR what was charged to the customer. I still think it should be a setting that included in WC Vendors, perhaps a new settings field on WC Vendors' settings page which holds a checkbox that dictates whether PDFs are generated using commission vs sale price. For me personally, I know it would be best to have that checkbox target either an invoice or a packing slip but not both, so maybe we can work that in as well. Maybe a set of two radio selects where one is packing slips and the other is invoices and the two options for each are Commission or Sale Price? If commission is listed, I almost think it would be best to have it listed under each item similar to how meta is displayed, where the commission amount isn't the main focus (i.e. listed to the right in the totals) but rather as an extra piece of info. It would be great to also have another line in the totals section where "total commission earned" is listed as well. Thoughts?

**Comment by Spreeuw** [comment]
@GoTeamScotch Yes a setting would be most convenient, although I'm not sure where this setting should reside because not all WC Vendor users will use PDF Invoices. Perhaps this could be a setting that in the first place refers to the email sent to the vendor. Not sure about this though.

Invoice attachment is definitely possible. The Professional extension of the PDF Invoice plugin automatically detects all custom/non-default WooCommerce emails, but I think I will port this function to the free version too.

**Comment by Spreeuw** [comment]
@bentasm1 @digitalchild
I have forked wcvendors to demonstrate the child order functionality, you can check it out here:
https://github.com/Spreeuw/wcvendors

This is the most basic implementation, I haven't actually rewritten any core functions to make use of the new child orders. However, this opens up a lof of possibilities to get all order information (/all orders) for a specific vendor much more easily, make recalculations and sync the child orders with the parent order. The items in the child order have the original item id's stored, which comes in handy when the data needs to be synced at some point. I have also stored the commission as line item meta.

These child orders are created as soon as an order is placed (woocommerce_checkout_order_processed). The new Vendor Order works exactly like regular orders, except that they only contain the line items data / totals data / etc. that applies to the vendor. Simply load the order with
```php
$vendor_order = new WC_Order_Vendor( $vendor_order_id );
```
and from there on you can do everything that you were used to doing with the $order object.

It gets really interesting when you want to assign different/multiple shipping methods to each vendor or if you need to make tax calculations, if you want to generate vendor specific reports, etc. Many of the commission database calls can be made obsolete (or at least much more simple), and functions that filter the items for a specific vendor (which currently is bounced between several different functions) are now a simple $vendor_order->get_items() call.

Even this simple implementation fixes the issue this thread started with: Because the "vendor order" extends the original WooCommerce order class, all class functions can be used on the vendor order object.

Let me know what you guys think or if anything is unclear!

**Comment by Spreeuw** [comment]
I have added a helper function that makes testing functionality of these vendor orders easier:
```php
$vendor_orders = WCV_Vendors::get_vendor_orders( $order_id );
```
This returns an array of all vendor order objects for a particular order.

**Comment by Spreeuw** [comment]
@bentasm1 @digitalchild
I was wondering if you guys had a chance to look at my fork yet!
https://github.com/Spreeuw/wcvendors

I'd love to hear your feedback

**Comment by digitalchild** [comment]
@Spreeuw Sorry I haven't had a look yet. I've been so busy with getting pro released that I haven't had a chance to look into it. I'm very excited to look at it, I just won't have time till after the 1st October to look into this. I've wanted to move orders to this kind of system for a while now so if your ground work is solid, it'll be a great first step to cleaning things up. 

Thanks for your patience.

**Comment by Spreeuw** [comment]
@digitalchild any news?

**Comment by digitalchild** [comment]
I've set aside sometime this month to look into this and start to migrate to complete sub orders for vendors.

**Comment by Spreeuw** [comment]
Thanks for the quick reply! I recommend going for a soft transition, introducing the sub orders without using it for the core functions. This way you can test the functionality without running the risk of breaking existing installations. This will also shorten the time to market a lot :)
Let me know if you have any questions regarding the [example implementation](https://github.com/Spreeuw/wcvendors)!

**Comment by digitalchild** [comment]
Oh I intend to migrate slowly, I'm maintaining two plugins now so I have to plan everything very throughly.

**Comment by vinaynihal3** [comment]
I am encountering troubles when an order has products from different vendors.
I have added <br>`
add_filter('woocommerce_order_get_items', array($this, 'check_items'), 15, 2);
add_filter('woocommerce_get_order_item_totals', array( $this, 'check_order_totals' ), 15, 2);
`
in my child theme functions.php
As long as above code is not commented my Pdf does nt contain any products.
Can somebody pls help.

**Comment by bentasm1** [comment]
@vinaynihal3 your code is likely broken, you cant use $this without being in the class.  You need to reference the full class/function.  Seek help from a PHP developer to correct your custom code.

**Comment by vinaynihal3** [comment]
@bentasm1 Thanks. your suggestion, it worked. 
 I wanted the invoice to print total of all MRP of the product for the logged in vendor, so I just summed up the individual prices in php for loop. Is there anyway, i could get those from the database like how wc-vendors get the commission amount from tables.
(What I did, I will not suggest to anyone but I couldnt figure out any other way).

**Comment by bentasm1** [comment]
Github is not for tech support, its for bug reporting & development.

www.wcvendors.com/help/

**Comment by Spreeuw** [comment]
@vinaynihal3 the code you copy pasted came from an old example, it's better to use this (a later post in this thread): https://github.com/wcvendors/wcvendors/issues/196#issuecomment-138639644

**Comment by Spreeuw** [comment]
@digitalchild, any news on the sub-order implementation? Every once in a while I get a request from people asking me about compatibility, it would be great if we can fix this!

**Comment by bentasm1** [comment]
Probably around the end of summer.

**Comment by Spreeuw** [comment]
2017?

I made an [example implementation](https://github.com/wcvendors/wcvendors/issues/196#issuecomment-139222147) before that you could even just use as is. You can keep all your core methods and add this to it, which would allow for a soft transition (slowly starting to integrate it with /rebuilding your core methods). I'd really appreciate it, and many others with me!

**Comment by bentasm1** [comment]
In the USA, it is April.  It's spring.  Summer starts in a few months. :)

**Comment by bentasm1** [comment]
PS -- The example implementation does not factor in other plugins, integrations, or WC Vendors Pro.  We cant just copy/paste your code. ;)

**Comment by Spreeuw** [comment]
I'm in Europe, it's spring here too, but the 'probably around end of summer' sounded ore vague than the 'I've set aside sometime this month' last December.

I know the example implementation doesn't factor in other plugins or integrations, but that doesn't matter because you can run them side by side. My proposal uses WooCommerce Core functions, extending the regular WC Order to a Vendor Order, and then adds a few helper functions. That's it - the basic implementation is really simple (and should be), but offers a lot of freedom for tieing this up with core functions (and is not restricting anything at all in that sense).

**Comment by bentasm1** [comment]
Understood.  We have this feature planned for WC Vendors Free v2.0 with a bunch of other stuff all at once.  Jamie is on his way to America from Australia to visit me for a few weeks and have a coding marathon, we'll be reviewing this in detail when he arrives.  Still, our first priority is finishing features promised for WC Vendors Pro, once that is done, we'll be doing all the other upgrades.

**Comment by digitalchild** [comment]
Good news @Spreeuw I've integrated your suggested soft suborder changes. Thanks for the contrib!

**Comment by Spreeuw** [comment]
Awesome, thanks - that's good news indeed! With this in place I'm going to add WC Vendors support to the next release of WooCommerce PDF Invoices & Packing Slips!

**Comment by bentasm1** [comment]
Fantastic, thanks! :)  Feel free to test with the current github master, as the wordpress.org/plugins/wc-vendors/ is still v1.8.9 until we add some more to v1.9.0 for release.
