### ISSUE TITLE
WooCommerce Shipment Tracking Bug

### ISSUE THREAD

**Issue by GoTeamScotch** [wcvendors/wcvendors#199]
If the plugin "WooCommerce Shipment Tracking" (v1.2.7) is installed, the vendor dashboard breaks. This seems to be the result of the plugin no longer providing the method "get_providers()" but instead offers the same information in the form of a public property. This appears in two places I've found so far:
- wc-vendors\classes\front\orders\class-orders.php on line 137
- wc-vendors\classes\front\dashboard\class-vendor-dashboard.php on line 199

Change this:
```
$providers = $WC_Shipment_Tracking->get_providers();
```
To this:
```
$providers = $WC_Shipment_Tracking->providers;
```
Or if you want to maintain backwards compatibility for older version of the Shipment Tracking plugin:
```
$providers  = (method_exists($WC_Shipment_Tracking, 'get_providers')) ? $WC_Shipment_Tracking->get_providers() : $WC_Shipment_Tracking->providers;
```
Edit: See my pull request: https://github.com/wcvendors/wcvendors/pull/201

**Comment by digitalchild** [comment]
Your updates have been added thanks !
