### ISSUE TITLE
Vendor Dash > Orders: Deprecated Function

### ISSUE THREAD

**Issue by GoTeamScotch** [wcvendors/wcvendors#200]
As of WooCommerce 2.4, the file wc-vendors\templates\orders\table-body.php is generating a deprecated function warning on line 2...
```
$item_meta = new WC_Order_Item_Meta( $item['item_meta'] );
```
Should be
```
$item_meta = new WC_Order_Item_Meta( $item );
```
WC_Order_Item_Meta is defined in woocommerce\includes\class-wc-order-item-meta.php. Its constructor contains:
```
public function __construct( $item = array(), $product = null ) {
	// Backwards (pre 2.4) compat
	if ( ! isset( $item['item_meta'] ) ) {
		$this->legacy = true;
		$this->meta   = array_filter( (array) $item );
	return;
	}
	
	$this->item    = $item;
	$this->meta    = array_filter( (array) $item['item_meta'] );
	$this->product = $product;
}
```
Also found on wc-vendors\templates\dashboard\orders.php on line 84. Same fix applicable.

Edit: See my pull request: https://github.com/wcvendors/wcvendors/pull/201

**Comment by GoTeamScotch** [comment]
Also found on wc-vendors\templates\dashboard\orders.php on line 84. Same fix applicable.

**Comment by digitalchild** [comment]
This updated has been added thanks.
