### ISSUE TITLE
Multiple Users - One Vendor

### ISSUE THREAD

**Issue by GoTeamScotch** [wcvendors/wcvendors#202]
I have found a need in my setup that I wanted to discuss and find out if I'm a fringe use case or if there might be viability in making these adjustments.

Basically, the product's author is used to tie it to a vendor. This presents a problem if you have more than one person publishing products under the same vendor. Perhaps one person creates products, manages prices, and checks reports while another person fulfills orders and marks them as shipped.

Is using a custom taxonomy an option? From there, WordPress taxonomy related functions are available. You could determine if a product is in a particular vendors' store using has_term() for example.

Taking workload out of the picture, would this sort of feature be beneficial?

Personally, I used to use the plugin "Vendor Stores" which did use a custom taxonomy to link products to vendors and it worked well. It wasn't as feature rich or well written as WC Vendors but that much worked. From what I remember I think they simply used a taxonomy for the store name, slug, and description and then a serialized array of other vendor options stored in the wp_options table.

I realize that currently much of WC Vendors' codebase references the post's author and uses that as the vendor. I realize it's easier said than done with lots of code relying on the way it currently is designed. My question is basically how crazy of an idea is it to switch to an alternative to using the post's author as a vendor designation?

**Comment by digitalchild** [comment]
Can I ask things like this are posted to our forums as the majority of our users aren't savvy enough to use github. It will create a great discussion that heaps more people can get their eyes over. 

I'll be moving this over to our forums, but my first reply is below :) 

---

Using custom taxonomies has its own problems and there are other multi vendor products that have used this method and it all comes crashing down pretty quickly. 

We will continue to use the post author for products however we have had a few people wanting different variations of what you're asking including 

1) One product, many users 
2) One store, many users (i think this is your use case) 
3) One user, many stores
4) many users, many stores 

These all require different configurations and capabilities, and lots of other things oh and heaps of programming. I have taken the first steps towards supporting, 2, 3 and 4 in pro but will be a while before this is all realised. 1) is an interesting case as it requires varied pricing and meta data depending on who the user is, the store and other attributes. After first release of pro I'll be focusing a lot of energy on getting custom capabilities working to give our users much better control over who has access to what.

**Comment by GoTeamScotch** [comment]
Yeah, absolutely. Let's get a discussion going. :+1:
