### ISSUE TITLE
Critical: Mark Shipped button magically disappears

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#209]
1.) Purchase a tangible item on dev.  Such as the Flying Ninja T-Shirt.

2.) Check vendor dashboard, no Mark Shipped button.

Oddly, the Mark Shipped button does show up on some older orders, but not on new orders.

**Comment by digitalchild** [comment]
I can't seem to replicate this in my environment

**Comment by bentasm1** [comment]
https://www.wcvendors.com/help/topic/front-end-dashboard-orders-issues/
https://www.wcvendors.com/help/topic/mark-shipped-not-appearing-on-vendor-dashboard/
https://www.wcvendors.com/help/topic/mark-as-shipped-not-working/

**Comment by digitalchild** [comment]
This was added in december
