### ISSUE TITLE
When browsing a category, the title does not display

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#213]
On dev, deactivate free & pro.  View any product category.  You will see the category as the page title at the top.  Activate Free, category goes away.  Activate Pro, no difference.

https://www.wcvendors.com/help/topic/shop-titles-gone-with-wc-plugin/

**Comment by stodorovic** [comment]
I've similar issue. I found bug in "filter" remove_vendor_title():

File wc-vendors/classes/front/class-vendor-shop.php:

// Remove Page Title if on Vendor Shop 
add_filter ( 'woocommerce_show_page_title', array('WCV_Vendor_Shop', 'remove_vendor_title') );

/* 
* Remove the Page title from Archive-Product while on a vendor Page
*/ 
public static function remove_vendor_title() {
        if ( WCV_Vendors::is_vendor_page() ) { 
                return false; 
        }
}

this function doesn't return valid value if it isn't vendor page. Correct function is:

public static function remove_vendor_title( $b ) { 
        if ( WCV_Vendors::is_vendor_page() ) { 
                return false; 
        }
        return $b;
}

**Comment by digitalchild** [comment]
Thanks @stodorovic I'll add this to our next release !
