### ISSUE TITLE
Action should be filter: woocommerce_email_classes

### ISSUE THREAD

**Issue by ontiuk** [wcvendors/wcvendors#215]
In file classes/admin/class-emails.php
	`add_action( 'woocommerce_email_classes', array( $this, 'check_items' ) );`
Should be:
        `add_filter( 'woocommerce_email_classes', array( $this, 'check_items' ) );`

Called in woocommerce: includes/class-wc-emails.php:   
	`$this->emails = apply_filters( 'woocommerce_email_classes', $this->emails );`

Filters additional values not used afaik otherwise would have been noticed earlier. Only noticed as I needed the notify_vendor one.

**Comment by bentasm1** [comment]
Call me crazy, but the two lines look identical to me in your post.

**Comment by digitalchild** [comment]
Nice catch, I've updated the code.
