### ISSUE TITLE
add woocommerce_completed_statuses filter to notify-vendor email class. Extra payment statuses.

### ISSUE THREAD

**Issue by ontiuk** [wcvendors/wcvendors#216]
Hi Ben

Further to issue:214 I'd like to log a small additional enhancement to allow for integration with other plugins that have other completed statuses. In this case woocommerce deposits which uses the partial-payment action status, and wp-partial-payment order status.

This would be added to class-wc-notify-vendor.php in the construct above the email triggers @line37.

```
$completed_statuses = apply_filters( 'wcvendors_completed_statuses', array( 'completed', 'processing' ) );
```
The email triggers could then be dynamically created based on completed statuses
```
// Triggers for this email
add_action( 'woocommerce_order_status_pending_to_processing_notification', array( $this, 'trigger' ) );
add_action( 'woocommerce_order_status_pending_to_completed_notification', array( $this, 'trigger' ) );
add_action( 'woocommerce_order_status_failed_to_processing_notification', array( $this, 'trigger' ) );
add_action( 'woocommerce_order_status_failed_to_completed_notification', array( $this, 'trigger' ) );
```
Replace with:
```
foreach ( $completed_statuses as $status ) {
// Triggers for this email
add_action( 'woocommerce_order_status_pending_to_{$status}_notification', array( $this, 'trigger' ) );
add_action( 'woocommerce_order_status_failed_to_{$status}_notification', array( $this, 'trigger' ) );
}
```
These are then added to woocommerce triggers via the 'woocommerce_email_actions' filter. At the moment I've had to hardcode the partial-payment trigger into the class. Not good for updates.

Not quite got round to mastering the fork and pull mechanisms yet so logging it this way.

**Comment by digitalchild** [comment]
Thanks for this, I'll work on having your suggestion integrated into the plugin tomorrow. I'll be completing issue #214 also.

**Comment by bentasm1** [comment]
Better late than never.  Commit complete.
