### ISSUE TITLE
Shipping Clarification for Free

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#217]
https://github.com/wcvendors/wcvendors/blob/a6556e16a1434c79d0d3524f33e17b05c0ce7923/classes/admin/settings/sf-options.php#L47

Old Text: Give vendors any shipping collected per-product

New Text:  "Give vendors any shipping collected through WooThemes Per Product Shipping for WCV Free, or through the shipping module <name> in WC Vendors Pro"

**Comment by bentasm1** [comment]
And probably a href the "shipping module in WC Vendors Pro" to the KB article yet to be written that shows how to use it.

**Comment by digitalchild** [comment]
too long, didn't read

**Comment by bentasm1** [comment]
Fixed months ago.
