### ISSUE TITLE
More filter woes: wcv_product_commission_tab 

### ISSUE THREAD

**Issue by ontiuk** [wcvendors/wcvendors#218]
Hi

More hook trigger issues: wcv_product_commission_tab (filter)

Trying to get this to fire, but it's not working. Problem is that whatever I try to do to get the filter added it's always done after the filter is applied.

Root of the problem may be that you're using plugins_loaded to load all of the plugins dependencies and core files. Wrapped in a few class constructors are apply_filter calls that are automatically called then, and as plugins_loaded is called before any theme hooks then they'll never be added to the stack before the plugins_loaded action is fired.

Not particularly good practice to do this. I know a lot of developers to, myself included, but these tend to be post install tidy-up requirements and not core file install.

Might be a need to revisit how initiation is done? Or at least for any filters/actions applied in constructs wrap them in action calls for later in the stack such as init / admin_init, so any theme functions.php actions / filter calls can be loaded.

Thanks

**Comment by digitalchild** [comment]
It's actually bad practice to be using init or admin_init unless you have to. plugins_loaded is the recommended way to initialise the subclasses of a plugin. I have discussed this with several plugin developers and a couple of core developers and the recommended this way. There is also large sections of this plugin that I didn't write but inherited so if you have a better way to do something I'm all ears. 

What are you trying to achieve with this filter?

**Comment by ontiuk** [comment]
Agreed, init & admin_init are very bad practices for the actual loading of plugin files. These imo - and from trawling through countless plugins & tutorials, as well as developing my own - over the last 10+yrs - and I remember WP when it was b2 and they were ripping off ez_sql - should be loaded as simple includes/requires. Similarly any instantiated subclasses classes should be available in the global namespace to allow for remove_* access.

I was referring more to the actual filters / actions that are applied inside constructs being wrapped in init or admin_init calls so they're stacked to be called later. Recommendation is that filters / actions applied via theme functions should be called via after_setup_theme, init / admin_init / wp_loaded / wp / widget init, and in some cases plugins_loaded, but in general further down the call stack.

By having filters /actions that are applied in __constructs of classes instantiated on loading especially when linked to an early calls such as plugins_loaded  they're essentially tied to that action as much as if you'd just written:

```
add_action( 'plugins_loaded', 'function_name' );
function function_name () [
apply_filter( 'filter_name', val );
} 

It's why things line register_post_type functions are wrapped in init calls when the actual register_post_type hook is called early. Means that anything amending them can be stacked before.

Have to agree to disagree in the plugins_loaded for loading subclasses. There's strict caveats to that in that they shouldn't be doing any processing that is plugabble later on. Then again that's the same case for just loading them as includes.

This as with the other issue all I'm trying to do is to be able to add the 'partial-payment' payment status to the list of 'completed' statuses for woocommerce. 

The enhancement to include the filter for notification emails works fine because it's called quite late and so any theme add_filter() calls are stacked before and are applied.

Hope that helps.

**Comment by digitalchild** [comment]
Have you got some sample code I can use for testing to see if I can resolve this?

**Comment by bentasm1** [comment]
Abandoned by the original poster, closing.
