### ISSUE TITLE
Pagination on Home Page for Custom Loops

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#219]
https://wordpress.org/support/topic/plugin-breaks-pagination-on-home-page-for-custom-loops

"First of all, I found that problem is gone if I delete stroke

$options = get_option( $this->id . '_options' );

in classes/admin/settings/classes/sf-class-settings.php

So, I thought that the problem is in one of plugin options. Of course, first of possible option was permalink for shop page, because you use some add_rewrite_rule based on this settings. But when I disabled all things that connected to this option - nothing was changed. Then, I continued test and disabled one by one different settings.

And found one stroke. If I disable it - pagination works.

It's in classes/front/orders/class-orders.php

When I disabled function public function display_shortcodes() - everything works

Even if I disabled stroke

is_page( WC_Vendors::$pv_options->get_option( 'orders_page' ) ) &&

pagination works. So, can you help me to understand what is the problem? Maybe plugin think that home page is order page? But in settings I have correct page as order page."

**Comment by digitalchild** [comment]
I don't understand what a stroke is?

**Comment by bentasm1** [comment]
Hell if I know.

**Comment by MattyLB** [comment]
@wpsoul - are you referring to the entire line of code when you say "stroke"
?

**Comment by wpsoul** [comment]
Hi, guys. I think I found fix. This was conflict with canonical redirect of wordpress.

https://wpsoul.com/pagination-fix-for-wordpress-4-4-1/

I checked this fix on wp 4.4.1 and latest versions of WC Vendors and Woocommerce and looks like it works

**Comment by bentasm1** [comment]
Sounds good.  Thanks for the tip!  Closing the issue now......
