### ISSUE TITLE
Phase out session_start

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#220]
...to make Varnish happy.  Probably for Pro, too.

**Comment by stodorovic** [comment]
I've same issue. In main __construct(), I found line:

if ( !session_id() ) session_start();

It creates session for each page.

I've created patch for it. From my point of view, right place for session_start is "action template_redirect". I moved previous line to function check_access (classes/front/dashboard/class-vendor-dashboard.php). I added code to start session only if user is authenticated.

I'm new here. I can pull my patch if it's OK.

**Comment by digitalchild** [comment]
Hi @stodorovic Can you confirm that this fixes the issue with Varnish? I'd be happy to take the pull request if it fixes the issue and can be confirmed working with varnish configs. I don't have a host with varnish setup on it at the moment.

**Comment by stodorovic** [comment]
I created pull request. As I said in comment it works on my test server. php session will be started only if user is logged. Only problem is when display_errors=on in php.ini, if some error, warning is printed on the page (before executing action template_redirect), php can't start session. In this case, you will see this warning :

Warning: session_start(): Cannot send session cookie - headers already sent by ...
But most servers are logging warnings, errors to log file instead showing them. 

I was thinking about option in admin dashboard which control location of session_start. I don't know is it needed or no. It's just an idea.

Also, I didn't test everything (all options from vendor dashboard, etc...). I was assuming that session is only needed for vendor dashboard and reports.
If you confirm that everything works as should, I'll test again varnish/CDN.

Thank you

**Comment by digitalchild** [comment]
Pull request merged that fixes this.
