### ISSUE TITLE
New filter: product_controller & product types - Pro

### ISSUE THREAD

**Issue by ontiuk** [wcvendors/wcvendors#226]
Hi

I'd like a new filter added to the class-wcvendors-pro-product-controller. It would also be pretty useful when you come to implementing the bookings integration 

`
public function save_meta( $post_id ) { 
...
if ( in_array( $product_type, array( 'variable', 'grouped' ) ) ) {
...
`
Could do with a filter for the product types so the user can set additional product types such as booking.

`
public function save_meta( $post_id ) { 
...
if ( in_array( $product_type, apply_filters( 'wcv_product_save_meta_types', array( 'variable', 'grouped' ) ) ) ) {
...
`
Adding the booking type means easier setting of non-used price values.

Thanks

**Comment by digitalchild** [comment]
This has been added as the following filter : wcv_product_meta_types
