### ISSUE TITLE
Custom product meta save

### ISSUE THREAD

**Issue by ontiuk** [wcvendors/wcvendors#227]
PRO version

In 1.1.0 you've created a section in the save_meta function of the product controller to iterate through any _wcv_custom_product_*variables and save them. Unfortunately the update_post_meta() call uses store_id instead of post_id.

There’s an argument that custom meta data isn’t standard and should be dealt with on an ad hoc basis not with a straight no-validation update/insert. 

As well as the fix to the variable name I would also request/recommend that the key capture applies a filter to let the user bypass it, so:

```
// To be used to allow custom meta keys 
$wcv_custom_metas = array_intersect_key( $_POST, array_flip(preg_grep('/^_wcv_custom_product/', array_keys( $_POST ) ) ) );

if ( !empty( $wcv_custom_metas ) ) { 
foreach ( $wcv_custom_metas as $key => $value ) {
	update_post_meta( $store_id, $key, 	$value ); 	
}
}
```
to:
```
// To be used to allow custom meta keys 
$wcv_custom_metas = apply_filters( 'wcv_custom_product_meta', array_intersect_key( $_POST, array_flip(preg_grep('/^_wcv_custom_product/', array_keys( $_POST ) ) ) ) );

if ( !empty( $wcv_custom_metas ) ) { 

foreach ( $wcv_custom_metas as $key => $value ) {
	update_post_meta( $post_id, $key, 	$value ); 	
}
}
```

**Comment by digitalchild** [comment]
This has been fixed, thanks.
