### ISSUE TITLE
Pro: Form Helper allow for multiple select atributes

### ISSUE THREAD

**Issue by ontiuk** [wcvendors/wcvendors#229]
Delving through the code there some reference to allowing for multiple attributes via select2 styled selects. At present the form helper selects don't allow this and adding multiple to the custom_attributes argument to the form helper selects styles as a multiple select but only processes the first option.

Some code changes to the for helper selects to allow for arrays can get round this:

~231
`
foreach ( $field['options'] as $key => $value ) {
	echo '<option value="' . esc_attr( $key ) . '" ' . selected( esc_attr( $field['value'] ), esc_attr( $key ), false ) . '>' . esc_html( $value ) . '</option>';
}
`
to
`
foreach ( $field['options'] as $key => $value ) {
        $selected = ( is_array( $field['value'] ) ) ? ( in_array( esc_attr( $key ), $field['value'] ) ) ? 'selected="selected"' : '' :  selected( esc_attr( $field['value'] ), esc_attr( $key ), false );
	echo '<option value="' . esc_attr( $key ) . '" ' . $selected . '>' . esc_html( $value ) . '</option>';
}
`
~354
`
foreach ( $field[ 'options' ] as $key => $value ) {
	echo '<option value="' . esc_attr( $key ) . '" ' . selected( esc_attr( $field['value'] ), esc_attr( $key ), false ) . '>' . esc_html( $value ) . '</option>';
}
`
to
`
foreach ( $field[ 'options' ] as $key => $value ) {
        $selected = ( is_array( $field['value'] ) ) ? ( in_array( esc_attr( $key ), $field['value'] ) ) ? 'selected="selected"' : '' :  selected( esc_attr( $field['value'] ), esc_attr( $key ), false );
	echo '<option value="' . esc_attr( $key ) . '" ' . $selected . '>' . esc_html( $value ) . '</option>';
}
`
~424
`
foreach ( $option as $key => $value ) {
	echo '<option value="' . esc_attr( $key ) . '" ' . selected( esc_attr( $field[ 'value' ] ), esc_attr( $key ), false ) . '>' . esc_html( $value ) . '</option>';
} 
`
to
`
foreach ( $options as $key => $value ) {
        $selected = ( is_array( $field['value'] ) ) ? ( in_array( esc_attr( $key ), $field['value'] ) ) ? 'selected="selected"' : '' :  selected( esc_attr( $field['value'] ), esc_attr( $key ), false );
	echo '<option value="' . esc_attr( $key ) . '" ' . $selected . '>' . esc_html( $value ) . '</option>';
}
`

Thanks

**Comment by bentasm1** [comment]
Hi @ontiuk -- I'm adding you to the Pro private repo right now so you can make contributions without having to use the Free repo.  Thanks!

Ben
