### ISSUE TITLE
Create Button to Reset Vendor Roles

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#230]
This will save us a few support tickets a week. Admins love installing User Role Editor and screwing things up.  A simple "Reset Vendor and Pending Vendor" button would do the trick.

**Comment by MattyLB** [comment]
That's a great fallback, however you might want to throw a
conflicting/potential security risk error on the admin screen when certain
roles are added to vendors, or link a disclaimer to FAQs about the do's and
don'ts of modifying vendor role capabilities.

Both ways will prevent support tickets and foul-ups from paying admins who
are trying to accomplish something that must not be available out of the
box for their vendors. Just a thought.

**Comment by digitalchild** [comment]
I agree @MattyLB we can't help people that shoot themselves in the foot easily :)

**Comment by bentasm1** [comment]
Of course, it's just like WooThemes Tools.  You can clear all transients, but the warning says it will indeed reset all cart data including live carts.  We'll have warnings under the button, but hey, can't fix stupid all of the time.  We need a better arsenal of these things, especially more buttons like "Re-create all WC Vendors Pages and assign if they are missing" because I cant count the number of times I login to a site to find pages not set (at all) and admins wondering why the dashboard or orders page don't work.

**Comment by MattyLB** [comment]
Good points!
