### ISSUE TITLE
Fix orders screen for vendors in admin

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#231]
Notice: get_formatted_legacy is deprecated since version 2.4! Use Item Meta Data is being called with legacy arguments instead. in /Users/jamie/Sites/wcv-2015-10-03/wp-includes/functions.php on line 3406

Notice: Undefined offset: 0 in /Development/wcvendors/classes/admin/class-vendor-admin-dashboard.php on line 456

Notice: Trying to get property of non-object in /Development/wcvendors/classes/admin/class-vendor-admin-dashboard.php on line 456

Notice: get_formatted_legacy is deprecated since version 2.4! Use Item Meta Data is being called with legacy arguments instead. in /Users/jamie/Sites/wcv-2015-10-03/wp-includes/functions.php on line 3406

Notice: Undefined offset: 0 in /Development/wcvendors/classes/admin/class-vendor-admin-dashboard.php on line 456

Notice: Trying to get property of non-object in /Development/wcvendors/classes/admin/class-vendor-admin-dashboard.php on line 456

Notice: get_formatted_legacy is deprecated since version 2.4! Use Item Meta Data is being called with legacy arguments instead. in /Users/jamie/Sites/wcv-2015-10-03/wp-includes/functions.php on line 3406

Notice: Undefined offset: 0 in /Development/wcvendors/classes/admin/class-vendor-admin-dashboard.php on line 456

Notice: Trying to get property of non-object in /Development/wcvendors/classes/admin/class-vendor-admin-dashboard.php on line 456

Notice: get_formatted_legacy is deprecated since version 2.4! Use Item Meta Data is being called with legacy arguments instead. in /Users/jamie/Sites/wcv-2015-10-03/wp-includes/functions.php on line 3406

Notice: Undefined offset: 0 in /Development/wcvendors/classes/admin/class-vendor-admin-dashboard.php on line 456

Notice: Trying to get property of non-object in /Development/wcvendors/classes/admin/class-vendor-admin-dashboard.php on line 456

Notice: get_formatted_legacy is deprecated since version 2.4! Use Item Meta Data is being called with legacy arguments instead. in /Users/jamie/Sites/wcv-2015-10-03/wp-includes/functions.php on line 3406

Notice: Undefined offset: 0 in /Development/wcvendors/classes/admin/class-vendor-admin-dashboard.php on line 456

Notice: Trying to get property of non-object in /Development/wcvendors/classes/admin/class-vendor-admin-dashboard.php on line 456

Notice: get_formatted_legacy is deprecated since version 2.4! Use Item Meta Data is being called with legacy arguments instead. in /Users/jamie/Sites/wcv-2015-10-03/wp-includes/functions.php on line 3406

Notice: get_formatted_legacy is deprecated since version 2.4! Use Item Meta Data is being called with legacy arguments instead. in /Users/jamie/Sites/wcv-2015-10-03/wp-includes/functions.php on line 3406

Notice: Undefined offset: 0 in /Development/wcvendors/classes/admin/class-vendor-admin-dashboard.php on line 456

Notice: Trying to get property of non-object in /Development/wcvendors/classes/admin/class-vendor-admin-dashboard.php on line 456

**Comment by MattyLB** [comment]
Hi Jamie,
I'm a newb at PHP but I was looking into the line 456 (undefined offset: 0) issue and found this. Hope it helps and I'm sorry if I'm pointing out the obvious - just trying to help! ;) ...

source: [stackoverflow: how to avoid php notice undefined offset 0](http://stackoverflow.com/questions/7688814/how-to-avoid-php-notice-undefined-offset-0-without-checking-each-field-of-arr)

>- i think isset is the way you should go – Dukeatcoding Jan 30 '13 at 15:50
>- I agree that @ should be used as little as absolutely possible. However, I have a valid example of why I'd want exactly that: I have a TypeValidation class with a function that checks a variable's type and content, combining several of the isset(), empty(), is_int(), etc. standard functions. Haviing this wrapped in my own reusable function instead of typing it out every time is immensely time-saving. But each call with an undefined value (which my function will handle just fine) returns a notice error which is completely useless in my situation. Now do that 100x in a loop.... – Bison Jun 1 at 14:06

**Most up-voted answer was**: [this solution provided by Neal](http://stackoverflow.com/a/7688840)
>You can do an isset():

    if(isset($array[0])){
        echo $array[0];
    }
    else {
      //some error?
    }
>Or if you know that you are only going to be checking index 0:

    $array = $array + array(null);
>So if the original $array[0] was unset, now it is null

**Comment by bentasm1** [comment]
Matty, what's this got to do with this issue #231?

**Comment by MattyLB** [comment]
I might have replied to wrong open issue. I'll fix it shortly, sorry

**Comment by MattyLB** [comment]
@bentasm1 - was sifting through the open issues and hoped I could help with at least part of the #231 bug. My comments only pertain to the: *Notice: Undefined offset: 0 in /Development/wcvendors/classes/admin/class-vendor-admin-dashboard.php on line 456* part.

No harm meant - just trying to figure out PHP myself and I learn better with live examples. Let me know if I should step back. ;)

**Comment by bentasm1** [comment]
Hell no, step forward. :)  This is open source, we strongly encourage the community and everyone to help!  More work you do the less I have to do! :) :)
