### ISSUE TITLE
Manually Creating Order gets Commissions Wrong

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#232]
1.) wp-admin > WooCommerce > Orders > Add New

2.) Select a customer or create one.

3.) Add Line Items and add a few vendor products.

4.) Discount those products prices to $0

5.) Complete the order

When you do this, the commissions show as due for the full purchase price, rather than $0 since the product actually sold for $0.

This would be a strange use case, as very few sites (if any) ever do free orders this way through the wp-admin, I just happened to find it when creating an order for a vendor who needed to recover some downloadable products after her hard drive crashed.

**Comment by digitalchild** [comment]
What was the order set to processing or completed?

**Comment by bentasm1** [comment]
Tried both, actually.  First order was set to processing, and then completed.  Second order was set directly to completed.  Same results.

**Comment by digitalchild** [comment]
Just tested this and it sets the commission to $0 and it's set to paid.
