### ISSUE TITLE
Feature product with pro template

### ISSUE THREAD

**Issue by archonic** [wcvendors/wcvendors#241]
There's a checkbox to control showing/hiding feature product (WooCommerce > WC Vendors > Products) for vendors but there's no featured checkbox element present on product-edit.php. Not sure if `$wcv_featured_enabled` is the right check but this is most of the way there.

	/**
	 *  Output product featured
	 * 
	 * @since    1.1.5
	 * @param 	 int 	$post_id  post_id for this meta if any 
	 */
	public static function featured( $post_id ) {
		if ( $wcv_featured_enabled ) {
			WCVendors_Pro_Form_Helper::input( apply_filters( 'wcv_product_featured', array( 
				'post_id'		=> $post_id,
				'type'			=> 'checkbox',
				'label'			=> __( 'Featured', 'wcvendors-pro' ), 
				'id' 			=> '_featured',
				'value'			=> esc_attr( get_post_meta( $post_id, '_featured', true ) )
				) )
			);
			do_action( 'woocommerce_product_options_featured' );
		}
	} // featured()

**Comment by digitalchild** [comment]
I didn't include it in the template because no one uses it, cause that's how vendors spam the featured products area of a site.

**Comment by archonic** [comment]
I guess that makes sense. The above code should help folk who want the featured checkbox on the pro dashboard (when it doesn't have the `$wcv_featured_enabled ` condition). It would also make sense to include if [pay-to-feature](https://www.wcvendors.com/help/topic/pay-to-feature/) is implemented.

**Comment by bentasm1** [comment]
Not Free.
