### ISSUE TITLE
Pro templates: unmatched divs

### ISSUE THREAD

**Issue by archonic** [wcvendors/wcvendors#242]
When editing `product-edit.php`, I noticed the start wrapper and end wrapper in price and sale price make it easy to screw up a layout. Form helpers shouldn't rely on each other for start and end tags - any given function should end all it's start tags. To see what I mean, trying commenting out / removing sale price. The inventory and other tabs break because the row isn't finished by `sale_price`.

I'm pretty certain there's a missing end div in the layout of the pro dashboard as well. I have to put an end div at the end of `product-edit.php` to fix that layout from trying to eat my footer. It's the only wcv template I'm editing.

Update: The seller dashboard (pro) also has an unmatched div and I'm not overriding it. Looks like a layout problem.

**Comment by archonic** [comment]
Mentioned on the forums but not here: You can remove unwanted form inputs from product-edit.php and the product controller is fine with it. I believe the only required item is the title. However the products controller in WCV freaks out if it doesn't have sale price. It would be nice to be able to remove that input.

**Comment by digitalchild** [comment]
You're right, I'll replace Price and Sale price with a single output that will then use the correct wrapping. As of 1.1.5 you can just disable most fields via the new options tab. I'll look into the missing divs but you're the first to report the issue out of the few hundred people we have using it.

**Comment by archonic** [comment]
:+1: for price and sale. For the divs, I tried viewing source on the pro demo pro dashboard and comparing the find results for "<div" and "</div". There's 154 starts and 154 ends, so that's on my side. My bad!

**Comment by digitalchild** [comment]
I've changed how price is output in the next release to be prices() instead of price/sale_price this has fixed the div issues.
