### ISSUE TITLE
Unable to remove actions

### ISSUE THREAD

**Issue by zarcode** [wcvendors/wcvendors#244]
Not sure is it possible to remove this action:
``` 
add_action( 'woocommerce_before_single_product', array('WCV_Vendor_Shop', 'vendor_mini_header'));
```
since there is no handle to WCV_Vendor_Shop object

**Comment by zarcode** [comment]
From another plugin

**Comment by bentasm1** [comment]
remove_action( 'woocommerce_before_single_product', array('WCV_Vendor_Shop', 'vendor_mini_header'));

Of course, you can do it the really easy way, but just disabling "Vendor Shop Headers" in the WooCommerce > WC Vendors > General tab.

**Comment by zarcode** [comment]
Works from theme, but not from plugin.

**Comment by zarcode** [comment]
this works from plugin
```
	add_action('init', array( $this, 'test' ) );

		public function test () {
			remove_action('woocommerce_before_single_product', array('WCV_Vendor_Shop', 'vendor_mini_header'));
		}
```

**Comment by zarcode** [comment]
thanks
