### ISSUE TITLE
Hook into wp-login.php for Apply to become a vendor

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#245]
Is there a reason we don't do this now?  I know we havent really touched the registration hooks since this is the way it was done in PV before.  But I guess the question comes in, why not also hook into wp-login.php?action=register (or whatever the URI is)?

**Comment by digitalchild** [comment]
We can do that, not sure why we don't

**Comment by digitalchild** [comment]
Need to work out how to validate the form correctly during registration
