### ISSUE TITLE
Local Delivery doesn't log commission

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#249]
Local delivery doesn't log commissions at all.

**Comment by archonic** [comment]
Hate to be "that guy" but is there an ETA on this?

**Comment by bentasm1** [comment]
Hate to be "that guy" that says "when its done". ;)

**Comment by archonic** [comment]
It's stupid but this bug is holding back a client from paying a rather large invoice. If no one has taken a look yet, I can submit the PR but I bet you guys would be more efficient since you're more familiar.

Could this issue also screw up mailing the vendor a product sold notification?

**Comment by bentasm1** [comment]
Pull Requests is what GitHub was meant for.  Do it! :-)

**Comment by archonic** [comment]
Are there automated tests? Doesn't seem to be.

**Comment by bentasm1** [comment]
Feel free to submit a PR with automated tests, too. :)

**Comment by archonic** [comment]
Hah, sigh. I miss Rails. But not really, cause I work with it every day. I'm inclined to work on paying things first and this issue isn't one of them. I may take a look later and will let you know if I do.

**Comment by archonic** [comment]
My client said her vendors have sometimes not been getting product sold emails. In my sandbox, I can confirm that local pickup orders aren't sending an email to the vendor. That is a MAJOR problem - without that there is no indication that the product was sold at all, and buyer is left hanging. Most sellers entered "disable national shipping" and "disable international shipping", meaning local pick up is the only way to buy that item - I can't just disable that shipping option. In case it's not obvious by now, I really need this fixed.

Is no one else running local pickup shipping? I feel like this should be a problem for more people than just myself.

**Comment by IdeaZone** [comment]
Is this issue being looked at? It is causing huge issues on a launched site and is holding us back from from using the plugin on two additional projects.

**Comment by bentasm1** [comment]
Yup, @digitalchild will be on it like white on rice pretty shortly here.

**Comment by IdeaZone** [comment]
As much as I appreciate the response an actual timeline would be great so that I can pass the information along to my client. I am not entirely sure that "white on rice" will cut it out here in the real world.

**Comment by bentasm1** [comment]
@IdeaZone You're right, my apologies by trying to add some humor to things.  I'm a terrible person for being funny.  ;)

Jamie is refreshing WC Vendors Free this week, and this will be part of the updates he makes when we push the next version.  If you need it done faster, perhaps a donation of some rice would work. ;)

**Comment by IdeaZone** [comment]
If it gets done faster I can promise a donation of more than just rice ;)

**Comment by IdeaZone** [comment]
Do we have any idea when this might be fixed yet?

**Comment by digitalchild** [comment]
This appears to be fixed all by itself in WooCommerce 2.6. No fix required.

**Comment by archonic** [comment]
Well there ya go. Thanks for the update.
