### ISSUE TITLE
Fatal Erro when updating Free

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#252]
Fatal error: Class 'WC_Vendors' not found in /home3/wcvendors/public_html/dev/wp-content/plugins/wcvendors-pro/includes/class-wcvendors-pro-ratings-controller.php on line 797

...when updating through the plugin auto updater for Free.

**Comment by bentasm1** [comment]
Rename the pro plugin folder.  Then reload wp-admin go get WP admin to work again.  Pro is then disabled.  Rename Pro back to original folder name.  Activate Pro on the plugins page:

`WC Vendors Pro requires WC Vendors to run. Please install WC Vendors and activate before attempting to activate again.`

**Comment by bentasm1** [comment]
Closed!  Ben is an idiot.

**Comment by bikramaditya** [comment]
I followed these steps. I also followed all other tricks in google. It didnt help

**Comment by bentasm1** [comment]
Eeeh, bikramaditya, this is from like 11 months ago.  This isnt a forum for technical support.  If you need help, wcvendors.com/help/
