### ISSUE TITLE
Notify Vendors Email Fatal Error

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#257]
1.) Choose an order from wp-admin

2.) Choose "Order Actions - Notify Vendors" and click the circle to send the vendor notification email.

3.) Result:  The email shows up in the browser (?), is not sent, and contains a PHP fatal error.

![capture](https://cloud.githubusercontent.com/assets/6693745/12853506/6bd2eb0c-cc02-11e5-8981-cb55f3e52576.PNG)

**Comment by digitalchild** [comment]
This has been fixed
