### ISSUE TITLE
Enforce Vendor Display Name

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#258]
When Vendor Display Name is set to anything other than the Shop Name, the Shop Name is still used around the site in various places.  We should enforce the same name to show throughout the site for consistency:

1.) Commission log
2.) Emails
3.) Order meta under "Vendors Shipped"
4.) Reports
5.) Vendor URL (e.g., /vendors/user_login/ or /vendors/shop_name/ etc....)

**Comment by bentasm1** [comment]
https://www.wcvendors.com/help/topic/vendor-url-as-display-name/

**Comment by digitalchild** [comment]
We can't use the display name cause they can change that whenever they want which would lead to inconsistent commission calculations. It has to be stored as user_id and then bubble up to whatever the display option is. There isn't really much we can do here in the current code form.
