### ISSUE TITLE
WC Vendor shows fatal error if Woo Commerce is deactivated

### ISSUE THREAD

**Issue by ankitguptaindia** [wcvendors/wcvendors#259]
If WC Vendor is activated and if we deactivated woo commerce then site shows fatal error, unable to access site dashboard. 
Plugin should have conditional logic, it should show a validation check and ask for plugin activation message.

**Comment by digitalchild** [comment]
Are you able to give me a log entry so I can see where this is erroring out? I've just tested this on a few installs and have been unable to replicate it deactivating woocommerce.

**Comment by digitalchild** [comment]
Can't replicate this so i'm closing it.
