### ISSUE TITLE
BuddyPress Notices Fix

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#264]
https://www.wcvendors.com/help/topic/buddypress-compatibility/

Warning:  Have not tested this fix.  You know about init/plugins_loaded better than I.

------

My issue is that when I activate both Buddypress 2.5.1 plugin and WC Vendor Version 1.8.7 plugin on WordPress 4.4.2, I get this notice.
Notice: bp_setup_current_user was called incorrectly. The current user is being initialized without using $wp->init(). Please see Debugging in WordPress for more information. (This message was added in version 1.7.) in dummydomain.com/wp-includes/functions.php on line 3792

------

I think I have found the solution.
Please take a quick look at this >> http://webdesign.anmari.com/2853/call-current_user_can-after-init/

Buddypress displays that notice to make sure that every current_user_can() and wp_set_current_user() are called after the init action.

In class-wc-vendors.php, I change line 92 from add_action( ‘plugins_loaded’, array( $this, ‘include_core’ ) ); to add_action( ‘init’, array( $this, ‘include_core’ ) ); then the notice is gone.
Could you please fix this for the future release ?

I hope that it is the right solution because I haven’t dug into the code that much.

**Comment by digitalchild** [comment]
Ive made this change and will work with this for a bit and see if it has any adverse effects on the operation of our plugins.

**Comment by digitalchild** [comment]
Changing this to init will break pretty much all of wcvendors free. We have to wait for woocommerce to load before we can hook into all the woo actions and filters. We are unable to run this any lower than it currently is.
