### ISSUE TITLE
product created using REST API is not associated to vendor

### ISSUE THREAD

**Issue by jcampos73** [wcvendors/wcvendors#266]
Hello,

When I create a product using REST API and vendor key (key is associated with a Vendor), created product is not associated to that vendor.

Steps to reproduce:

Generate a key/secret for a vendor.
Create a product via REST API using that key/secret

Kind regards

**Comment by bentasm1** [comment]
If you can set the post_author as the vendor's user ID, that's what you need to do. :)

**Comment by jcampos73** [comment]
Hello,

Thx for the fast response, but...

I am using

http://woothemes.github.io/woocommerce-rest-api-docs/#create-a-product

I dont see that field (post_author) there?

Thx a lot

**Comment by bentasm1** [comment]
That's because it doesnt exist. :)  You would have to use the WordPress API in addition to Woo's to set it.  A bit of a pain in the ass, granted, but until WooCommerce has an API that supports all of the meta keys / values it's what you'll have to do.

**Comment by jcampos73** [comment]
Thx for the fast answer :)
I will do so
