### ISSUE TITLE
paypalap - Add Transaction ID

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#268]
The "paypal" gateway adds a transaction ID on top of the order #.  See any WC Vendors order since we just use basic paypal.  However, our paypalap does not, and it doesnt store the transaction ID anywhere.  Time to upgrade so we do!

**Comment by digitalchild** [comment]
There are multiple transaction Id's returned with parallel payments however the woocommerce payment API only supports a single transaction ID so we cannot implement this there. We could however look at storing the transaction id's in the comments section instead?

**Comment by bentasm1** [comment]
Sure, that'd work.

**Comment by digitalchild** [comment]
Adaptive payments have been depreciated so this is no longer relevant.
