### ISSUE TITLE
Filter for fetch non-entered paypal email

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#274]
https://github.com/wcvendors/wcvendors/blob/22450857572469165103b9501eeb60814f343ec7/classes/class-vendors.php#L224

Add a filter for that line so that if the paypal email is not set it doesnt use one at all.  Not an option, just a filter is plenty fine.

Reference: https://www.wcvendors.com/help/topic/paypal-address-not-set-behavior/

**Comment by digitalchild** [comment]
Setting this to nothing will break the gateway. I will also have to modify the gateway so that if there is no paypal email set that the money goes to the admin, this is not as simple as it seems.

**Comment by digitalchild** [comment]
Not fixing this.
