### ISSUE TITLE
Drop database rows when order is emptied from trash

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#277]
When deleting orders in wp-admin, we should drop the database rows for them as well.  If possible, doing it when they are emptied from the trash rather than moved to the trash as an extra layer of protection.  This will prevent dashboard display issues when admins are testing things out or have actually trashed an order for some reason.

**Comment by digitalchild** [comment]
https://codex.wordpress.org/Plugin_API/Action_Reference/delete_post
