### ISSUE TITLE
Non-Object Notice

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#289]
https://github.com/wcvendors/wcvendors/blob/master/classes/class-install.php#L33

Notice: Trying to get property of non-object in /www/htdocs/w013a313/xxxxxxxxx.de/wp-content/plugins/wc-vendors/classes/class-install.php on line 33

**Comment by digitalchild** [comment]
Just fixe

**Comment by atorresbr** [comment]
Hello, it seems that is correction is not coming with WordPress plugin repository. I'm using MarketHub theme. When checked the problem, I made sure to direct install wordpress repository, problem continued. Now I fix the problem through this post.

**Comment by bentasm1** [comment]
@atorresbr that's pretty expected, since this is the non-wordpress.org repo and this change hasnt been pushed yet.  GitHub will always have the latest master and is available pre-release any time.

**Comment by atorresbr** [comment]
@bentasm1 👍 :)
