### ISSUE TITLE
Not all pages created @ Install

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#290]
Lot of posts about too many redirects from the my account page, always turns out that the Orders page is not set, when Free is installed and activated the first time.

1.) Fix Free (and Pro?) so that if a page is not set, it doesnt error out when logging in to /my-account/

2.) Ensure the Orders page is assigned correctly upon install

3.) (EXTRA CREDIT) A clickable button like Woo has to reinstall & set pages for when an admin screws up

**Comment by digitalchild** [comment]
Fixed too many redirects. Add new issue for 'create page' enhancement
