### ISSUE TITLE
PHP session starts at each page

### ISSUE THREAD

**Issue by stodorovic** [wcvendors/wcvendors#294]
Hello,

I had same issue before. It's https://github.com/wcvendors/wcvendors/issues/220 We fixed starting of sessions. But now, I see that you changed it again ( https://github.com/wcvendors/wcvendors/issues/285 ). I have big trouble with CDN and varnish (again) because each page (posts, product pages, ...) set PHPSESSID cookie. (which blocks caching by default)

I want to dedicate some time to resolve this issue (if you send some more info about issue 285). As some  compromise, I propose to we call function session_start() only if user is logged (in init action we can check it). I created pull request  #293. Also, it will good if developer could customize init_session (how to get_instance for WC_Vendors? then I could remove your action and add my action.)

Sasa

**Comment by digitalchild** [comment]
It appears that sessions were not being started at all so we actually broke it in #220 . This fixes it and now with your merged pull request it should fix sessions and your issues. If you can come up with a better way to manage sessions I'm all ears. Currently wc vendors isn't in a singleton so it's not possible to easily get an instance. I'm looking to fixing the instance issue in version 2.0.
