### ISSUE TITLE
Turkish translation

### ISSUE THREAD

**Issue by rehber7777** [wcvendors/wcvendors#299]
I have been translated to Turkish language a bit. I will go on again.

**Comment by bentasm1** [comment]
Sure, once you have a translated file, feel free to email to translate@wcvendors.com for inclusion in WC Vendors, and thanks very much!

**Comment by rehber7777** [comment]
has my translation been saved and will be used on wcvendors free?

25 Tem 2016 19:53 tarihinde "Ben Agresta" <notifications@github.com> yazdı:

**Comment by bentasm1** [comment]
Hi,

We didnt see any file attached to this issue, so we dont have your translation unless you've emailed us then I'm still going through new emails right now... :)

**Comment by rehber7777** [comment]
ooo. by github.com i did it :/

25 Tem 2016 19:57 tarihinde "Ben Agresta" <notifications@github.com> yazdı:
