### ISSUE TITLE
Property of non object

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#300]
`[23-Jul-2016 11:16:47 UTC] PHP Notice: Trying to get property of non-object in C:\OpenServer\domains\vendors\wp-content\plugins\wc-vendors\classes\class-install.php on line 33

https://www.wcvendors.com/help/reply/37995/

**Comment by digitalchild** [comment]
Their orders page isn't set. But that should not error out like that no matter what. I'm not sure how that is generating that error on the install.
