### ISSUE TITLE
Orders Page - shortcode shown, page not saving

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#304]
I see you've addressed the shortcode issue here: [(https://www.wcvendors.com/help/topic/code-shows-instead-of-orders-page-layout/)]
 I also want to bring up this issue reported, in case these are related:
[(https://wordpress.org/support/topic/wcv_orders?replies=1)]

**Comment by digitalchild** [comment]
Yes I'll be pusing 1.9.3 in the morning.
