### ISSUE TITLE
Only one vendor at a time

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#310]
https://www.wcvendors.com/help/topic/restrict-clientbuyer-to-order-from-one-vendor-at-a-time/
https://www.wcvendors.com/help/topic/restrict-buy-from-one-vendor-at-time/#post-41165

This enhancement has been requested.  Allow checkout to occur from only one vendor at a time.

**Comment by digitalchild** [comment]
Put the code provided into a gist and provide the gist when people want it. It's too specific to be included into free or pro.

**Comment by bentasm1** [comment]
There's some gists on my page with the checkout filter
