### ISSUE TITLE
Provide hooks for mass payments

### ISSUE THREAD

**Issue by hobailey** [wcvendors/wcvendors#312]
We're trying to make [our plugin](https://wordpress.org/plugins/mangopay-woocommerce/) be able to do payouts via our own payments/payouts API ([Mangopay](http://www.mangopay.com)) - instead of using PayPal - but it seems that the mass payment system is hard coded to use PayPal ([here](https://github.com/wcvendors/wcvendors/blob/master/classes/gateways/PayPal_Masspay/class-paypal-masspay.php#L149)).
So it would be great to have some hooks around this so that we can implement other payment methods (namely, ours :-) )
We'd either like to be able to pay out commissions X days after an order, or at the very least, use the existing "payment schedule" system but with another service than PayPal.
Let me know if that's not clear, or if you'd like any other info.

**Comment by digitalchild** [comment]
That is because the mass payment system is from paypal. It is part of their adaptive payments system.  Does mango pay include a mass payment system or is it individual transactions? We'd have to make a generic masspay class instead so that any gateway could hook into it. Thoughts ?

**Comment by hobailey** [comment]
Mangopay doesn't infact have a mass payment system, no. Opening up this class would be really helpful, and making it less PayPal centric would be no bad thing :-)

**Comment by digitalchild** [comment]
I agree however it's all paypal so it would make more sense to make a generic mass pay that everyone could hook into. First version, I'll take any pull requests for added filters that you need in the existing class.

**Comment by hobailey** [comment]
Totally agree. I'll see what we can do regarding filters for the existing class. Thanks for your quick feedback in any case :-)

**Comment by digitalchild** [comment]
No worries, the more gateways that work with our software, the more we can help our users to sell in more places! I'm also on Vietnam time so halfway between europe and american timezones.

**Comment by MounirHamani** [comment]
Hi there,
In the meantime and as a workaround, I have submitted a pull request #319 which might help you with the commissions payout by adding actions to the "Bulk Actions" dropdown menu.
Cordially, Mounir.

P.S. Too bad MangoPay is limited to european companies, your fee structure and rates would wipe out competition in other parts of the world.

**Comment by hobailey** [comment]
Awesome, thanks so much!

**Comment by avishai** [comment]
On a related note, we're considering using [TransferWise's Mass Pay](https://transferwise.com/business/mass-pay) feature to pay out our international vendors. They also have a very attractive fee structure and a mass pay API. I'd be happy to take a crack at writing the integration if you could open up the WC Vendors payment to other payment providers. 😄

**Comment by digitalchild** [comment]
Transfer wise were impossible to deal with. I spent a month trying to explain to them what I wanted without success. They didn't understand that I wasn't an end user but a developer trying to write an integration. Their developer on boarding doesn't seem to get that people will build tools they don't use themselves. If you can provide a pull request that 'opens up' the payment then I'm all for it. For now I'm closing this issue due to age and lack of further discussion.
