### ISSUE TITLE
Order management per product/vendor

### ISSUE THREAD

**Issue by hobailey** [wcvendors/wcvendors#313]
Hey, I've seen it discussed a bit here and there, but without much conclusion etc. 
A major need for marketplaces using this plugin is that there is order management on a per-product (or just per-vendor at least) level, so that commissions can be paid once a vendor has done their work/shipped etc, rather than having to wait for all the vendors in the order to have shipped (ie penalising quicker vendors because of the slower ones).
Presumably this could be acheived by creating multiple WooCommerce orders per vendor?

I appreciate this may not be simple to implement, but it really would be a great help for alot of people :-)

**Comment by digitalchild** [comment]
This is planned for version 2. We actually already have sub orders hidden in the code in preparation for this. But they are just sitting idle till its activated. Per product served its purposed but we need to do per order for commissions, shipping, and pretty much EVERYTHING to make woo integrations work properly.

**Comment by hobailey** [comment]
That's great news, really excited :-) Do you have a rough date/month for releasing v2?

**Comment by digitalchild** [comment]
Not at this stage. I'm still chasing my tail writing our replacement update and licensing system for pro :(

**Comment by hobailey** [comment]
OK, no problem.

**Comment by digitalchild** [comment]
Closing this discussion.
