### ISSUE TITLE
Placeholders missing from text inputs

### ISSUE THREAD

**Issue by avishai** [wcvendors/wcvendors#315]
I would add a placeholder to the `WCVendors_Pro_Form_Helper` class, to help vendors better understand what to write in free-form text fields (`input type='text'` and `textarea`).

<img width="1129" alt="screen shot 2016-09-21 at 11 34 42 pm" src="https://cloud.githubusercontent.com/assets/13284/18730123/f0666e82-8054-11e6-94bc-a215c8cf70d3.png">

**Comment by digitalchild** [comment]
This is a pro issue not free but I've added the placeholders for you. There was always filters you could modify to add these too. Check the form helper classes for details.
