### ISSUE TITLE
Commission Query Functions

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#321]
These functions will return a number only, or empty.

$vendor_id = self explanitory
$status = commission status (due, reversed, paid)

wcv_commissions_now ( $vendor_id, $status )

If my vendor ID is 1 and I have $100 in unpaid commissions, wcv_commissions_now('1', 'due') would return 100.00.

This will make it easier for plugin authors to extend their dashboards, entire site, etc... with integrating commission numbers.

**Comment by digitalchild** [comment]
What would you like the default status to be ? due?

**Comment by digitalchild** [comment]
The entire commission controller needs to be unravelled I'm not entirely sure why it is that complicated making it difficult for extensions to hook into it.

**Comment by bentasm1** [comment]
Probably the default being due is good
