### ISSUE TITLE
Multi-Currency capability? 

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#323]
https://www.wcvendors.com/help/topic/change-currency-depends-on-vendor/
This has been requested quite a few times, so I am adding it here in case of a possibility for a currency switcher; perhaps even just an option for the price to be viewed in the vendor's own currency if not actually switched.

**Comment by digitalchild** [comment]
If they want something like that we won't support it as gateways don't support multiple currency payments. If they need a currency switcher install a currency switcher and integrate it.
