### ISSUE TITLE
Loop sold by template

### ISSUE THREAD

**Issue by iben12** [wcvendors/wcvendors#324]
Hi,

I have this problem with WC Vendors for a long time now: the loop sold by template defined in classes/front/class-vendor-shop.php:179 contains a line break (`<br>`) at the end which breaks my layout. I really don't know what is it for that can't be achieved by CSS, but it's there. Since this is a hard-coded template rather than one defined in templates, you cannot override it in a child theme, which leaves me the only option to open that file and remove the `<br>` tag after every update. Wouldn't it be possible to include this as a real template?

**Comment by digitalchild** [comment]
We don't load any css on the shop pages which is why this is like this. I have put this into a template for you as per your request. It'll be available in the next update.
