### ISSUE TITLE
Detecting vendor ID for email (Notify Vendor)

### ISSUE THREAD

**Issue by Spreeuw** [wcvendors/wcvendors#327]
How can I detect the vendor ID for the Notify Vendor email when it's being sent?
I would use this to determine which order to use when creating a [PDF invoice](https://wordpress.org/plugins/woocommerce-pdf-invoices-packing-slips/).

Or, alternatively, would it be possible to not use the main order (shop_order) as the email object but the vendor order (shop_order_vendor) object instead? That would also allow you to get rid of a the [filters you're currently using](https://github.com/wcvendors/wcvendors/blob/48c9b2c202c9ccb051c0fe5c710fb955fe3a3c98/classes/admin/emails/class-wc-notify-vendor.php#L79-L82), because all order functions would be performed on just the vendor order.
That solution would actually be preferable for me too.

Let me know your thoughts!
Ewout

**Comment by digitalchild** [comment]
We will be working towards using the shop_order_vendor object for version 2.0.  Discussions have begun about what will be updated/changed. For now you can look at the existing emails to see where we grab the vendor id from in the trigger function which references get_vendors in the same email class.

**Comment by Spreeuw** [comment]
Thanks! I can't find a way to access the vendor id from the 'current email'. I can get a list of vendors for the current order but that wouldn't tell me which  AFAIK there is no global value that can be read - `$this->current_vendor` is not accessible from the email filters (like [woocommerce_email_attachments()](woocommerce_email_attachments)). Or am I missing something?

**Comment by digitalchild** [comment]
You'd have to create your own function with that filter which gives you the order and extract the vendor ids yourself and then attach based on vendor id that you get from the product. Another option would be to add an attachment function into our email classes with a filter you can override that way you are accessing the email class object with the vendor id. If you can write something I'd be happy to check it and then add it to our next release for you.

**Comment by Spreeuw** [comment]
I see - since the get_items() is filtered already for the vendor emails, I can always assume that all items are for the 'current_vendor', and then simply take the vendor_id for the first item and work from there. As a temporary workaround that should be fine :)
Thanks!
