### ISSUE TITLE
HTML title attribute doesn't change for store pages

### ISSUE THREAD

**Issue by avishai** [wcvendors/wcvendors#328]
The HTML `<title>` attribute is not set when viewing a store page (pro). When viewing the vendor's store page, the title just says `"Products - Site Name"`. It should be `"Vendor's Store Name - Site Name"`

The way it is now is problematic for SEO, plus if you have a couple of vendor store tabs open, you can't tell which is which. 

![image](https://cloud.githubusercontent.com/assets/13284/19491371/b132e01e-9540-11e6-8508-9ece0bf8bd5a.png)

**Comment by fervous** [comment]
https://gist.github.com/fervous/2afc70872305e7f3ff1bd873ab45579f
