### ISSUE TITLE
Capabilities Fix for Resetting Roles

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#329]
When resetting wp-admin > woo > sys status > tools > reset wcv roles, the delete_posts capability is not set correctly.  It should be set to 'true'.

( /wc-vendors/classes/admin/class-admin-page.php ) and change around line 136 to add the delete_posts = 'true'. )

**Comment by fervous** [comment]
https://www.wcvendors.com/help/topic/enable-vendors-to-delete-photos-media/

Involved adding 'delete_posts' => true, to lines approx 138-148
