### ISSUE TITLE
Deny publishing a product

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#33]
http://www.wcvendors.com/help/topic/decline-a-product/

If product should not be approved by site admin, all admin can do right now is trash it or set it to a draft.  Need notification system to send vendor a message of why it isnt approved, and set post status to admins choice.

**Comment by digitalchild** [comment]
Could use Post Status Transitions to hook into the trash status to send off an email to say product deny + reason. Will look into the admin interface hooks for this. Possibly a deny button on the actions list. 

http://codex.wordpress.org/Post_Status_Transitions

**Comment by bentasm1** [comment]
I like:  

pending_to_draft as (Deny and trash) or pending_to_draft (Deny set draft) as two options for it.  We could then make a Woo email template that would notify the vendor, or just use a simple wp_mail call to them.  If clicking Deny and trash or Deny set draft provided a popup window for the email contents for a message, that would be even handier.

**Comment by digitalchild** [comment]
I say we use templates so that users have customisation options. I think all our emails should be customisable via the dashboard and templates.

**Comment by bentasm1** [comment]
Agreed.  The extra popup window append to the email that way we can use both, or just the standard template.

**Comment by bentasm1** [comment]
Let's move this to Pro as a feature in that instead......
