### ISSUE TITLE
New Order Email: Commissions Subtotal coloumn is showing Full Product Price

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#330]
https://www.wcvendors.com/help/topic/new-customer-order-email-commission-subtotal/#post-47454

Tested.  Commission is set to 95% to the vendor. Commissions calculations are correct (wp admin > WC > Commissions).  In the email, however, Product Total Sale price of $36.00  is shown in the Commissions Subtotal Column (it should be 95%=$34.20).

My test:
![comsubt](https://cloud.githubusercontent.com/assets/13291807/20243660/99091ae8-a91e-11e6-9ca6-9d08111883af.jpg)

**Comment by chomomahesh** [comment]
Hi, can i know is this issue fixed on new version ?

**Comment by digitalchild** [comment]
Until our next release. You can go to the email options for this email template and save the settings. This will trigger the settings to be saved and the correct totals will be displayed.
