### ISSUE TITLE
If I'm looking to add vendor name on products for the "store" page...

### ISSUE THREAD

**Issue by DylanAlloy** [wcvendors/wcvendors#331]
How would I do that? I'm having a hard time discovering the structure I should be playing with. 

![ffdasf](https://cloud.githubusercontent.com/assets/12659763/20281361/366fddb6-aa7e-11e6-8fd3-154fb3f9a599.PNG)

Is what I'm looking to do for all of the products on the woocommerce shop page so that those browsing can see who sells what without mousing over or anything.

**Comment by bentasm1** [comment]
www.wcvendors.com/help/ for tech support.  GitHub is for issues and developers sending in patches/fixes/additions. :)
