### ISSUE TITLE
Add option to override "give shipping to vendor" on a per-vendor basis

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#332]
https://www.wcvendors.com/help/topic/pdf-vouchers-and-pro-vendors-dashboard/#post-41717

Admin can select to *NOT* give shipping to a vendor.. override on a per vendor basis.  Shipping goes to admin.  (i.e. for drop shipping...).

**Comment by avishai** [comment]
Is it possible to give shipping to vendor if _not using_ the built-in Vendor Shipping method? It seems there is already an association between the shipping order line item and the vendor & product IDs...

**Comment by fervous** [comment]
avishai,
This solution would require custom coding work; while it may be feasible, remember that commission are calculated on a per product basis, and most shipping plugins calculate on a per order basis (whole cart).

**Comment by fervous** [comment]
Closing- this is a really rare request- probably not needed by many users.  Also- this is a terribly worded issue- sorry! :-P
