### ISSUE TITLE
Uploaded media doesn't get attached to post

### ISSUE THREAD

**Issue by avishai** [wcvendors/wcvendors#333]
## Description

When uploading images via the WC Vendors Pro dashboard, uploaded images do not get "attached" to the product post in WordPress, even they're associated with the correct product's image gallery:

![image](https://cloud.githubusercontent.com/assets/13284/20853968/e726b402-b8bd-11e6-888c-494f39794a09.png)

Yet, when you go to the WP Admin backend and try to select one of the uploaded files using the media library's "Uploaded to this product" dropdown option, no media appears:

![image](https://cloud.githubusercontent.com/assets/13284/20854006/2a1b1fd2-b8be-11e6-8aad-09b295caa225.png)

### System
- WC Vendors Pro by WC Vendors – 1.3.7
- WC Vendors by WC Vendors – 1.9.5

**Comment by digitalchild** [comment]
I have already created this in Pro. Please stop creating issues for pro in our free repo.
