### ISSUE TITLE
Cannot select multiple items from media library when adding to product gallery

### ISSUE THREAD

**Issue by avishai** [wcvendors/wcvendors#334]
When adding photos to the product gallery from the Pro Dashboard's product edit form, it's not possible to select more than one image at a time. This modal should allow multiple selection; the current single-selection mode makes it necessarily lengthy to add photos to the gallery.

<img width="1244" alt="screen shot 2016-12-15 at 1 14 35 pm" src="https://cloud.githubusercontent.com/assets/13284/21236301/7d2d1a72-c2c8-11e6-8dd8-df958d4c5f4d.png">

**Comment by digitalchild** [comment]
You cannot select multiple images in the woocommerce gallery selection in the backend either.  Also this git hub is for free issues only. If you have issues with pro please post them to our forums.

**Comment by avishai** [comment]
@digitalchild okay, I've opened this directly on WooCommerce then. https://github.com/woocommerce/woocommerce/issues/12856

**Comment by avishai** [comment]
@digitalchild Turns out that's not the case. In the WooCommerce backend, adding multiple images at once _does work_, using shift+click or command+click. I've verified this in the WC backend, and the issue only persists in the WC Vendors product edit form.

**Comment by digitalchild** [comment]
OK, i'll create an issue in our pro repo.
