### ISSUE TITLE
Terms & Conditions not Translating

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#335]
https://www.wcvendors.com/help/topic/translation-issue-2/
I have seen this before and we've discussed it; I just realized it has not been added to either free or Pro issues. (I THINK free is the right place for this-...)
This will not translate, and also I am unable to change the text using a filter:
**I have read and accepted the terms and conditions**

**Comment by digitalchild** [comment]
This is a pro only bug. Please move this to pro issues.
