### ISSUE TITLE
textdomain

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#341]
wp.org's translation page for us says we load the textdomain incorrectly.  This is the full slack channel log from make.wordpress.org's slack channel related to this issue:

![capture](https://cloud.githubusercontent.com/assets/6693745/22867460/9dd4cf74-f156-11e6-999b-fa939d0890bc.PNG)

**Comment by digitalchild** [comment]
Do they provide any more information has to what is wrong? Where is this information from? Can I get a link instead of a screen shot?

**Comment by bentasm1** [comment]
wordpress.org/plugins/wc-vendors/ click translate wc vendors.  then follow the warnings @ the top to join slack and stuff, they tell you the channnel and how to see it.  This is all the information they provided.
