### ISSUE TITLE
Report "Sales by product" count wrong

### ISSUE THREAD

**Issue by yktsan** [wcvendors/wcvendors#343]
After install WC vendor, woocommerce > reports > "Sales by product" count wrong

**Comment by bentasm1** [comment]
Sales by product count goes by total_sales meta key/value.  This is WooCommerce.  WC Vendors never touches that key/value pair.

**Comment by yktsan** [comment]
Activate:
![01](https://cloud.githubusercontent.com/assets/289701/23713213/22fc057a-0460-11e7-97e5-09b9e06c0abe.jpg)

Deactivate:
![02](https://cloud.githubusercontent.com/assets/289701/23713230/33a666a4-0460-11e7-8c28-4c4ed26423a7.jpg)

My theme is "Storefront"

**Comment by digitalchild** [comment]
Is this for the admin user or a vendor?

**Comment by yktsan** [comment]
Admin user

**Comment by yktsan** [comment]
Any idea?

**Comment by digitalchild** [comment]
Cannot replicate. Closing

**Comment by Spirit55555** [comment]
I'm having the same problem, should I open a new issue, or do you want more information here?

**Comment by digitalchild** [comment]
@Spirit55555  Can you provide details on how to replicate this and I'll be able to narrow down the issue.

**Comment by Spirit55555** [comment]
I can send you the Woocommerce status page, if that would help?

I also noticed that the widget on the dashboard of WP shows the correct amount sold by the most popular item.

**Comment by digitalchild** [comment]
WooCommerce status won't help. This is a statistics issue which means something isn't calculating correctly or wcvendors is hooking into something it shouldn't be.

**Comment by Spirit55555** [comment]
Tell me what information you need, and I will get it for you.

**Comment by digitalchild** [comment]
I'm currently in the process of completely rewriting wc vendors which will include new reports code. So I'm going to close this as the new code will replace all of this.
