### ISSUE TITLE
Notification to site admin when vendor marks a product shipped

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#344]
Request to have either an email or some other type of notification to the site admin when a vendor has marked a product as shipped.
https://www.wcvendors.com/help/topic/vendor-shipped-notification/#post-58736

**Comment by digitalchild** [comment]
We already have this in free. It shows a shipping icon on the order screen and view order shows 'shipped' under order details.

**Comment by bentasm1** [comment]
That is not a notification, though.  I think perhaps what would be of easy use would be to allow them to add another email it sends to, similar to WooCommerce and their order emails, for this email too:

/wp-admin/admin.php?page=wc-settings&tab=email&section=wc_email_notify_shipped

**Comment by avishai** [comment]
@bensasm1 you could intercept the shipment tracking info and work off of that, too:

`add_action( 'wcv_update_shipment_tracking', 'do_something_with_tracking_details', 10, 2 );`

**Comment by digitalchild** [comment]
Done
