### ISSUE TITLE
v1.9.9 - vendor image upload is not working when Select Files button is used.

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#345]
- Vendor chooses to Add Product (or edit product).  If  "Set Product Image" or "Add Product gallery images"  is selected on the add/edit product page and the vendor attempts to upload an image, the "Select Files" button does not work to upload an image.  Click it, nothing happens.   
The vendor CAN Drag & Drop an image to upload, and they can also add a product image that already exists in the media library.

- If the vendor goes to: wp admin > media library, the vendor CAN upload images by using the "multi-file uploader" or by dragging files to the "Drop files anywhere to upload" ... but they CANNOT upload an image by clicking the button "(button)Select Files", as that button also does not work at all.
  
- Admin role is able to upload using all methods when adding a product from wp admin > products > add product.  "Select Files" button works for the Admin.

**Comment by fervous** [comment]
I just discovered that this occurs when using Chrome, but not when using FireFox.

**Comment by fervous** [comment]
This is an issue with WP and Chrome. Closing.

**Comment by bentasm1** [comment]
Re-open!  Just because it's Chrome, doesnt mean we cant fix it.  Still investigate just in case.

**Comment by digitalchild** [comment]
um no, this is wordpress and chrome and has NOTHING to do with our plugins.
