### ISSUE TITLE
Order Status Strings are not translatable

### ISSUE THREAD

**Issue by canyasa** [wcvendors/wcvendors#353]
Order Status Strings are not translatable, could you change `ucfirst( $order->get_status() )`on **wp-content/plugins/wcvendors-pro/public/class-wcvendors-pro-order-controller.php** line 528 to `ucfirst( wc_get_order_status_name( $order->get_status() ) )`

Reference link: https://www.wcvendors.com/help/topic/orders-status-translation-strings-completed-processing/

**Comment by digitalchild** [comment]
Fixed. Will be in 1.4.2 release.
