### ISSUE TITLE
WC Vendors Test Gateway : 500 Error

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#355]
This is occurring on the https://dev.wcvendors.com site.
I cannot replicate this on my local development site, so I do not have the error_log yet.  The WC Vendors test gateway works fine on my local dev site.

I have asked some users who have reported this to provide error_log details.

**Comment by digitalchild** [comment]
Nothing to do with test gateway. Pro commission file was the culprit. Updated and all working now.1.4.3 is ready to release to fix this for all sites.
