### ISSUE TITLE
Vendor New Order Email Issues

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#356]
Getting reports of issues with the new order emails to the vendor.  I need to test this still- I have to set up a live site to do so since local does not send me emails.  I'll update with what I find or close the issue if needed. 
 
- Orders not sending completed order emails – I need to manually “resend”
- Order emails and order received page upon checkout do not show shipping cost, instead they show vendor shipping method.
- Variable products orders are shown as – 1 x Variation #6748 Product name (Not sure why variation ID)

**Comment by digitalchild** [comment]
1. Completed order emails ? As in set order to complete? 
2. Confirmed this is an issue 
3. All variations are now displayed like this. Please see cart, checkout and final orders in my-account page. The variation titles are now used instead of the Parent product. This is not us this is WooCommerce 3.0

**Comment by fervous** [comment]
1. this was how it was reported by the user-- I'll see if he will clarify. 

3. Ok I will let him know that this is how they will show now due to WooCommerce

**Comment by fervous** [comment]
- Report of vendor new order email not showing Vendor Coupon discounts.  Full price shown without discount.
- I have not had any further reports of the emails not sending (needing to be manually sent).  I think that was an isolated issue with that user.

**Comment by digitalchild** [comment]
I dont think the coupon information has ever worked in the emails. This will take a bit of work to fix. Not high on the list right now.

**Comment by fervous** [comment]
Order emails for variable products do not show the shipping cost; likely related to this issue, perhaps? https://github.com/wcvendors/wcvendors-pro/issues/571

**Comment by fervous** [comment]
Ok, now that issue #571 is resolved.. the variable product shipping cost is now appearing in the vendor-notification email., but the product total and commission are still showing as $0.00.

**Comment by digitalchild** [comment]
Is this for variable products only?

**Comment by fervous** [comment]
Yes, Jamie, this is for variable products.  The product total and commission show 0 in the variable product emails.

**Comment by digitalchild** [comment]
I'm pretty sure these have been fixed. Please test with latest pro

**Comment by fervous** [comment]
Looks good to me! :-) Variable product shows proper shipping:
![testvariable-shipping-email](https://user-images.githubusercontent.com/13291807/27417957-4931b132-56d5-11e7-86c8-381606c19021.jpg)

**Comment by digitalchild** [comment]
closing
