### ISSUE TITLE
A vendor should be able to manage his own featured products 

### ISSUE THREAD

**Issue by rhurtik** [wcvendors/wcvendors#358]
A vendor should be able to manage his own featured products and this option is already “half implemented” in the system because vendor can flag a product as featured if the product is edited through the ‘Quick Edit’ link or when he is editing the product’s ‘Catalogue visibility’. 
I have tested the products modified by a vendor and the featured modifications is correctly reflecting on admin product listing. 

How ever, even though is the vendor able to feature his own product the shortcode `‘[wcv_featured_products vendor="VENDOR-LOGIN-NAME"]’ `
return an empty output because its content is based on the meta key ‘_featured’ from ‘wp_postmeta.meta_key’ column and this meta key is not being inserted or updated.  

To fix this we would have to refactor the static method `‘WCV_Shortcode::featured_product’ `
and instead of fetching the featured meta key in the ‘wp_postmeta.meta_key’ we should simply reuse the existing admin mechanism. 

It will simplify the complexity of the process.

**Comment by digitalchild** [comment]
The reasons that vendors cannot set their own products featured is due to the fact that vendors can and will set every product to be featured. There are a few things that vendors can't do because they will abuse the system. This includes featured products ( as this is site wide ), attributes or categories.  That shortcode exists because we had people that that allowed vendors to pay for featured products through other mechanisms but the marketplace still sets the products featured manually.

**Comment by rhurtik** [comment]
@digitalchild  This approach fits into some specific busyness model and to some not. I am surprised that you have chosen to programmatically lock this option instead of including a decisional checkbox into admin front end. 
Stripping the system of an existing feature is a narrow minded approach. The prove is here I am just extending the plugin to bring back to users the wp core features which have been  disabled for their well being. 
I will leave this with you guys either : 
1. You may keep this option hardcoded in your project and limit the usability for a specific busyness model. 
2. You extend the functionality of your system, you add a decision checkbox to admin front end and let the users decide what is best for their  busyness.

**Comment by bentasm1** [comment]
Pro feature.  It's in the Pro's Product Edit form.  Check on to enable.  Uncheck to disable.

**Comment by rhurtik** [comment]
Are you sure about your statement? If yes please explain why this option doesn’t show up in WC Vendors Pro Features => https://www.wcvendors.com/#pro-2 and why the integration of this feature doesn’t show up in this topic => https://www.wcvendors.com/help/topic/vendor-able-to-mark-products-as-favourites/#post-33354 ?
