### ISSUE TITLE
Edit Published Products Permission Issue

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#359]
If admin grants vendors the capability to 
- Submit products
- Submit products live without requiring approval

Yet DENIES the capability to 
- Edit live products

When the vendor publishes a product, they are shown the white box on the screen with the error message: 
**Sorry, you are not allowed to access this page.**

With WC Vendors free, the vendor remains on the published product page- which would now be considered the EDIT page..... and since they do not have editing permissions for live products...   Boom. No access allowed for you. ;-)

With WC Vendors Pro, this does not occur, since the vendor is directed differently after product submission. 

https://www.wcvendors.com/help/topic/wc-vendor-edit-published-products-issue

**Comment by digitalchild** [comment]
What is the issue here? Is this that they can't publish new products or can't publish edits and get the standard wordpress error message?

**Comment by fervous** [comment]
The product is published.  They are shown the error because after publishing they remain on the product add/edit page.  It's confusing to the vendor.   It does not prevent them from publishing the product.

**Comment by digitalchild** [comment]
OK I see what the problem is here. There is no easy way to fix this as this is a Wordpress limit in how we remove access. We use the built in Wordpress capabilities and the message comes from this. I would have to write our own permission system. Will not be doing that.
