### ISSUE TITLE
Backend validation for Coupons

### ISSUE THREAD

**Issue by damanmehta** [wcvendors/wcvendors#362]
While creating coupons, anyone can add any product ID to the text field(Inspect element hack). Even if that product doesn't belong to that vendor.

And coupons are generated successfully. Looks like there's no backend validation. There should be some sort of backened check to see if coupon creater is the real owner of product.

**Comment by digitalchild** [comment]
Coupons are not configured to work in free at all. If you have enabled them to work you will have to do all the extra work to make that happen. Coupons are only written to work in pro.
