### ISSUE TITLE
The plugin does not have a valid header message

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#365]
When installing WC Vendors from wp.org.. if you try to activate it right after uploading/installing this message is shown: “The plugin does not have a valid header.” 
You can go and activate it from plugins > installed plugins. .. But this is causing confusion for new users.

**Comment by digitalchild** [comment]
Do you mean via search?

**Comment by digitalchild** [comment]
This has been fixed in 1.9.12
