### ISSUE TITLE
Email template overrides should go in woocommerce/emails

### ISSUE THREAD

**Issue by avishai** [wcvendors/wcvendors#373]
Currently, to override email templates, they have to be present in the `mytheme/woocommerce/` directory. To be consistent with other WooCommerce plugins that override emails, these should go in `mytheme/woocommerces/emails/`. Can you please update the template paths for the next release?

Thanks :-)

**Comment by digitalchild** [comment]
Updating the template paths will break anyone that has already overridden the templates. We can look into doing this for version 2.

**Comment by digitalchild** [comment]
This is half complete with 4 new email templates having been added to the code now. Need to update the existing templates to use the new system. 

All existing emails will be replaced while existing ones will stay in place. All new emails will stay disabled for now.

**Comment by digitalchild** [comment]
This has been completed.
