### ISSUE TITLE
Admin Commission Report / Breakdown

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#376]
I have had several requests for a more detailed report, specifically one in which the site admin could see a breakdown of the admin commission / earnings as well as vendor commission earnings

Such as shown wp admin > WooCommerce > Reports > WC Vendors.. we can view by product and by vendor..

the addition of an additional tab/link for admin commission would be helpful for many site admin to be able to see what they have received as profit as well.

**Comment by digitalchild** [comment]
Site admin commission isn't stored anywhere, so this would have to be calculated and cached to even be possible. Right now this isn't easily possible without some serious updates to the code that includes logging the admin commission in the commissions table.
