### ISSUE TITLE
Add Payment method used to New Order (notify vendor) email

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#377]
Request to add the payment method that a vendor used to purchase the products to the Notify Vendor email for new orders.  This way the vendor knows where to expect the payment. (Stripe or paypal, etc.).

Support ticket: https://wcvendors.zendesk.com/agent/tickets/426

**Comment by digitalchild** [comment]
Payment methods and commissions are completely separate and not related in this context. Just because we provide Stripe and Paypal payments for commissions doesn't mean the vendor should know what payment method the customer used to purchase.
