### ISSUE TITLE
Post called incorrectly wc_doing_it_wrong line 4139

### ISSUE THREAD

**Issue by rsg-ndilworth** [wcvendors/wcvendors#378]
Using WooCommerce 3.2.1, and WC Vendors Free 1.9.12.

With only those plugin activates, this error appears on the product detail page:

Notice: post was called <strong>incorrectly</strong>. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce/templates/single-product.php'), wc_get_template_part, load_template, require('/plugins/woocommerce/templates/content-single-product.php'), do_action('woocommerce_before_single_product'), WP_Hook->do_action, WP_Hook->apply_filters, WCV_Vendor_Shop::vendor_mini_header, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 3.0.) in /var/www/html/wp-includes/functions.php on line 4139

Can this be fixed?

**Comment by rsg-ndilworth** [comment]
The line 264 in _wc-vendors/classes/front/class-vendor-shop.php_ that produces the error:

` if ( WCV_Vendors::is_vendor_product_page($product->post->post_author)) {`

**Comment by digitalchild** [comment]
This has been fixed. thanks.
