### ISSUE TITLE
Blank spaces at the end of lines with no changes

### ISSUE THREAD

**Issue by jsonUK** [wcvendors/wcvendors#387]
Hi,

I just want to make a polite request about a minor but pretty annoying issue.

When comparing you changes between version releases - I keep seeing lines that have no changes but have blank spaces appended to the end of them...

Can you please update your editor to trim "whitespaces" upon saving - this is getting into your live releases and is unnecessary.

Thanks

![screen shot 2018-01-18 at 09 59 26](https://user-images.githubusercontent.com/1830568/35092215-9a027356-fc36-11e7-8918-b8c72a93752f.png)

**Comment by digitalchild** [comment]
Editor updated, sorry about that.
