### ISSUE TITLE
Your support page appears broken

### ISSUE THREAD

**Issue by jsonUK** [wcvendors/wcvendors#389]
Hi,

Tried to submit a support ticket on your website. Was taken to a blank ajax request page.

I believe it's broken.

https://www.wcvendors.com/help/submit-help/

**Comment by digitalchild** [comment]
Hi @jsonUK 

I am aware of the issue and I'm working to release a whole new website in the next week to fix this. Tickets are submitted, the theme is just hosed after the last update, I'm spread thin atm and doing what I can to get everything sorted. 

thanks for your patience.
