### ISSUE TITLE
how can i get chat data for a particular vendor

### ISSUE THREAD

**Issue by redsparkers** [wcvendors/wcvendors#391]
Hello i want to make api and send the chart data to the andorid, but how can i get the chat data from a user_id. ? 
refer- attahment ->Dashboard_sales.png
![dashboard_sales](https://user-images.githubusercontent.com/35765884/35851086-e4d07d18-0b4c-11e8-984d-ab87dc659344.png)

**Comment by digitalchild** [comment]
I do not understand what you mean by chat data. This screen shot is not from our product.

**Comment by redsparkers** [comment]
Hello i want to make api and send the chart data to the andorid, but how can i get the chat data from a user_id. ?
refer- attahment ->Dashboard_sales.png
![dashboard_sales](https://user-images.githubusercontent.com/35765884/35898981-c7998840-0bef-11e8-8f21-28df9151857e.png)

**Comment by digitalchild** [comment]
Once again, this screen shot is not from our product. I have no idea what this screen is or where it comes from. Order data comes from woocommerce and the commissions table.
