### ISSUE TITLE
Terms & Conditions Checkbox for Vendor Registration does not show

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#392]
Tested on Storefront 
After updating to v1.9.14, the Terms & Conditions checkbox does not appear once a registrant has checked "apply to become a vendor" checkbox.
It DOES appear with v1.9.13, so it is something with the new update.

https://wcvendors.zendesk.com/agent/tickets/2058

**Comment by digitalchild** [comment]
Confirmed hosed.
