### ISSUE TITLE
Coupon Discount is not shown in Vendor New Order email (testing needed)

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#393]
Order notification Emails to the admin and customer show the coupon discount. But the vendor's new order email does not show the coupon discount.
Screenshots:
Admin & customer:
![cdibkp8l png](https://user-images.githubusercontent.com/13291807/34113930-895438da-e3ce-11e7-92b8-e75375b8b5f4.jpg)

vendor:
![0erxwzkl png](https://user-images.githubusercontent.com/13291807/34113944-91ff88cc-e3ce-11e7-90fc-e22c16c82fda.jpg)

**Comment by digitalchild** [comment]
New email system allows for this to be hooked into properly now. Will fix in pro.
