### ISSUE TITLE
Vendor Custom Product Attributes

### ISSUE THREAD

**Issue by v1images** [wcvendors/wcvendors#398]
Since the WooCommerce upgrade to v3.0 and above it is now no longer possible for a vendor to add a Custom Product Attribute that is not already in that particular list. The 'Add New' button is present, and the pop-up comes open when clicked but when the vendor submits this data it does not enter into the Value field.

This works fine with an administrator account but not for a vendor account.

**Comment by digitalchild** [comment]
It appears that WooCommerce has removed the text input from attributes. Allow vendors to create attribute terms will lead to catalog spam issues. I'm checking with WooCommerce but I don't think there is a way around this.

**Comment by digitalchild** [comment]
Nothing can be done here as its not possible to allow the vendors to add these at this time.
