### ISSUE TITLE
Invalid references in sf-class-settings.php

### ISSUE THREAD

**Issue by bporcelli** [wcvendors/wcvendors#401]
There a couple of typos on line 606 in sf-class-settings.php. This is causing a fatal error when a plugin uses the deprecated `get_option` method.

This:

`return ( array_key_exits( $name, $amppings ) ) ? get_option(  $mappings[ $name ] ) : null;`

Should be this:

`return ( array_key_exists( $name, $mappings ) ) ? get_option(  $mappings[ $name ] ) : null;`

Thanks!

**Comment by digitalchild** [comment]
Thanks @bporcelli
