### ISSUE TITLE
Missing closing quote for href in html-notice-update.php

### ISSUE THREAD

**Issue by bporcelli** [wcvendors/wcvendors#402]
The href for the anchor tag in html-notice-update.php is not closed. This leads to an invalid link address like "http://example.com/wp-admin/admin.php?page=wcv-settings&do_update_wcvendors=true%20class="

Also, there are two versions of html-notice-update.php (classes/includes/views/html-notice-update.php and classes/admin/views/notices/html-notice-update.php). They appear to be identical. Not sure if this is intentional or not.

**Comment by digitalchild** [comment]
Yes, that bit of code was old but I ended up adding a new notice class which should make this depreciated. Will update relevant references.

**Comment by digitalchild** [comment]
Thanks @bporcelli
