### ISSUE TITLE
Undefined variable: this in WCVendors_Admin_Menus::commissions_menu

### ISSUE THREAD

**Issue by bporcelli** [wcvendors/wcvendors#403]
It appears the method `WCVendors_Admin_Menus::commissions_menu` was accidentally declared as static in 2.0. This means that your references to `$this` in that method are invalid (see below).

Notice: Undefined variable: this in /srv/www/wcvendors/public_html/wp-content/plugins/wc-vendors/classes/admin/class-admin-menus.php on line 72
Notice: Undefined variable: this in /srv/www/wcvendors/public_html/wp-content/plugins/wc-vendors/classes/admin/class-admin-menus.php on line 73

**Comment by digitalchild** [comment]
Thanks
