### ISSUE TITLE
Code element is present causing gray on front end

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#408]
<code>  </code> is present in various regions causing gray sections to appear when vendor dashboard pages and the vendor list is viewed.
Chrome and Firefox
screenshots:
![code1](https://user-images.githubusercontent.com/13291807/39091230-1d1b8a2e-45ad-11e8-8ae3-549292a3a9d6.jpg)
![code2](https://user-images.githubusercontent.com/13291807/39091231-21b197ea-45ad-11e8-98e5-4f136e43d3a7.jpg)

**Comment by digitalchild** [comment]
Code is not present on any front end classes so I'm not even sure how these are outputting. I've checked and cannot find anything in the code for this. I can't replicate it either..

**Comment by CasperBraske** [comment]
Can't reproduce either. 
As far as I can see they are both output using `ob_start()`/`ob_get_clean()` inside _shortcodes_.
Are you using xdebug? 
I remember having that problem in an unrelated project. Will come back with the solution if I remember.
