### ISSUE TITLE
PHP Warnings

### ISSUE THREAD

**Issue by alexys63** [wcvendors/wcvendors#429]
Hello,
I found PHP warning logged as vendor on products dashboard:
```
Warning: in_array() expects parameter 2 to be array, string given in /htdocs/wp-content/plugins/wc-vendors/classes/admin/class-admin-users.php on line 174
Warning: in_array() expects parameter 2 to be array, string given in /htdocs/wp-content/plugins/wc-vendors/classes/admin/class-admin-users.php on line 193
```
Urls affected:
```
/wp-admin/edit.php?post_type=product
/wp-admin/post-new.php?post_type=product
/wp-admin/post.php?post=207223&action=edit
```
Versions : 
Wordpress 4.9.6
WooCommerce 3.4.2
WC Vendors 2.0.7

**Comment by alexys63** [comment]
I made a var_dump on parameter 2 it return : string(6) "simple"
I hope this help.

**Comment by digitalchild** [comment]
Please go into WC Vendors > Settings > Capabilities > Products and save this page. Does this still occur?

**Comment by digitalchild** [comment]
Ok good to know. This was an issue with what was stored in your database.
