### ISSUE TITLE
Notice on activation of buddypress plugin

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#43]
Notice: bp_setup_current_user was called incorrectly. The current user is being initialized without using $wp->init(). Please see Debugging in WordPress for more information. (This message was added in version 1.7.) in /sites/wcvendors/wp-includes/functions.php on line 3370

This is because wcv is loading current_user in the wrong context and will need to be fixed.

**Comment by svenl77** [comment]
Just had a quick look, not sure if its correct but I think this issue can be fixed by changing the hook from "plugins_loaded" to "init" in class-wc-vendors.php on line 78.

I have done some testing and so far it solves this issue.

**Comment by digitalchild** [comment]
I'll have a look into this. I did try changing it to init a while ago but I had some issues with woocommerce functionality breaking due to it loading after WC Vendors.

**Comment by digitalchild** [comment]
Is this still an issue?

**Comment by bentasm1** [comment]
I've always used BuddyPress, and I've never seen this ever be an issue.  And never had any members other than sven report it was an issue.  I'm confident we have a lot of BuddyPress users by the amount of support threads we get on integration.  Likely close the issue unless someone can give us a step by step to replicate a possible issue.
