### ISSUE TITLE
Reporting Templates

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#44]
https://wordpress.org/plugins/woocommerce-mis-report/

**Comment by digitalchild** [comment]
What would you like from this plugin to be integrated?

**Comment by bentasm1** [comment]
Nothing in particular.  It's just a handy reference for making pie charts and things like that for WooCommerce.  It would make a good vendor report replacement for the back-end and possibly the front-end.

**Comment by digitalchild** [comment]
Depreciated feature, will not fix.
