### ISSUE TITLE
Vendors new order email notification not working after update 2.0.8

### ISSUE THREAD

**Issue by joacovitale** [wcvendors/wcvendors#443]
Hi, I did the last update and the email for new orders to vendors stopped working.

The error is the following:

_You have received an order. The order is as follows:

Order #27842 (25/06/2018)

Fatal error: Uncaught Error: Call to undefined function wcv_get_vendor_order_items() in /var/www/clients/client18/web82/web/wp-content/plugins/wc-vendors/templates/emails/vendor-order-details.php:49 Stack trace: #0 /var/www/clients/client18/web82/web/wp-content/plugins/woocommerce/includes/wc-core-functions.php(210): include() #1 /var/www/clients/client18/web82/web/wp-content/plugins/wc-vendors/classes/admin/emails/class-emails.php(252): wc_get_template('emails/vendor-o...', Array, 'woocommerce', '/var/www/client...') #2 /var/www/clients/client18/web82/web/wp-includes/class-wp-hook.php(286): WCV_Emails->vendor_order_details(Object(WC_Order), Array, 'commission', 220, true, false, false, Object(WCVendors_Vendor_Notify_Order)) #3 /var/www/clients/client18/web82/web/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #4 /var/www/clients/client18/web82/web/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /var/www/clients/client18/web82/web/wp-content/plugins/wc-vendors/templates/emails/vendor-notify in /var/www/clients/client18/web82/web/wp-content/plugins/wc-vendors/templates/emails/vendor-order-details.php on line 49_

Thanks in advance,
Best regards.

**Comment by digitalchild** [comment]
This was due to a class loading sequence issue that has been fixed. 2.0.9 will be released today with this fix.

**Comment by joacovitale** [comment]
@digitalchild I did the update and it allows me to send the email manually now, but its not sent automatically like before when a purchase is made.

Thanks in advance.
