### ISSUE TITLE
my-account "become a vendor" tab is leading to a 404

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#447]
When using v2.0.9:  Even after saving permalinks, the "become a vendor" tab on the my-account page is leading to a 404 page not found.
This does not occur with v2.0.7

**Comment by digitalchild** [comment]
Does saving settings fix this?

**Comment by fervous** [comment]
Yes, It does.

**Comment by digitalchild** [comment]
rewrite rules need to be moved out of the class to fix init loading issues. @mahlamusa 

Anything with init needs to be loaded before the front end.

**Comment by fervous** [comment]
wc vendors v2.10.0
wc vendors pro v1.5.3

In my testing, the registered user who visits the "become a vendor" tab on the my-account page now leads to the checkbox to apply to become a vendor.... however, the (pending vendor) applicant is not directed to the application form as expected if WC Vendors Pro is active.  

The application is instead automatically submitted without the applicant being directed to the signup form.  The applicant sees the pending vendor submission confirmation and message.

Not sure if this is related to this issue:
https://github.com/wcvendors/wcvendors/issues/448

**Comment by digitalchild** [comment]
I'm unable to replicate this. If the users is pending and they click on 'become a vendor, it redirects them to the pro dashboard with the pending vendor notice' 

Using latest masters for both.

**Comment by mahlamusa** [comment]
I can't replicate this on two installs. If the user has not applied it redirects to the application form and if they have already applied it redirects to the page saying 'Your application has been received'

**Comment by fervous** [comment]
Ok I tested this again.. and I had the same results.
If (me) the registered non-vendor user visits the my-account page and clicks on the "become a vendor" tab, they are directed to the check boxes for "apply to become a vendor" and "terms & conditions".  ( first screenshot) 
I check these and hit submit.

After I hit submit, I am not directed to the Vendor Application.  I instead just receive the pending vendor notice. (second screenshot )

I am not sure why I am experiencing this but both of you are not.  It seems that it is behaving as if WC Vendors Pro is not active, but I have v1.5.3 active on the testing site.

![pendingvendor-from-my-account-link](https://user-images.githubusercontent.com/13291807/42251500-094e3b00-7ef5-11e8-958c-755b9b18a0ca.jpg)

![pendingvendor-from-my-account-link1](https://user-images.githubusercontent.com/13291807/42251503-0e604192-7ef5-11e8-9cd2-ae38d275def3.jpg)

**Comment by mahlamusa** [comment]
This has been addressed, if you get the current master branch you will not see this. I can't replicate this on 2.0.10 and pro 1.5.4

**Comment by digitalchild** [comment]
closing
