### ISSUE TITLE
Vendor Notify Order emails not firing

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#450]
Vendor notify order emails are not firing.

**Comment by joacovitale** [comment]
I am having this issue and been sending vendors notification manually

**Comment by digitalchild** [comment]
Error log on one install is saying  [26-Jun-2018 13:23:02 UTC] ERROR PostmanWpMail: Exception code=0 message=No recipient forward path has been supplied

**Comment by joacovitale** [comment]
It was working correctly on 2.0.7

When I updated it to the 2.0.8 it stopped working entirely and couldn't send mails manually either.

In the update 2.0.9 it started working the emails manually going to each order and choosing resend vendor notification, but after the purchase the emails to the vendors aren't sent automatically.

In the update 2.0.9 I don't get any error, the emails are just not sent. And in the update 2.0.8 I had the error  of this post https://github.com/wcvendors/wcvendors/issues/443 

And from the update of 2.0.0 the emails can't be translated for some reason, it changed completely.

**Comment by majidempire** [comment]
Email notifications stopped working after 2.0.9

**Comment by joacovitale** [comment]
@digitalchild  Hi, how can I access to the update with this fix?

Thanks in advance!

**Comment by digitalchild** [comment]
@joacovitale just doing some final testing and then we'll be pushing a new release in the next day or so.
