### ISSUE TITLE
Shipping cost to be added onto Vendor commissions

### ISSUE THREAD

**Issue by jsonUK** [wcvendors/wcvendors#463]
Hi,

Not sure where this should go.

We maintain a WCV + WCV Pro website. One of things we have to keep changing is adding the ability to give the Vendors the shipping cost as part of their commission.

The quickest and simplest way I have found is to alter 2 lines (but my guess is you will need to add a feature flag for it).

2 lines I have to keep altering are in these 2 files:

**classes/class-commission.php** line 219: (added total_shipping to the select clause)
```
$query      = "SELECT id, vendor_id, total_due, total_shipping FROM `{$table_name}` $where";
```

**classes/gateway/PayPal_Masspay/class-paypayl-masspay.php** line 59:
```
$due_amounts[ $data->vendor_id ][ ] = $data->total_due + $data->total_shipping;
```

I realise my changes may not in the right place for a feature, but they do give the correct pricing when our commission is due.

If you could turn it into a feature so I don't have to keep altering these lines, that would be great.

Thanks!

**Comment by jsonUK** [comment]
Hi,

I just realised you do have a feature for this in the WCV settings, but when testing, it never takes into account for PayPal MassPay.

Maybe the best thing to do is allow the **class-paypal-masspay.php** to check the variable?

Maybe something like this:
```
'yes' == get_option( 'wcvendors_vendor_give_shipping', 'no' )
```

**Comment by jsonUK** [comment]
Tested - my logic above works as expected. I hope you can put this change into you next release :)

**Comment by digitalchild** [comment]
This has been added.
