### ISSUE TITLE
[wcv_vendorslist]

### ISSUE THREAD

**Issue by tysonchamp** [wcvendors/wcvendors#464]
short code not showing up the vendor lists..

**Comment by digitalchild** [comment]
Do your vendors have products? by default the shortcode will not show any vendors if they don't have products. 

https://docs.wcvendors.com/knowledge-base/pages-and-shortcodes/ 

This outlines the options for the shortcode. Please provide details on how to replicate the issue.

**Comment by digitalchild** [comment]
@tysonchamp Please provide more information otherwise I will have to close this issue as it cannot be replicated in our test environments.

**Comment by tysonchamp** [comment]
It's done and sorry for late reply..

Thank you guys.
