### ISSUE TITLE
Capabilities resetting disables edit live products

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#466]
There has been 3 reports now of users having to re-save their capabilities settings after an update as the vendors ability to edit live products is reset. 

From the reporting user 

> Whenever plugin is updated, I have to go to “Settings->Capabilities” and resave “Permissions” for vendors.
> 
> In particular, my vendors are allowed to edit live products. Without resave, they cannot edit existing products until I press “Save changes” in the “General” tab of “Capabilities” (just pressing “Save changes” is enough, all the boxes are ticked properly).

**Comment by davidmasin** [comment]
Hi, here is my woocommerce status page associated with this issue. Thanks David
[WoocommerceStatus.pdf](https://github.com/wcvendors/wcvendors/files/2191344/WoocommerceStatus.pdf)
