### ISSUE TITLE
UI/UX Issues

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#47]
There are many inconsistencies in the current UI that is confusing and not aligned with standard wordpress UI interactions. 

There is a lot of work to be done around this area and I will start a full discussion on the forums regarding this.

**Comment by digitalchild** [comment]
Orders Page To Do: 

- [ ] Add shipping tracking support as per front end
- [ ] Add pagination support 
- [ ] Order note support

**Comment by archonic** [comment]
With the seller dashboard already available in the frontend, moving everything to the backend, while consistent, would anger more than a few people. Many people are installing plugins (WFSM for example) and making modifications to keep users on the frontend as much as possible. Just having everything on the frontend line up under "My Account" would be my vote. Have a link for the vendor dashboard, and a nav for the links within it.

**Comment by digitalchild** [comment]
The current front end code will not be touched however there are times when the consistency and extra plugins costs are a concern. These features will allow site admins an avenue for a consistent look and feel in the standard WordPress dashboard. The front end system currently requires that people spend money on a variety of extra plugins to get the complete front end dashboard experience. This is why we are building the Pro version. It extends the functionality to include a complete front end experience without the need of buying 2-3 extra plugins.

**Comment by archonic** [comment]
That's even better. I was wondering if Pro would cover a full frontend experience. WFSM took a lot of customizing and I ended up scrapping it and getting a refund. The JS in that plugin is a disaster. Thanks for the speedy response!
