### ISSUE TITLE
Add option to remove "Become a Vendor" tab on the my-account page

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#471]
A user has requested that an option be added for admin to choose not to display the "Become a Vendor" tab on the WooCommerce my-account page.

**Comment by fervous** [comment]
This option is working -- but opposite to what the selection indicates the action should be.

For instance, the description for the option says," Show the "Become a Vendor" link on WooCommerce my-account page ".

If the option box is ticked / checked, the become a vendor tab on the my-account page does **NOT** show.
If the option is not ticked / checked and left empty, the become a vendor tab on the my-account page **DOES** show.

So, either the description for the option needs to be changed or the action for the option needs to be reversed.

**Comment by mahlamusa** [comment]
https://github.com/wcvendors/wcvendors/pull/482
