### ISSUE TITLE
WC vendor Pro plugin issue

### ISSUE THREAD

**Issue by parmarhardip** [wcvendors/wcvendors#476]
Hello team,

I have used the latest version of woocommerce.

If I create one seller then added product after the product has sold then click to the order tab for checking order details I get an error on console.

Please refer URL: http://nimb.ws/t3rBC9

Thanks,

**Comment by digitalchild** [comment]
Please do not create issues for pro in our free repository. Please submit your issues here : https://www.wcvendors.com/submit-ticket/
