### ISSUE TITLE
Class 'WC_Background_Process' not found

### ISSUE THREAD

**Issue by msshohan** [wcvendors/wcvendors#477]
The latest version of WC Vendors plugin is returning the error, "Class 'WC_Background_Process' not found in \wp-content\plugins\wcvendors\classes\includes\class-wcv-background-updater.php on line 14"

Please fix the issue asap.
Thank you.

**Comment by digitalchild** [comment]
We are unable to assist or replicate this issue without feedback from you. I will close this issue. Pleas re-open it if you are able to provide the requested information.
