### ISSUE TITLE
Admin Notify email not firing from Become a vendor tab

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#486]
'Admin Notify Vendor Application' is not firing when a user becomes a vendor from 'Become a Vendor' tab.

**Comment by mahlamusa** [comment]
I can not replicate this. The email is firing. I have added debug log point to see where it fails, the email is firing properly. Maybe its not delivered due to some other issues.

**Comment by digitalchild** [comment]
Confirmed this email is firing on 2 installs. Closing.
