### ISSUE TITLE
[Pro?] -- Title on Product Archives

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#49]
Currently when you view a vendors page, it shows "Products Archive - Sitename" as the title of the page if you use WordPress SEO by Yoast, or "Products | Sitename" if using no SEO plugin.  Not really search engine friendly.

Change to "Vendor Store Name - Sitename" would be much more appropriate.

**Comment by Creativedot** [comment]
Add %%name%% under your product seo titles - like this

%%name%% %%pt_plural%% %%page%% %%sep%% %%sitename%%
![tilfoj designer navn under titles](https://cloud.githubusercontent.com/assets/9765767/5843569/b56b83da-a1ad-11e4-9eef-4a99c2a3d414.JPG)

**Comment by bentasm1** [comment]
Thanks, that's much easier. :)
