### ISSUE TITLE
Undefined variable: customer_name

### ISSUE THREAD

**Issue by felixhagspiel** [wcvendors/wcvendors#491]
Hello,

I just received this error when calling `$order->payment_complete()`:

```
= New Customer Order =

<br />
<b>Notice</b>:  Undefined variable: customer_name in <b>/var/www/wp/wp-content/plugins/wc-vendors/templates/emails/plain/vendor-notify-order.php</b> on line <b>19</b><br />
You have received an order from .

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


<h2>
	Order #78 (17. August 2018)</h2>

<div style="margin-bottom: 40px;">
	<table class="td" cellspacing="0" cellpadding="6" style="width: 100%; font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif;" border="1">
		<thead>
			<tr>
				<th class="td" scope="col" style="text-align:left;">Produkt</th>
				<th class="td" scope="col" style="text-align:left;">Menge</th>
						
			</tr>
		</thead>
		<tbody>
			<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/wp/wp-content/plugins/wc-vendors/templates/emails/vendor-order-items.php</b> on line <b>19</b><br />
		</tbody>
		<tfoot>
			<br />
<b>Notice</b>:  Object of class WCVendors_Vendor_Notify_Order could not be converted to int in <b>/var/www/wp/wp-content/plugins/wc-vendors/classes/includes/wcv-template-functions.php</b> on line <b>88</b><br />
<br />
<b>Notice</b>:  Object of class WCVendors_Vendor_Notify_Order could not be converted to int in <b>/var/www/wp/wp-content/plugins/wc-vendors/classes/includes/wcv-template-functions.php</b> on line <b>88</b><br />
<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function get_option() on string in /var/www/wp/wp-content/plugins/wc-vendors/classes/includes/wcv-template-functions.php:137
Stack trace:
#0 /var/www/wp/wp-content/plugins/wc-vendors/templates/emails/vendor-order-details.php(64): wcv_get_vendor_item_totals(Object(WC_Order), false, Object(WCVendors_Vendor_Notify_Order), '', true)
#1 /var/www/wp/wp-content/plugins/woocommerce/includes/wc-core-functions.php(210): include('/var/www/wordpr...')
#2 /var/www/wp/wp-content/plugins/wc-vendors/classes/admin/emails/class-emails.php(257): wc_get_template('emails/vendor-o...', Array, 'woocommerce', '/var/www/wordpr...')
#3 /var/www/wp/wp-includes/class-wp-hook.php(286): WCV_Emails-&gt;vendor_order_details(Object(WC_Order), false, true, Object(WCVendors_Vendor_Notify_Order))
#4 /var/www/wp/wp-includes/class-wp-hook.php(310): WP_Hook-&gt;apply_filters('', Array)
#5 /var/www/wp/wp-include in <b>/var/www/wp/wp-content/plugins/wc-vendors/classes/includes/wcv-template-functions.php</b> on line <b>137</b><br />
```

I think a simple check if customer_name is set should fix this.

**Comment by felixhagspiel** [comment]
Thanks for the quick reply.

Woocommerce Version 3.4.4
WC Vendors Version 2.1.0

I am executing the function when a custom webhook is called. The webhook is registered by  `rest_api_init` https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/`. Updating the order works anyway, but the rest-endpoint is returning a HTTP 500 / internal server error.
Is there any way to set the customer_name globally for the webhook call?

**Comment by digitalchild** [comment]
The customer name is populated when the email calls the action `wcvendors_email_customer_details` which parses the order and related information. The interesting thing is that your email template has html in it, yet its referencing the plain text email paths. 

Do you have your emails set to plain text or html? Because it looks like its trying to use a mixture of both. I've just double checked the latest code and I'm not entirely sure how you're getting that output at all. I would suggest trying this on the latest master branch and setting the emails to HTML first and then plain text. 

$order->payment_complete() starts the actions for triggering the emails and shouldn't matter if thats coming from the REST api or standard PHP code.

**Comment by felixhagspiel** [comment]
the woocommerce emails are all set to `text/plain`. I did not find any wcvendors specific settings for emails (I am not using the PRO version atm).
How do I set the emails as html? I did not change any settings regarding emails so far. Also, we are using regular PHPs `sendmail`. Could that be the problem as well?

**Comment by felixhagspiel** [comment]
okay, I fixed it. It was related to my server config. regarding to [this answer](https://stackoverflow.com/questions/30139808/woocommercewordpress-email-type-displaying-plain-text-instead-of-text-html) I had to install php-gd, php-xml and php-xmlrpc then restart my apache.
Thank you for your help!
