### ISSUE TITLE
Capabilities for backend vendor pages

### ISSUE THREAD

**Issue by Spreeuw** [wcvendors/wcvendors#496]
I was looking to hook into the bulk actions for the backend vendor pages but noticed that these are only available for vendors with the `manage_product` capability, which is not a standard capability for the Vendor role.
Source: https://github.com/wcvendors/wcvendors/blob/v2.1.0/classes/admin/class-vendor-admin-dashboard.php#L22-L24

Is there a specific reason for this? Why are the backend Vendor pages not available to all Vendors? checking [more of the code](https://github.com/wcvendors/wcvendors/blob/v2.1.0/classes/class-install.php#L155-L177) I think this should actually be enabled by default, but it's not?
In the setup wizard I believe I enabled all capabilities:
![wcvendors-wizard-caps](https://user-images.githubusercontent.com/3217773/45255451-ff004f00-b386-11e8-82ae-5347fff9bb10.png)
So perhaps it's just that this is wizard related?

Not sure if it's relevant but I created the vendor simply by setting an existing user to the Vendor role.

**Comment by digitalchild** [comment]
All vendors are assigned this capability. The only time this capability isn't added is if "Allow Vendors to add/edit products" (wcvendors_capability_products_enabled) capability isn't enabled in settings. If this hasn't been set then the role isn't updated to included this. You can see the default roles listed here: 

https://github.com/wcvendors/wcvendors/blob/v2.1.0/classes/class-install.php#L141-L179 

Is the wizard not setting these for some reason?

**Comment by Spreeuw** [comment]
> Is the wizard not setting these for some reason?

That appears to be the culprit indeed!

**Comment by Spreeuw** [comment]
> After you set the wizard does it set them?
'Them' being actual capabilities: no
'Them' being the capability settings in WC vendors: yes

I did a quick test on a clean install:

WC Vendors activated, no wizard:
![wcvendors-no-wizard-ran](https://user-images.githubusercontent.com/3217773/45262652-391b3080-b41b-11e8-8ac0-3582903ee6cb.png)

after wizard (all caps enabled during wizard):
![wcvendors-wizard-ran](https://user-images.githubusercontent.com/3217773/45262654-446e5c00-b41b-11e8-9627-c6cae7244e30.png)

after saving the caps settings:
![wcvendors-cap-settings-saved](https://user-images.githubusercontent.com/3217773/45262656-4c2e0080-b41b-11e8-8a66-7cc98e61ea3a.png)

**Comment by digitalchild** [comment]
Fixed: https://github.com/wcvendors/wcvendors/commit/bd435d22c194acd675cba55d1c0fd140bc6f4ae8 pull latest master and give that a crack

**Comment by digitalchild** [comment]
Actually completely fixed now as of https://github.com/wcvendors/wcvendors/commit/51a597dc185b1019d0f147f9fe4565504253beeb

**Comment by Spreeuw** [comment]
Awesome, thanks!
