### ISSUE TITLE
Commissions are calculated on integers

### ISSUE THREAD

**Issue by Niiicooo** [wcvendors/wcvendors#499]
Hello,

We use **WC Vendors** with **WooCommerce** and **Mangopay**.

Everything worked perfectly for the commissions until the day when, without any update of the plug-in (WC Vendor or other), WC Vendors no longer supported the numbers with commas in the commissions. For example, I pay 100% commissions, with a product at 29 € TTC, I had 24,17 € commission and 4,83 € tax _(with a 20% VAT)_. Now, for a product at € 29, I have € 24 commission and € 4 tax. The problem is that I miss 1 € in my transactions now.

The solution to the problem was found by modifying the function **insert_new_commission()** in the file **class-commission.php**

Indeed, in this function when calling the **insert()** and **update()** functions of WordPress (wpdb), no format is specified. Therefore, WordPress considers all fields as “string”, so it uses “%s” in the SQL statement before the “prepare()” function.

So I add a variable **$format** which simply modifies the formats of **total_due** and **tax** to consider them like float (“%f”):
`$format = array(“%s”, “%s”, “%s”, “%f”, “%s”, “%f”, “%s”, “%s”, “%s”);`

So I changed the call to both functions to use this variable:
`$update = $wpdb->update( $table, $order, $where, $format );`
`if ( !$update ) $insert = $wpdb->insert( $table, $order, $format );`

The final result here is as follows:
`$format = array(“%s”, “%s”, “%s”, “%f”, “%s”, “%f”, “%s”, “%s”, “%s”);`
`$update = $wpdb->update( $table, $order, $where, $format );`
`if ( !$update ) $insert = $wpdb->insert( $table, $order, $format );`

I doubt that this problem did not happen alone. It may be due to an update somewhere, or a configuration change. What I do know is that I have the same problem on two different environments, a PHP 7.0.x server and a PHP 5.6.x server.

Thank you

**Comment by r3gis3r** [comment]
Hi, 

It seems the actual commit doesn't exactly match database values. PR proposed to fix that.
