### ISSUE TITLE
Logout issues

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#500]
If WC Vendors > Settings > Display > Advanced Use WooCommerce Registration is enabled then when logging out the following error happens 

`Warning: call_user_func_array() expects parameter 1 to be a valid callback, class ‘WCV_Vendor_Shop’ does not have a method ‘redirect_after_logout’ in /wp-includes/class-wp-hook.php on line 286`

This is because `redirect_after_logout ` does not exist. It appears this method was removed at some point?

**Comment by CasperBraske** [comment]
Actually, the hook was **added** in the last commit as well as other [hooks and their respective methods](https://github.com/wcvendors/wcvendors/commit/a451eab96d19f0c0c2473bb70c5ef8f19a5df807#diff-2b8e2d3444733a2e49e61ce48551d9c3R47).
They forgot to add that method.

**Comment by CasperBraske** [comment]
Just a typo:
https://github.com/wcvendors/wcvendors/commit/a451eab96d19f0c0c2473bb70c5ef8f19a5df807#diff-2b8e2d3444733a2e49e61ce48551d9c3R389
