### ISSUE TITLE
Duplicating orders after update Woocomerce 3.5.1

### ISSUE THREAD

**Issue by fun99** [wcvendors/wcvendors#503]
I am using wc vendors marketplace for some reason I’m getting duplicate orders only when wc vendors marketplace. Once wc vendors marketplace is deactivated, the duplicate orders disappears.

 I’ve switched to the storefront theme and deactivated all other plugins and nothing happened.
This shows only on, my-account/orders page and on the customer’s end only. the duplicated orders does not show in the backend.

**Comment by fervous** [comment]
I have confirmed this issue using WC Vendors Marketplace v2.1.2 and WooCommerce v3.5.1

my-account/orders
The customer sees duplicate lines on the orders page.. orders are duplicated on the screen.

**Comment by mahlamusa** [comment]
@fervous May I have the steps to replicate this issue as I can't replicate it currently. I tried placing new orders and changing order statuses and I only see the original order, no duplicates. Are there any steps you follow to replicate this?

**Comment by fervous** [comment]
@mahlamusa It appears that the duplicate orders are happening to the older orders, not new orders.  Do you have an install setup that has orders form before mid-September?  
When I view the customer's my-account/orders page, the new orders are not duplicated, but the older orders are duplicated.  Perhaps this will help with debugging.. Please see my screenshot:
![duplicate-orders](https://user-images.githubusercontent.com/13291807/48233079-236dad00-e371-11e8-8837-e16a0a4d00c9.jpg)

**Comment by fun99** [comment]
But in my case only new orders making duplicate not old orders.

**Comment by mahlamusa** [comment]
I have no luck with this so far. I have tried on an old install with orders from June, I don't see any duplicates. I tried this with the version before 2.0.2 and then updated to 2.0.2 and still no luck. @fun99 & @fervous , does this happen after you perform a specific action on the order or it just happens for all orders?

**Comment by fun99** [comment]
@mahlamusa which version of Woocommerce you are using? Its happening me on new orders only.

**Comment by mahlamusa** [comment]
I have WooCommerce 3.5.1, WC Vendors Marketplace 2.1.2, on WordPress 4.9.8.

**Comment by mahlamusa** [comment]
@fun99 could you also share a screenshot highlighting the duplicate orders, also share as much information as possible about your setup. You can get more from 'WooCommerce > Status'

**Comment by fervous** [comment]
@mahlamusa  I had to set up a new testing environment, and I cannot replicate this issue any longer.  I have tried to re-create it, and now I cannot.  I do believe it was happening on my previous install, but I am unable to recreate this again.

**Comment by digitalchild** [comment]
I have tried on 6 different installs going from WC3.3 - > WC3.5.1 / WC3.4 - WC3.5.1 and I am unable to replicate this. Does this happen with 3.5.0? or ONLY 3.5.1 ? 

Can you provide screen shots @fun99 ?

**Comment by fun99** [comment]
@digitalchild, @fervous , I think no issue in woocommerce 3.5.1 it was issue in 3.5.0

**Comment by digitalchild** [comment]
@fun99 Good to hear, seems there was a glitch. closing.
