### ISSUE TITLE
Vendor New Order email: Billing name is shown instead of Shipping name

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#509]
Vendor receives New Order email with wrong name shown under Shipping Address (Billing name is shown instead of Shipping name).
ACTIONS TO REPLICATE:
- Add item to basket and go to checkout
- On checkout page, change the First/Last Name in the Shipping Address to be different to Billing name.
- Place order

FILES
- wc-vendors/templates/emails/vendor-order-addresses.php (Line 48)
- wc-vendors/templates/emails/plain/vendor-order-addresses.php (Line 39)

In the Shipping Address section of the email, both templates use the $customer_name variable generated in wc-vendors/classes/admin/emails/class-emails.php and derived from $order->get_formatted_billing_full_name()

However, for the vendor notification emails Shipping Address section, we should be using $order->get_formatted_shipping_full_name() as the Shipping Address can be different to the Billing Address.

**Comment by mahlamusa** [comment]
Addressed here: https://github.com/wcvendors/wcvendors/pull/511
