### ISSUE TITLE
Multisite compatiability

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#51]
When network enabling woocommerce on a multisite install, WC Vendors doesn't activate. Will need to investigate how multisite works and how it differs. 

We do detect if multisite is active and then merge our options however we might need to do more than this to have WC V play nicely in this environment. 

https://github.com/wcvendors/wcvendors/blob/master/WCVendors/classes/includes/class-dependencies.php#L21

More work required on this.

**Comment by jetlej** [comment]
Please make this a priority!

**Comment by Webnik** [comment]
I'll second that. Please make this a priority!

Hopefully there is a way around WooCommerce not playing nice with Multisite for WCV.

**Comment by bentasm1** [comment]
Since WC Vendors Pro offers mulitisite compatibility, closing this issue.

https://www.wcvendors.com/product/wc-vendors-pro/

Cheers

chCBen
