### ISSUE TITLE
Email details incorrect when Manually approved unchecked. 

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#520]
I have unchecked ‘Manually approve all store applications’ but the emails being sent to Admin now shows a pending status of the vendor, with a link to approve or deny the vendor. when I click on the link, it says ‘No users found’ but that user has already become a vendor.

**Comment by dinhtungdu** [comment]
Can't reproduce this issue.

**Comment by malavikaprav** [comment]
Email is not firing at all now after recent update.
