### ISSUE TITLE
Commisions are not calculating multiple of the same item

### ISSUE THREAD

**Issue by Josephthecodeacrhitect** [wcvendors/wcvendors#530]
Notice in this image for this order I have 2 items but with a quantity of 3 [http://kot90.altervista.org/survius/img/JzMmkCKTOv](http://kot90.altervista.org/survius/img/JzMmkCKTOv)

And within the commissions tab it is only showing the 2 items disregarding the quantity entirely [http://kot90.altervista.org/survius/img/HqcoS8sN8w](http://kot90.altervista.org/survius/img/HqcoS8sN8w)

Major bug needs to be fixed

**Comment by digitalchild** [comment]
Can we get details on the commissions that you're using? The commission table doesn't show the quantity but the commission totals do use the qty in the calculation.

**Comment by digitalchild** [comment]
Closing due to no response from reporter
