### ISSUE TITLE
Add Gulp task to update new strings from POT file to PO files

### ISSUE THREAD

**Issue by dinhtungdu** [wcvendors/wcvendors#533]

**Comment by CasperBraske** [comment]
Why not use WP CLI?
https://github.com/wp-cli/i18n-command

**Comment by digitalchild** [comment]
@CasperBraske it's easier as part of our build process. We already use gulp's wpPot to create it, this is to update all existing Po's as we have people translating other languages we ship but they aren't syncing them with the base file first. This will reduce the translation issues we've been seeing.

**Comment by CasperBraske** [comment]
Yes, I remember you showed me that Gulp task. After some time it was causing me too many troubles and I gave up translating for a while.

Haven't you guys set up the translation env in WordPress' translation service? I thought the translation service moved there and even offered myself to manage the translations to PT-BR if I'm not mistaken.

**Comment by digitalchild** [comment]
Closing in favour of having people send to translate.wordpress.org
