### ISSUE TITLE
Vendor Notify Order not showing customer name / address

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#534]
I have received several reports of the Vendor Notify Order email not showing the customer's name and/or complete customer information-- any customer details at all, in one case.

I have not replicated this yet, but since there is more than one report I wanted to open an issue so this can be investigated.

I will setup a new live site rather than local site so I can try to replicate this.

![notify-vendor-order-email](https://user-images.githubusercontent.com/13291807/51995625-48edec80-2470-11e9-9209-b364d82a29f8.png)

**Comment by digitalchild** [comment]
This happens when using the BACS gateway only. closing
