### ISSUE TITLE
Email Issues 

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#559]
Vendor Notify Order 

- [ ] In some environments this is not being triggered, does work on our demo system 
- [x] Customer shipping name view does not work if this is the only option shown 
- [x] Custom address formatting is incorrect for shipping address. The customer name is left outside of the address tags. 
- [x] **Fatal error when Email type set to Plain text.**

![WP_Mail_Log_‹_WC_Vendors_-_Demo_Site_—_WordPress](https://user-images.githubusercontent.com/909468/57208062-d145d580-6ffb-11e9-8aeb-9cc4fae4b11c.jpg)

**Comment by dinhtungdu** [comment]
> In some environments this is not being triggered, does work on our demo system

We need to test on those environments or ask them to install [this plugin](https://vi.wordpress.org/plugins/wp-mail-logging/) to check if the emails actually work. This problem usually occurs due to server/hosting mail config.

**Comment by dinhtungdu** [comment]
> Customer shipping name view does not work if this is the only option shown

How to reproduce this issue?
