### ISSUE TITLE
Multi role issue - customer role still the primary role after vendor approval

### ISSUE THREAD

**Issue by MarkKevin08** [wcvendors/wcvendors#563]
Describe the bug : After vendor's approval, it seems that the primary role is still set to  "Customer" 

To Reproduce Steps to reproduce the behavior:

Go to "my-account" and register as a vendor.
Check the vendor's application in WP dashboard >> users
Role is set to Customer, Pending Vendor
Approve the application, role is still set as Customer, Vendor
See error
https://cl.ly/e3d96b663180

Expected behavior : Customer role should be removed or Vendor role should be the primary role.

Isolating the problem (mark completed items with an [x]):

 I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
 This bug happens with a default WordPress theme active, or Storefront.
 I can reproduce this bug consistently using the steps above.

**Comment by digitalchild** [comment]
Need to remove the customer role only after approval. 

If the vendor is denied then the pending_vendor role is removed, but their existing role is left instead of using the default role for WordPress (current behaviour).

**Comment by digitalchild** [comment]
We will also need an update tool to go through all vendors that have the vendor AND customer role and remove the customer role only. Leave all other roles alone.
