### ISSUE TITLE
An option/setting for a/an labels

### ISSUE THREAD

**Issue by MarkKevin08** [wcvendors/wcvendors#567]
Related to this ticket a support ticket request. 

The user mentioned : 
> it shows as become "a" artist instead of become "an" artist. How can I make "a" to "an"

An option to provide them to change this as well will be good. Thanks!

**Comment by dinhtungdu** [comment]
@MarkKevin08, We have a filter to change that information: `wcv_become_a_vendor_string`

You can change it by adding this piece of code:
```
add_filter( 'wcv_become_a_vendor_string', function() {
	return array(
		'become-a-vendor' => sprintf( __( 'Become an %s', 'wc-vendors' ), wcv_get_vendor_name() ),
	);
} );
```

**Comment by digitalchild** [comment]
I think this is a better solution then adding even more labels to the backend. I'll add this to the snippets on docs.
