### ISSUE TITLE
Double order creation

### ISSUE THREAD

**Issue by Praanshu** [wcvendors/wcvendors#580]
Hi, 
I am using WC vendors for my marketplace but the when a customer orders, there are 2 order ids generated from a single transaction. One with shipping which is either processing/failed and another without shipping that says complete.

Please help me out asap.

Automatic new completed order generated for only vendor items seperately

![Annotation 2019-07-31 144229](https://user-images.githubusercontent.com/18312367/62199692-9c9aad80-b3a1-11e9-9ecf-e598a29673ce.jpg)
.

**Comment by digitalchild** [comment]
Are you able to provide any debugging for this?

**Comment by digitalchild** [comment]
As you have not provided any more details and we cannot replicate this, I'll be closing this for now. Please reply with more details and how to replicate it as per our submission requests.
