### ISSUE TITLE
"Sold By" label's colon spacing is not same for the archive pages and order page

### ISSUE THREAD

**Issue by MarkKevin08** [wcvendors/wcvendors#597]
**Describe the bug**
There is no space for some of the pages like the archive page(product category page).
and for the Order page, where the colon is double like so: https://cl.ly/1d37b95f4aa5

**To Reproduce**
1. Go to an archive page, a category page for example
2. check the Sold by label:
3. You can see the difference from the shop page as the Sold by label should be something like so: "Sold by: Vendor name"

In the Orders page:
1.) Go to Orders tab and see the "By::" label

**Screenshots**
"Sold by Label" - https://cl.ly/050043bd7cef
"By::" label : https://cl.ly/1d37b95f4aa5

**Expected behavior**
"Sold By:" label should have space like the ones in the product single page - https://cl.ly/fb8e332719ad
"By::" label should only have one colon symbol ":"

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WC Vendors and WooCommerce are active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by digitalchild** [comment]
@MarkKevin08 I'm not seeing this By:: output on any of my installs. Can you provide me a demo that can show this?
