### ISSUE TITLE
Front-end issues with View Order Notes option

### ISSUE THREAD

**Issue by poojasolanki3272** [wcvendors/wcvendors#598]
**Describe the bug**
On the capabilities tab, there are multiple options but one of the options named View Order Notes is not working properly whether it's Enabled or Disabled not change anything at the front end

**WCVendor settings > capabilities ( Tab ) >  View Order Notes.**

**Screenshot :** 

![image_2019_11_21T06_15_55_612Z](https://user-images.githubusercontent.com/40519642/69347921-542e3500-0c9b-11ea-9950-1ff8e4b154d4.png)
![image_2019_11_21T14_35_48_439Z](https://user-images.githubusercontent.com/40519642/69347923-542e3500-0c9b-11ea-9fe4-a5d90514214b.png)
![image_2019_11_21T14_42_02_066Z](https://user-images.githubusercontent.com/40519642/69347924-54c6cb80-0c9b-11ea-8e1c-0a2ca0d20b10.png)

Please check Screenshot above and find the location of the settings and the option plugin 

**Video :** 

[VIdeo link ](https://we.tl/t-7tRqckRVY5)

**Expected behavior**
While we check the option, the order notes should be added to the front end of the vendor and the unchecked order notes should be hidden.

**Comment by digitalchild** [comment]
This will be addressed in the coming update.
