### ISSUE TITLE
Front-end issues For Edit Approved Product. ( WC Vendors Pro )

### ISSUE THREAD

**Issue by poojasolanki3272** [wcvendors/wcvendors#600]
**Describe the bug**
On the capabilities tab, there are multiple options but one of the options named Edit Approved Product. is not working properly whether it's Enabled or Disabled not change anything at the front end

**WCVendor settings > capabilities ( Tab ) >  General.**

** Screenshot:** 
![edit-approved-product](https://user-images.githubusercontent.com/40519642/69546792-691c0880-0fba-11ea-8aca-318f2665f5e0.png)
![image_2019_11_25T13_51_28_995Z](https://user-images.githubusercontent.com/40519642/69546793-691c0880-0fba-11ea-9222-ac8a3bc03753.png)

Please check Screenshot above and find the location of the settings and the plugin option 

**Expected behavior**
While unchecking the option, the user should not be able to modify the product after it has been approved.

**Comment by digitalchild** [comment]
With pro, users cannot access the wp-admin and we do not check this. This is a frontend pro dashboard feature only.
