### ISSUE TITLE
When the marketplace is set to manually approve accounts, accounts that are created and that applied for a vendor role does not seem to have a pending vendor role when viewed from the user dashboard and admin cannot see the option to approve the user as a vendor

### ISSUE THREAD

**Issue by junenacpil29** [wcvendors/wcvendors#642]
Details removed.

**Comment by junenacpil29** [comment]
Ticket reference - https://secure.helpscout.net/conversation/1122955791/7781/

**Comment by digitalchild** [comment]
This user still has other marketplace plugins installed. This cannot be replicated in any of our installs. Until they completely clear out their database we cannot support it.
