### ISSUE TITLE
Vendor search is not working as expected

### ISSUE THREAD

**Issue by jraborar** [wcvendors/wcvendors#672]
**Describe the bug**
The name can be filtered in the search box but it does not yield the result

**To Reproduce**
1. Go to WordPress Dashboard
2. Click on Products.
3. Look for the vendor filter, type the name and you'll in the search box that it filters but results are incorrect

**Screenshots**

**Expected behavior**
After you type the filter the list will be updated based on the criteria

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WC Vendors and WooCommerce are active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [XI can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by digitalchild** [comment]
Fixed in PR #679
