### ISSUE TITLE
Search by using SKU not working when WC Vendors Marketplace is active

### ISSUE THREAD

**Issue by MarkKevin08** [wcvendors/wcvendors#677]
**Describe the bug**
When I have WC Vendors activated I can’t search my products (in the admin area) by SKU. As soon as I deactivate it, that functionality is restored.

**To Reproduce**
1. Edit a product and an SKU to it
2. As an admin try searching for it while WC Vendors Marketplace is active, see error.
3. Deactivate marketplace and search the SKU again in the product search and it will return a result

**Screenshots**

**Expected behavior**
Products with SKU should be shown when searched by their SKU

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WC Vendors and WooCommerce are active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by digitalchild** [comment]
Fixed in this PR https://github.com/wcvendors/wcvendors/pull/679
