### ISSUE TITLE
Pagination on Commission pages when month is selected

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#68]
http://www.wcvendors.com/help/topic/bug-viewing-commissions-in-admin/

Steps to recreate the problem:

View commissions
Set month dropdown to any month
Click page 2.

By using the pagination it removes the month filter and shows page 2 of all commissions, instead of page 2 of the selected months commissions.

**Comment by digitalchild** [comment]
This bug was fixed in this commit ef19767b8e8b578f4a397d1abc49c97a6b0d9810 can you confirm @bentasm1

**Comment by bentasm1** [comment]
@digitalchild Fix does not work.

Tested on dev by selecting January for commissions, then page 2, which then shows February.
