### ISSUE TITLE
Become a vendor endpoint breaks WPML

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#693]
**Describe the bug**
When WPML is activated and there are secondary languages our add_rewrite_endpoint call in the main plugin file is stopping the WPML endpoints from working on the WooCommerce endpoints. 

**To Reproduce**
1. Install and configure all the plugins for WPML and WooCommerce WPML
2. Add a second language and define the endpoints for these
3. Go to my-account page in one language, then switch to another and try and click on any of the sub menu items.
4. The page just reloads and doesn't load the relevant translated endpoint. 

**Expected behavior**
All endpoints should work. 

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WC Vendors and WooCommerce are active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by ketulsheth85** [comment]
@digitalchild 
I want **WPML** plugin if you have or in dropbox. So, that I can download that and check for the issue.

**Comment by ketulsheth85** [comment]
Initially, the page was not working but after setting the slug for that page for another language its start working.

**Comment by digitalchild** [comment]
Can you explain what you mean by this @ketulsheth85 do we need to add documentation and not a fix?

**Comment by ketulsheth85** [comment]
For this, I've created one document. But need to re-right a little professionally.
[wpml-document.docx](https://github.com/wcvendors/wcvendors/files/5528365/wpml-document.docx)

**Comment by digitalchild** [comment]
This is documentation related, closing.
