### ISSUE TITLE
Add Vendor name to search query

### ISSUE THREAD

**Issue by HebaFareed** [wcvendors/wcvendors#695]
I want to add searching by vendor/store name to my search form, but the issue that there's only vendor id in the posts meta keys. How can I add vendor's name to search?

**Comment by HebaFareed** [comment]
Hi, is there any feedback? This issue is affecting my work.

**Comment by digitalchild** [comment]
Hi @HebaFareed , sorry about that, seems we missed this one! Which search are you referring to?

**Comment by digitalchild** [comment]
Hi @HebaFareed Can you please give us more details about which search you're referring to?
