### ISSUE TITLE
WooCommerce CSV Import does not work when WC Vendors Marketplace is active

### ISSUE THREAD

**Issue by MarkKevin08** [wcvendors/wcvendors#699]
**Describe the bug**
There was a report previously where the import does not work and I was able to replicate this  from my end - https://share.getcloudapp.com/p9uwrYEX

**To Reproduce**
1. Create a product CSV
2. Import it to a site where WC Vendors Marketpace is active
3. See error where the message is successful but no products were added

**Screenshots**
https://share.getcloudapp.com/p9uwrYEX

**Expected behavior**
Imported product should be accessible even WC Vendors marketplace is active.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WC Vendors and WooCommerce are active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by digitalchild** [comment]
Import / export code was re-enabled in 2.2.3 which was released last week.
