### ISSUE TITLE
Update vendor drop downs place holder

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#701]
**Is your feature request related to a problem? Please describe.**
The vendor drop downs say -- no change -- This isn't easy to understand. 

**Describe the solution you'd like**
Change this to Search vendors

**Comment by ketulsheth85** [comment]
@digitalchild 
Can you please give more information on this issue as to where it's coming?

**Comment by digitalchild** [comment]
This is a usability issue and we also check for these in the vendor search dropdowns. 

On the Product Page, the filters aren't intuitive. We have had several users report that the 'search for vendors has disappeared' 

![Products_‹_Test_—_WordPress](https://user-images.githubusercontent.com/909468/98077989-cb0c1000-1ea3-11eb-9f8e-fc901e263e59.jpg)
