### ISSUE TITLE
Reports not showing shipping or tax

### ISSUE THREAD

**Issue by sccr410** [wcvendors/wcvendors#72]
Looking at the "Commission by [Vendor or Product]" report, it doesn't show the tax or shipping collected. This just started in the most recent update, previously was working fine.

**Comment by sccr410** [comment]
Actually we were still on 1.2, just updated to 1.3.1 and that didn't help.

**Comment by sccr410** [comment]
Looking in the commission database table, looks like shipping is not being saved on all new orders

**Comment by sccr410** [comment]
Looks like when we switched to using the Table Rate Shipping plugin it no longer works. This is a commonly used plugin that should be supported.

**Comment by sccr410** [comment]
I am still digging, looks like all shipping prices are suddenly going to the store owner and not the vendor

**Comment by sccr410** [comment]
Holy cow, trying to add support for Table Rate Shipping looks daunting, maybe this is why support was removed by Matt way back when.

**Comment by bentasm1** [comment]
Keep digging!  This one is a curious nut to crack. ;)

**Comment by sccr410** [comment]
Ya this is over my head - I can't quite figure this out.

**Comment by darlaburns** [comment]
Has this issue been looked at.  I'm having same problem.  When buyer purchases something from a vendor, the shipping is going to the store owner even though in WC Vendors settings, the "Give Vendors any shipping collected per-product" is checked.  Tested through Sandbox at Paypal and indeed the shipping and commission is going to the store owner.

**Comment by bentasm1** [comment]
darla:  You need WooThemes Per Product Shipping.  It will not give vendors the flat rate or international shipping from the shipping modules included free with WooCommerce.  The Shipping Per Product plugin will handle this for you. :)

Once installed, also make sure that in the WC Vendors settings you have the box checked to give shipping to vendor.

Cheers,

Ben

**Comment by darlaburns** [comment]
Thank you so much.

**Comment by digitalchild** [comment]
@sccr410 I have done a bit of work getting shipping and taxes working and going to vendors correctly. Has this got the reports working now?

**Comment by sccr410** [comment]
That is awesome to hear. Unfortunately my client has basically stopped managing their site and so I don't have any more data to check on.

**Comment by digitalchild** [comment]
closing due to lack of reports
