### ISSUE TITLE
[QUESTION] How to show Payment Tab in settings?

### ISSUE THREAD

**Issue by ggoldani** [wcvendors/wcvendors#723]
**Describe the bug**
I cannot access payment tab in the settings and also i cannot find how to make the payments to vendors.

**Screenshots**
![image](https://user-images.githubusercontent.com/70818371/102272702-ef75f600-3eff-11eb-8136-9f2f79f87c68.png)

**Expected behavior**
I was expecting to find the PAYMENT button and the Payment Tab Settings.

**WordPress Environment**
<details>
```

Versão do WooCommerce: |   | 4.8.0
Pacote do WooCommerce REST API: |   | 4.8.0 
Pacote WooCommerce Blocks: |   | 3.8.1 
Pacote do agendador de ações: |   | 3.1.6
Pacote do WooCommerce Admin: |   | 1.7.3
Diretório gravável de registros: |   | 
Versão do WordPress: |   | 5.6
WordPress multisite: |   | –
Limite de memória do WordPress: |   | 256 MB
Modo de depuração do WordPress: |   | –
WordPress cron: |   |  
Idioma: |   | pt_BR
Cache de objeto externo: |   | –


```
</details>

**Comment by digitalchild** [comment]
The payment tab was removed in our last release as this was only relevant to a deprecated payment system from PayPal Adaptive payments. All payments are handled either on WooCommerce payment gateway settings pages or on the specific settings pages for vendor payout plugins.
