### ISSUE TITLE
Order total incorrect in vendor order emails when coupon is used

### ISSUE THREAD

**Issue by ketulsheth85** [wcvendors/wcvendors#726]
**Describe the bug**

As checked, when a customer creates an order using a coupon, in this example, 100%, the total is still displaying the full amount of the total price - https://share.getcloudapp.com/d5upB7yj

Product Total should now be displayed as $0.00, this would make sure that the vendor would not make expectation that they should receive a commission as the vendor coupon was used for the purchase.

**To Reproduce**
1.) create a vendor coupon
2.) Use it for an order
3.) see the product total

**Screenshots**
https://share.getcloudapp.com/d5upB7yj
 - There's also nothing for the new-order mail that says the customer used the coupon.

**Expected behavior**
Product total should be 0 as well.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WC Vendors and WooCommerce are active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by bdesai1982** [comment]
Not fixed - https://prnt.sc/10baopc Still the Vendor does not view the Product Total as Zero in the mail.

**Comment by bdesai1982** [comment]
@ketulsheth85 - I have gone through the option of "After" for commission and with the "After" option set, the commission is displayed zero in the Vendor mails as well - https://prnt.sc/10fx0m6
