### ISSUE TITLE
Vendor-wise shipping - Weight Range selection is not available

### ISSUE THREAD

**Issue by nikhilbhalwankar** [wcvendors/wcvendors#732]
I am trying out 3 days online demo version of WCVendors Pro version. I could see the vendor wise shipping options available. However in the table rate, there is no option to choose weight range. Most of the courier companies charge based on zip code and weight ranges both.

What can be done in such case? Is there any seperate extension available to attach to WCVendors Pro for this?

**Comment by digitalchild** [comment]
Our built-in table rate shipping currently does not include weight. There are 3rd party shipping plugins that support this available under the compatible plugins page on our website. 

https://www.wcvendors.com/home/compatible-plugins/
