### ISSUE TITLE
Vendor page is distorted on RTL

### ISSUE THREAD

**Issue by 123Check** [wcvendors/wcvendors#738]
**Describe the bug**
![wpmlarabic](https://user-images.githubusercontent.com/33170267/108672283-d5602180-7507-11eb-870f-53587b4f2d81.png)
![wpmleng](https://user-images.githubusercontent.com/33170267/108672290-d729e500-7507-11eb-96c6-b235e5a14d4b.png)

Vendor page breaks on RTL

can you please assist works fine in english.

**Comment by digitalchild** [comment]
Hello, this is not our dashboard. You would need to contact the developer who built that dashboard.
