### ISSUE TITLE
Add shipped column to admin dashboard's commission table

### ISSUE THREAD

**Issue by MarkKevin08** [wcvendors/wcvendors#740]
Is your feature request related to a problem? Please describe.

Admins would like to know if an order has been shipped before paying out the commissions. Add a shipped column to the commission's table. 

![download](https://user-images.githubusercontent.com/49851476/109377828-c06cff00-7908-11eb-8bf1-e2d7d1daab9a.png)

Describe the solution you'd like
Add a column that shows if the product has been shipped.

**Comment by digitalchild** [comment]
There are already filters in the table class to hook into these. So we can provide a snippet for this. However, I think their request to also list 'shipped' would be a good idea.
