### ISSUE TITLE
Translation for the strings "Apply to become a vendor" and " I have read and accepted the terms and conditions" not working using LocoTranslate 

### ISSUE THREAD

**Issue by MarkKevin08** [wcvendors/wcvendors#742]
**Is your feature request related to a problem? Please describe.**
As I checked, I was able to confirm that the translation for the strings "Apply to become a vendor" and " I have read and accepted the terms and conditions" are not working while using LocoTranslate.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Here's a test done through LocoTranslate:
![image](https://user-images.githubusercontent.com/49851476/111256087-3f756d80-8653-11eb-8189-48d157a0e066.png)

**Comment by digitalchild** [comment]
This is the incorrect string to translate the correct string is "Apply to %s %s" the second half, become a vendor is a label found under Display > Label - Become a vendor label. 

<img width="457" alt="My_account_–_WC_Vendors_Test" src="https://user-images.githubusercontent.com/909468/112302062-33ca1c80-8ccd-11eb-84c0-97306b3c79be.png">


The terms and conditions can also be translated. You must translate both strings listed. 

<img width="1367" alt="Editing_wc-vendors-en_US_po_in_WC_Vendors_Marketplace_‹_Plugin_translations_‹_Loco_‹_WC_Vendors_Test_—_WordPress" src="https://user-images.githubusercontent.com/909468/112301896-03827e00-8ccd-11eb-87af-c47bd2b02c3c.png">
