### ISSUE TITLE
Delete commission rows

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#762]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to remove a commission from the commission's table. 

**Describe the solution you'd like**
Add the ability to delete a commission from the table. 

** Requirements ** 

- [ ] add a bulk action to be able to remove multiple commissions
- [ ] add a row action to delete a single commission 

Both of these actions should have a confirmation before deleting.

**Comment by Mrlunsuper** [comment]
Steps to resolve the issue:
- Add delete row action
- Add delete bulk action
- Add confirm page to confirm delete action or we can use dialog
- Delete row using wp_db
That's all. Please tell me if you have an idea

**Comment by digitalchild** [comment]
@Mrlunsuper The confirmation doesn't have to be a page, it can be a javascript check that is a confirm on click.

**Comment by Mrlunsuper** [comment]
Oh. I will use Javascript way. Thank you!
