### ISSUE TITLE
Wordpress REST API (Pages asset) & WC Vendors Marketplace

### ISSUE THREAD

**Issue by loicpavard** [wcvendors/wcvendors#763]
**Describe the bug**
At https://mercadify.es, I am facing an issue on one particular aspect of wordpress REST API: pages connectivity.
The REST API seems to be working properly on posts, categories, users, etc…
On pages ressources, REST API will answer properly until 15 “pages” per page return.
But REST API throws systematically an error above 15 pages “per page”.

**To Reproduce**
You can test yourself any REST API URL like the following:
– POSTS:
https://mercadify.es/wp-json/wp/v2/posts?per_page=20 is OK
https://mercadify.es/wp-json/wp/v2/posts?per_page=30 is OK
– CATEGORIES:
https://mercadify.es/wp-json/wp/v2/categories?per_page=50 is OK
– PAGES:
https://mercadify.es/wp-json/wp/v2/pages?per_page=10 is OK
https://mercadify.es/wp-json/wp/v2/pages?per_page=15 is OK
https://mercadify.es/wp-json/wp/v2/pages?per_page=16 is throwing a critical error
BUT https://mercadify.es/wp-json/wp/v2/pages?per_page=20 is throwing a critical error
etc... Any number above 15 pages per page will throw a critical error

**Expected behavior**
REST API request should be returning wordpress assets as for any other API request.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated WC Vendors Marketplace and the error disappeared

**WordPress Environment**
### WordPress Environment ###

WordPress address (URL): https://mercadify.es
Site address (URL): https://mercadify.es
WC Version: 5.3.0
REST API Version: ✔ 5.3.0
WC Blocks Version: ✔ 4.9.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.2.6
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.16
PHP Post Max Size: 20 MB
PHP Time Limit: 180
PHP Max Input Vars: 4000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.38-MariaDB
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.3.0
WC Database Prefix: wc_
Tamaño total de la base de datos: 339.84MB
Tamaño de los datos de la base de datos: 206.44MB
Tamaño del índice de la base de datos: 133.40MB
wc_woocommerce_sessions: Datos: 3.02MB + Índice: 0.05MB + Motor InnoDB
wc_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wc_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wc_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wc_woocommerce_order_items: Datos: 0.50MB + Índice: 0.17MB + Motor InnoDB
wc_woocommerce_order_itemmeta: Datos: 8.52MB + Índice: 4.03MB + Motor InnoDB
wc_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wc_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wc_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wc_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wc_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wc_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wc_actionscheduler_actions: Datos: 2.52MB + Índice: 1.17MB + Motor InnoDB
wc_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wc_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wc_actionscheduler_logs: Datos: 1.52MB + Índice: 0.78MB + Motor InnoDB
wc_activecampaign_for_woocommerce_abandoned_cart: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
wc_cli_scripts: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_cmplz_cookiebanners: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_cmplz_cookies: Datos: 0.09MB + Índice: 0.00MB + Motor InnoDB
wc_cmplz_services: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_commentmeta: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wc_comments: Datos: 0.38MB + Índice: 0.42MB + Motor InnoDB
wc_e_submissions: Datos: 0.02MB + Índice: 0.27MB + Motor InnoDB
wc_e_submissions_actions_log: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
wc_e_submissions_values: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wc_jet_post_types: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_jet_taxonomies: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wc_litespeed_img_optm: Datos: 0.44MB + Índice: 0.18MB + Motor MyISAM
wc_litespeed_img_optming: Datos: 0.34MB + Índice: 0.22MB + Motor InnoDB
wc_mailchimp_carts: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_mailchimp_jobs: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_ms_snippets: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_options: Datos: 10.22MB + Índice: 0.50MB + Motor InnoDB
wc_postmeta: Datos: 12.52MB + Índice: 12.03MB + Motor InnoDB
wc_posts: Datos: 3.50MB + Índice: 0.89MB + Motor InnoDB
wc_ppress_forms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wc_ppress_formsmeta: Datos: 0.06MB + Índice: 0.05MB + Motor InnoDB
wc_ppress_meta_data: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wc_pprh_table: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_pv_commission: Datos: 0.14MB + Índice: 0.00MB + Motor InnoDB
wc_rank_math_analytics_gsc: Datos: 1.52MB + Índice: 2.30MB + Motor InnoDB
wc_rank_math_analytics_objects: Datos: 0.11MB + Índice: 0.05MB + Motor InnoDB
wc_rank_math_internal_links: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
wc_rank_math_internal_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_smush_dir_images: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wc_snippets: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_stock_log: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wc_termmeta: Datos: 0.08MB + Índice: 0.08MB + Motor InnoDB
wc_terms: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wc_term_relationships: Datos: 0.13MB + Índice: 0.09MB + Motor InnoDB
wc_term_taxonomy: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
wc_usermeta: Datos: 1.52MB + Índice: 2.03MB + Motor InnoDB
wc_users: Datos: 0.08MB + Índice: 0.05MB + Motor InnoDB
wc_wcfm_marketplace_orders: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wc_wcfm_marketplace_orders_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wcfm_marketplace_product_multivendor: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wc_wcfm_marketplace_refund_request: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wcfm_marketplace_refund_request_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wcfm_marketplace_reverse_withdrawal: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wcfm_marketplace_reverse_withdrawal_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wcfm_marketplace_reviews: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wcfm_marketplace_reviews_response: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wcfm_marketplace_reviews_response_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wcfm_marketplace_review_rating_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wcfm_marketplace_shipping_zone_locations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wcfm_marketplace_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wcfm_marketplace_store_taxonomies: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wcfm_marketplace_vendor_ledger: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wcfm_marketplace_withdraw_request: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wcfm_marketplace_withdraw_request_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wcpdf_invoice_number: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wcv_feedback: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wc_admin_notes: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
wc_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wc_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wc_customer_lookup: Datos: 0.09MB + Índice: 0.06MB + Motor InnoDB
wc_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wc_wc_order_coupon_lookup: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
wc_wc_order_product_lookup: Datos: 0.25MB + Índice: 0.27MB + Motor InnoDB
wc_wc_order_stats: Datos: 0.11MB + Índice: 0.11MB + Motor InnoDB
wc_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wc_wc_product_meta_lookup: Datos: 0.05MB + Índice: 0.07MB + Motor MyISAM
wc_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wc_tax_rate_classes: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wc_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wc_wdp_orders: Datos: 0.11MB + Índice: 0.05MB + Motor InnoDB
wc_wdp_order_items: Datos: 0.09MB + Índice: 0.06MB + Motor InnoDB
wc_wdp_rules: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wc_wpforms_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wpmailsmtp_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wc_wpr_rucss_resources: Datos: 5.42MB + Índice: 0.09MB + Motor InnoDB
wc_wpr_rucss_used_css: Datos: 2.52MB + Índice: 0.05MB + Motor InnoDB
wc_yith_wcwl: Datos: 2.52MB + Índice: 1.52MB + Motor InnoDB
wc_yith_wcwl_lists: Datos: 3.52MB + Índice: 4.89MB + Motor InnoDB
wc_yoast_indexable: Datos: 2.52MB + Índice: 1.34MB + Motor InnoDB
wc_yoast_indexable_hierarchy: Datos: 0.16MB + Índice: 0.23MB + Motor InnoDB
wc_yoast_migrations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wc_yoast_primary_term: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wc_yoast_seo_links: Datos: 33.56MB + Índice: 31.13MB + Motor InnoDB
wc_yoast_seo_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_actionscheduler_actions: Datos: 2.52MB + Índice: 0.97MB + Motor InnoDB
wpstg0_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpstg0_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpstg0_actionscheduler_logs: Datos: 1.52MB + Índice: 0.64MB + Motor InnoDB
wpstg0_activecampaign_for_woocommerce_abandoned_cart: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
wpstg0_cli_scripts: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_cmplz_cookiebanners: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_cmplz_cookies: Datos: 0.08MB + Índice: 0.00MB + Motor InnoDB
wpstg0_cmplz_services: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_commentmeta: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wpstg0_comments: Datos: 0.38MB + Índice: 0.42MB + Motor InnoDB
wpstg0_e_submissions: Datos: 0.02MB + Índice: 0.27MB + Motor InnoDB
wpstg0_e_submissions_actions_log: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
wpstg0_e_submissions_values: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpstg0_jet_post_types: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_jet_taxonomies: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpstg0_litespeed_img_optm: Datos: 0.44MB + Índice: 0.18MB + Motor MyISAM
wpstg0_litespeed_img_optming: Datos: 0.34MB + Índice: 0.22MB + Motor InnoDB
wpstg0_mailchimp_carts: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_mailchimp_jobs: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_ms_snippets: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_options: Datos: 9.47MB + Índice: 1.45MB + Motor InnoDB
wpstg0_postmeta: Datos: 18.52MB + Índice: 12.03MB + Motor InnoDB
wpstg0_posts: Datos: 4.50MB + Índice: 1.13MB + Motor InnoDB
wpstg0_ppress_forms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpstg0_ppress_formsmeta: Datos: 0.06MB + Índice: 0.05MB + Motor InnoDB
wpstg0_ppress_meta_data: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpstg0_pprh_table: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_pv_commission: Datos: 0.14MB + Índice: 0.00MB + Motor InnoDB
wpstg0_rank_math_analytics_gsc: Datos: 1.52MB + Índice: 2.25MB + Motor InnoDB
wpstg0_rank_math_analytics_objects: Datos: 0.14MB + Índice: 0.08MB + Motor InnoDB
wpstg0_rank_math_internal_links: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
wpstg0_rank_math_internal_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_smush_dir_images: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpstg0_snippets: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_stock_log: Datos: 0.00MB + Índice: 0.00MB + Motor MyISAM
wpstg0_termmeta: Datos: 0.09MB + Índice: 0.13MB + Motor InnoDB
wpstg0_terms: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
wpstg0_term_relationships: Datos: 0.13MB + Índice: 0.09MB + Motor InnoDB
wpstg0_term_taxonomy: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
wpstg0_usermeta: Datos: 1.52MB + Índice: 2.03MB + Motor InnoDB
wpstg0_users: Datos: 0.08MB + Índice: 0.05MB + Motor InnoDB
wpstg0_wcfm_marketplace_orders: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpstg0_wcfm_marketplace_orders_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wcfm_marketplace_product_multivendor: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpstg0_wcfm_marketplace_refund_request: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wcfm_marketplace_refund_request_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wcfm_marketplace_reverse_withdrawal: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wcfm_marketplace_reverse_withdrawal_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wcfm_marketplace_reviews: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wcfm_marketplace_reviews_response: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wcfm_marketplace_reviews_response_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wcfm_marketplace_review_rating_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wcfm_marketplace_shipping_zone_locations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wcfm_marketplace_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wcfm_marketplace_store_taxonomies: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wcfm_marketplace_vendor_ledger: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wcfm_marketplace_withdraw_request: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wcfm_marketplace_withdraw_request_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wcpdf_invoice_number: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wcv_feedback: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wc_admin_notes: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpstg0_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wc_customer_lookup: Datos: 0.09MB + Índice: 0.06MB + Motor InnoDB
wpstg0_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpstg0_wc_order_coupon_lookup: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
wpstg0_wc_order_product_lookup: Datos: 0.25MB + Índice: 0.27MB + Motor InnoDB
wpstg0_wc_order_stats: Datos: 0.11MB + Índice: 0.11MB + Motor InnoDB
wpstg0_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpstg0_wc_product_meta_lookup: Datos: 0.05MB + Índice: 0.07MB + Motor MyISAM
wpstg0_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wc_tax_rate_classes: Datos: 0.00MB + Índice: 0.01MB + Motor MyISAM
wpstg0_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpstg0_wdp_orders: Datos: 0.11MB + Índice: 0.05MB + Motor InnoDB
wpstg0_wdp_order_items: Datos: 0.09MB + Índice: 0.06MB + Motor InnoDB
wpstg0_wdp_rules: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpstg0_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpstg0_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpstg0_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wpstg0_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpstg0_woocommerce_order_itemmeta: Datos: 9.52MB + Índice: 4.03MB + Motor InnoDB
wpstg0_woocommerce_order_items: Datos: 0.50MB + Índice: 0.17MB + Motor InnoDB
wpstg0_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wpstg0_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpstg0_woocommerce_sessions: Datos: 2.52MB + Índice: 0.05MB + Motor InnoDB
wpstg0_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wpstg0_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wpstg0_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wpstg0_wpforms_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wpmailsmtp_tasks_meta: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
wpstg0_wpr_rucss_resources: Datos: 5.50MB + Índice: 0.09MB + Motor InnoDB
wpstg0_wpr_rucss_used_css: Datos: 2.50MB + Índice: 0.05MB + Motor InnoDB
wpstg0_yith_wcwl: Datos: 2.52MB + Índice: 1.52MB + Motor InnoDB
wpstg0_yith_wcwl_lists: Datos: 3.52MB + Índice: 4.89MB + Motor InnoDB
wpstg0_yoast_indexable: Datos: 2.52MB + Índice: 1.34MB + Motor InnoDB
wpstg0_yoast_indexable_hierarchy: Datos: 0.16MB + Índice: 0.23MB + Motor InnoDB
wpstg0_yoast_migrations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wpstg0_yoast_primary_term: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wpstg0_yoast_seo_links: Datos: 33.56MB + Índice: 31.13MB + Motor InnoDB
wpstg0_yoast_seo_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

attachment: 773
awdp_pt_products: 1
awdp_pt_rules: 6
elementor_icons: 1
elementor_library: 41
jet-engine: 1
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 51
oceanwp_library: 1
oembed_cache: 54
page: 37
post: 35
product: 353
product_variation: 312
revision: 8
shop_coupon: 261
shop_order: 767
shop_order_refund: 8
shop_order_vendor: 1616
wafs: 8
wpforms: 1
yith_wcan_preset: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (50) ###

Advanced Dynamic Pricing for WooCommerce: por AlgolPlus – 3.2.4
FiboSearch - AJAX Search for WooCommerce: por Equipo de FiboSearch – 1.11.0
Akismet Anti-Spam: por Automattic – 4.1.9
AppMySite: por AppMySite – 2.11.0
Bulk Edit Products, Prices & Attributes for Woocommerce: por Elex – 1.0.4
bunny.net: por bunny.net – 1.0.8
Code Snippets: por Code Snippets Pro – 2.14.1
Complianz | GDPR/CCPA Cookie Consent: por Plugins Really Simple – 5.1.0
Elementor Pro: por Elementor.com – 3.2.2
Elementor: por Elementor.com – 3.2.4
Facebook for WooCommerce: por Facebook – 2.5.1
Site Kit by Google: por Google – 1.33.0
OMGF: por Daan from FFW.Press – 4.4.2
Importar y exportar usuarios y clientes: por codection – 1.17.5.6
JetEngine: por Crocoblock – 2.8.0
Ocean Elementor Widgets: por OceanWP – 1.3.0
Ocean Extra: por OceanWP – 1.7.5
Ocean Full Screen: por OceanWP – 1.0.7
Ocean Popup Login: por OceanWP – 1.2.0
Ocean Posts Slider: por OceanWP – 1.1.1
Ocean Side Panel: por OceanWP – 1.1.0
Ocean Social Sharing: por OceanWP – 1.1.1
Ocean White Label: por OceanWP – 1.0.6
Ocean Woo Popup: por OceanWP – 1.0.8
Pre* Party Resource Hints: por Sam Perrow – 1.7.6.3
Really Simple SSL: por Really Simple Plugins – 4.0.15
Redsys WooCommerce: por Redsys – 3.1.0
Rank Math SEO: por Rank Math – 1.0.64
WC Vendors Marketplace: por WC Vendors – 2.2.4
WebP Converter for Media: por Mateusz Gbiorczyk – 3.0.4
Checkout Field Editor for WooCommerce: por ThemeHigh – 1.4.8
Advanced Order Export For WooCommerce: por AlgolPlus – 3.1.8
Variation Swatches for WooCommerce: por Emran Ahmed – 1.1.17
WooCommerce Customizer: por SkyVerge – 2.7.4
WooCommerce Google Analytics Integration: por WooCommerce – 1.5.1
WooCommerce Mix and Match Products: por Kathy Darling – 1.11.1
Pay for Payment for WooCommerce: por Karolína Vyskočilová – 2.0.19
WooCommerce PDF Invoices & Packing Slips: por Ewout Fernhout – 2.9.0
WooCommerce Smart Coupons: por StoreApps – 4.19.0 (la actualización a la versión 4.22.0 está disponible)
WooCommerce Subscriptions: por WooCommerce – 3.0.15 (la actualización a la versión 3.1.2 está disponible)
WooCommerce: por Automattic – 5.3.0
WordPress Importer: por wordpressdotorg – 0.7
Asset CleanUp: Page Speed Booster: por Gabe Livan – 1.3.7.9
WP Crontrol: por John Blackbourn & crontributors – 1.10.0
WP Mail SMTP: por WPForms – 2.8.0
WP Rocket: por WP Media – 3.9-alpha4
Smush: por WPMU DEV – 3.8.5
WP STAGING: por WP-STAGING – 2.8.4
Connectif for WordPress: por Connectif – 1.3.0
WPS Hide Login: por WPServeur
NicolasKulka
wpformation – 1.8.5

### Inactive Plugins (5) ###

Custom Product Tabs for WooCommerce: por YIKES
Inc. – 1.7.7

Judge.me Product Reviews for WooCommerce: por Judge.me – 1.3.11
ProfilePress: por ProfilePress Team – 3.1.4
Tidio Chat: por Tidio Ltd. – 4.3.0
YITH WooCommerce Wishlist: por YITH – 3.0.22

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

WP STAGING Optimizer: por René Hermenau – 1.4.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Base de la tienda: #4 - /tienda/
Carrito: #5 - /carrito/
Finalizar compra: #6 - /finalizar-comprar/
Mi cuenta: #7 - /mi-cuenta/
Términos y condiciones: #1635 - /terminos-y-condiciones/

### Theme ###

Name: OceanWP
Version: 2.0.8
Author URL: https://oceanwp.org/about-me/
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
oceanwp/woocommerce/content-single-product.php
oceanwp/woocommerce/emails/customer-invoice.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/title.php

### Suscripciones ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Activo
Subscriptions Live URL: https://mercadify.es
Subscription Statuses: –
WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No
Report Cache Enabled: ✔ Si
Cache Update Failures: ✔ 0 fallo

### Configuración de la tienda ###

Country / State: España — Cáceres

### Compatibilidad de pasarelas de pago ###

Pago con Tarjeta (REDSYS): products
PayPal estándar: subscriptions
gateway_scheduled_payments
subscription_payment_method_change_customer
subscription_cancellation
subscription_suspension
subscription_reactivation
products
refunds

PayPal Reference Transactions Enabled: ❌ No

### Mix and Match Products ###

Version: 1.11.1
Database Version: 1.11.1
Template Overrides: –

### Action Scheduler ###

Complete: 2.406
Oldest: 2021-05-05 11:13:16 +0200
Newest: 2021-06-04 19:30:14 +0200

Failed: 63
Oldest: 2020-10-02 11:36:07 +0200
Newest: 2021-03-27 09:52:38 +0100

Pending: 3
Oldest: 2021-06-05 14:15:13 +0200
Newest: 2021-06-11 19:15:08 +0200

### Status report information ###

Generated at: 2021-06-04 22:08:11 +02:00
`

**Comment by Mrlunsuper** [comment]
Hi @loicpavard, Thank you very much for reporting the bug to us
I don't get this error on my site. Can you enable debug mode? Or can you show us your error log?

**Comment by loicpavard** [comment]
Hi @Mrlunsuper,

Please find attached my error_log from wordpress as well a printscreen of the error displayed on screen when DEBUG mode enabled and trying to request: 
https://mercadify.es/wp-json/wp/v2/pages?per_page=20

[error_log.txt](https://github.com/wcvendors/wcvendors/files/6653852/error_log.txt)

![Screenshot 2021-06-15 at 09 58 22](https://user-images.githubusercontent.com/85369778/122015506-737e3d00-cdc0-11eb-8c14-bd2819fe82c1.png)

**Comment by Mrlunsuper** [comment]
HI @loicpavard,
Sorry about the error you are getting. It looks like our plugin is conflicting with Elementor. We will fix the bug soon in the upcoming update. 
If you still want to keep calling the API you can add the exclude = yourhomepageid parameter. In this case, it would look like this [https://mercadify.es/wp-json/wp/v2/pages?per_page=16&exclude=344](https://mercadify.es/wp-json/wp/v2/pages?per_page=16&exclude=344)

**Comment by loicpavard** [comment]
Well done.
How did you identify that the issue is linked to the Homepage id ?

Thanks

**Comment by Mrlunsuper** [comment]
@loicpavard,
Look at the pictures
![image](https://user-images.githubusercontent.com/29702044/122021266-b7d50180-cdef-11eb-8100-3bb49174db54.png)
![image](https://user-images.githubusercontent.com/29702044/122021410-d89d5700-cdef-11eb-8b85-fcaa56a843ba.png)
You can see this error starting from the top VENTAS section, Then we view the source of your homepage by pressuring Ctrl + U in the chrome browser and seeing page-id. So you identify that the issue is linked to the Homepage
Cheers!

**Comment by loicpavard** [comment]
Got it, Great.
Can we agree in leaving this thread open until you publish next release of WC Vendor plugin includings this fix ?

Thanks
