### ISSUE TITLE
Additional information in the WCV commissions table - Stripe Fee column

### ISSUE THREAD

**Issue by MarkKevin08** [wcvendors/wcvendors#771]
**Is your feature request related to a problem? Please describe.**
As from the client's request, they would like to have a filter for the WCV commissions table so they could do this from their own. They are aiming to have additional column within the WCV Commissions table, where the Stripe fee would be stated for the order/commission.

**Describe the solution you'd like**
A general solution would be to add a filter for the table, that clients could use for customization.

**Describe alternatives you've considered**

**Additional context**
Here's the context from the client:
I am currently trying to edit the WCV Commission table on the backend to

change some of the values displayed in the Commissions column of the WCV
Commissions table to include the stripe fee deduction, and other values
need to not have it included yet. This will be dependent on the vendors
connection status to Stripe. I have found the piece of code in your plugin
where I could make this happen, but I am kindly requesting that you add a
filter to this function so that I can access the code from my theme.

>>If you could add a return filter to the bottom of the column_default()
>>function around line 108, that would be tremendously helpful. If I am able
>>to add custom logic and custom values to the column_default() function on
>>the class-wcv-commission-page.php, it would be greatly appreciated and
>>solve the issue I have at hand.

**Comment by Mrlunsuper** [comment]
Here is a code snippet to add custom columns to the commission table.
Put this code snippet to your theme functions.php
```
/**
 * Add custom columns value
 *
 * @param  mixed  $value current value in loop
 * @param  Object $item current item in loop
 * @param  mixed  $column_name name of column in query result
 * @return mixed .
 */
function add_custom_commission_column( $value, $item, $column_name ) {
	switch ( $column_name ) {
		case 'id':
			return $item->id;
		break;
	}
}
/**
 * Add custom columns label
 *
 * @param  Array $columns array stored column names 
 * @return Array $columns
 */
function custom_commissions_columns( $columns ) {
	$columns['id'] = __( 'ID', 'wc-vendors' );
	return $columns;
}
add_filter( 'wcvendors_commissions_columns', 'custom_commissions_columns', 10, 1 );
add_filter( 'wcvendors_commissions_column_default_id', 'add_custom_commission_column', 10, 3 );
```

**Comment by digitalchild** [comment]
Closing in favor of our docs.
