### ISSUE TITLE
Add shortcode parameters for vendor directory

### ISSUE THREAD

**Issue by bentasm1** [wcvendors/wcvendors#78]
To change the output order.....

-random
-alphabetical
-by date of newness
-by number of products (?)
-and whatever else......

Might be a Pro feature, rather than WCVFree

**Comment by digitalchild** [comment]
Sort by supported by the following order by: 

 http://codex.wordpress.org/Class_Reference/WP_User_Query#Order_.26_Orderby_Parameters
