### ISSUE TITLE
Duplicate seller info in single product page.

### ISSUE THREAD

**Issue by Mrlunsuper** [wcvendors/wcvendors#780]
**Describe the bug**
Duplicate seller info in a Single Product page.
**To Reproduce**
1. Go to the Single Product page
2. Click on Store Info tab
3. See duplicate seller info

**Screenshots**
![image](https://user-images.githubusercontent.com/29702044/126149267-40f34bc7-cb63-446d-a333-9d78fb77096c.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WC Vendors and WooCommerce are active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by digitalchild** [comment]
Fixed in v2.3.1
