### ISSUE TITLE
Refreshing page will toggle unmark shipped/mark shipped

### ISSUE THREAD

**Issue by ispal** [wcvendors/wcvendors#79]
When vendor goes to vendor dashboard and marks order as shipped it goes to following page

http://domain.com/vendor_dashboard/?wc_pv_mark_shipped=20

The problem is that if you refresh the page it will toggle the shipment status and as result of that will send multiple emails to customers.

**Comment by bentasm1** [comment]
I can see that being a bit of a pain.  We will probably change it so the URL will refresh to the vendor dashboard, rather than to the URL of the item marked as being shipped.

**Comment by bentasm1** [comment]
If the vendor marks an order as shipped, WC Vendors updates the database, and send the vendor an email.  If you reload the URL, it will mark it as unshipped.  If you reload the URL again, it will mark as shipped and trigger the email.  Then the cycle repeats itself every page refresh.

We should find a way to use JavaScript to rewrite the URL in the browser window after the wc_pv_mark_shipped query string is posted.  Or, change around the buttons and how the function works to not keep the circle going with one button for mark shipped, one button for mark unshipped, and if the query string for either is reloaded, and already marked shipped or unshipped, do nothing other than die.

Till then, I've patched in a temporary warning notice for this issue to be seen on the Vendor Dashboard after a vendor marks/unmarks an order shipped.

**Comment by digitalchild** [comment]
Why would we allow people to mark something unshipped?
