### ISSUE TITLE
Vendor Membership being logged in the Commissions table

### ISSUE THREAD

**Issue by MarkKevin08** [wcvendors/wcvendors#817]
**Describe the bug**
As tested,  the vendor's membership purchase was logged in the commissions table. 

**To Reproduce**
1. Create a vendor's membership
2. Purchase the vendor's membership as a vendor
3. Check the commissions' table, and see the vendor's membership purchase got logged

**Screenshots**
![image](https://user-images.githubusercontent.com/49851476/149611054-37466837-0f73-488f-b157-acc6fc49b76f.png)

**Expected behavior**
Administrator-only orders should not be logged in the commissions' table.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WC Vendors and WooCommerce are active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by digitalchild** [comment]
We have reverted the admin marketplace logging so this will not log the memberships any more.
