### ISSUE TITLE
Add Billing Info to Paypal Transaction

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#82]
Currently the buyers billing information is not appended to the order during the transaction. This is supported by the paypal API. It will need to be added. This would give our paypal gateway the same functionality of the built in gateway.

**Comment by digitalchild** [comment]
It appears this cannot be done as per the official response from Paypal. 

" Adaptive Payments does not have any feature in the documents which does this. I apologize for the inconvenience this might cause." 

See: http://stackoverflow.com/a/11979175/977610

**Comment by fervous** [comment]
https://www.wcvendors.com/help/topic/paypal-shipping/#post-41343  Checking for updates to this issue, if any changes with paypal has occurred.

**Comment by digitalchild** [comment]
Can't fix, it's a limitation in PayPal, not us.
