### ISSUE TITLE
Marketplace commissions logged are incorrect

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#824]
**Describe the bug**
The new 2.4 marketplace commissions that are being logged are a duplicate of the vendor's side of the calculation and not reflective of the earnings of the marketplace. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Set commission to not be 50% 
2. Run an order
3. Check commissions table, see that both vendor and marketplace commission values are not correct. 

**Expected behaviour**
Commission amounts should reflect the split correctly.

**Comment by Mrlunsuper** [comment]
It's related to the Pro issue, So this issue should be closed.
