### ISSUE TITLE
Order status not getting updated while initiating a part refund.

### ISSUE THREAD

**Issue by bdesai1982** [wcvendors/wcvendors#827]
**Describe the bug**
Customer places an order including products from different vendors. Then after when the admin initiates a refund for a single product from the order, the status is not updated for the admin. 

**Steps to reproduce:**
1. Place an order for multiple products in a single order. (Customer)
2. Admin initiates a refund for a single product.
3. Check the status in the commission's table.

Note: The status is updated for both the admin and the vendor when a full refund is initiated.

**Screenshots**
![Screenshot_15](https://user-images.githubusercontent.com/77658351/153599732-61639994-029c-43d1-a8aa-1f83edd43ba3.png)
![Screenshot_16](https://user-images.githubusercontent.com/77658351/153599738-b4d2a7b0-f819-4f01-aa98-2ea56c783b51.png)

**Expected behavior**
The status must be changed from 'Due' to 'Reversed' for both the admin and the vendor.

**Comment by digitalchild** [comment]
Is this an issue in marketplace or Stripe?
