### ISSUE TITLE
The admin shipping fee is negative

### ISSUE THREAD

**Issue by Mrlunsuper** [wcvendors/wcvendors#828]
**Describe the bug**
The admin shipping fee is negative when the order has 2 items or more
**To Reproduce**
1. Run an order with 2 or more items
2. Go to WC Vendors -> Commissions and see the admin shipping fee was negative

**Screenshots**
![image](https://user-images.githubusercontent.com/29702044/153791371-3efb14cc-1e2e-4713-9277-dde97a0ed1b5.png)

**Expected behavior**
The admin shipping fee should not be negative

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WC Vendors and WooCommerce are active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by digitalchild** [comment]
Is this two items from the same vendor, what are the shipping settings ?

**Comment by Mrlunsuper** [comment]
> Is this two items from the same vendor, what are the shipping settings ?

Yes, there are two items from the same vendor, shipping system is flat rate and give shipping option enabled

**Comment by Mrlunsuper** [comment]
Close by revert log admin commission feature
