### ISSUE TITLE
Failed refund request.

### ISSUE THREAD

**Issue by bdesai1982** [wcvendors/wcvendors#831]
**Describe the bug**
Customer places an order for variable product and vendor requests for a refund to the admin, then
admin approves the refund request but the refund request gets failed.

**To Reproduce**
1. Place an order for variable products (Customer).
2. Vendor requests for a refund.
3. Admin approves the refund request. 
4. Check the refund request status "FAILED".

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/77658351/155470252-5d4db0e2-7e8c-47c5-9503-cfd4c7fc8a38.png)

**Expected behavior**
Refund request status must be "success".

**Comment by digitalchild** [comment]
Fixed in PR above
