### ISSUE TITLE
Duplicate H1 tag on products (accesibility, SEO)

### ISSUE THREAD

**Issue by damian-aragunde-udc** [wcvendors/wcvendors#839]
**Is your feature request related to a problem? Please describe.**
On each product page, there's 2 H1 tags : One "empty" (inserted by WC-V), another with the product title (inserted by WC).

**Describe the solution you'd like**
Should be only 1 H1 per page.

**Describe alternatives you've considered**
WC Vendors should use a label instead.

**Additional context**
Our team is improving our website SEO in general terms, based on the expertise of a SEO specialist company.
One problem was about headers.

A correct heading makes easier to "search crawlers" have an idea of the structure of the webpage.
This is also a huge consideration in terms of accessibility: screen readers can help navigate across the content based on HTML headers. And Google also likes the accessibility features.

The WC Vendors plugin adds an H1 tag by himself in [**/templates/front/vendor-main-header.php**](https://github.com/wcvendors/wcvendors/blob/master/templates/front/vendor-main-header.php).
WooCommerce also adds an H1 tag in  [**/plugins/woocommerce/templates/single-product/title.php**](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/single-product/title.php)

One of them should be changed, because there should be only 1 tag H1.

About accessibility:
https://www.w3.org/WAI/WCAG21/Techniques/html/H42

About SEO:
https://ahrefs.com/blog/h1-tag/

**Comment by digitalchild** [comment]
Hi @damian-aragunde-udc thanks for bringing this to our attention. We'll have this fixed for our next release.

**Comment by damian-aragunde-udc** [comment]
Thanks for the quick response and the excelent work :)
