### ISSUE TITLE
WC Vendors Ovewritten "Author" label

### ISSUE THREAD

**Issue by MarkKevin08** [wcvendors/wcvendors#887]
**Describe the bug**
WC Vendors overwritten the "author" field's label.
![image](https://user-images.githubusercontent.com/49851476/225199208-8273cf06-738e-495c-9f81-df1694e3d5b4.png)

**To Reproduce**
1. Go to Posts
2. Click on Quick Edit
3. Scroll down to check the "author" field.
4. See error - "vendor" is labeled instead of "author"

**Screenshots**
![image](https://user-images.githubusercontent.com/49851476/225199425-484261e1-2e05-4e78-b036-b1d538860ff9.png)

**Expected behavior**
"vendor" is labeled instead of "author"

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WC Vendors and WooCommerce are active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by digitalchild** [comment]
This is an issue in Pro not marketplace.
