### ISSUE TITLE
Spanish Translation Missing

### ISSUE THREAD

**Issue by mauricioulloa** [wcvendors/wcvendors#89]

**Comment by bentasm1** [comment]
It's not missing.  We don't speak Spanish.  If you can translate it, send us the translated file and we'll very happily include it in the plugin! :)

**Comment by mauricioulloa** [comment]
I'll do it !

**Comment by bentasm1** [comment]
Thanks, you can email it to ben@wcvendors.com or post it here on GitHub,
whichever way works best for you. :)
