### ISSUE TITLE
Override Vendor Role Name

### ISSUE THREAD

**Issue by digitalchild** [wcvendors/wcvendors#96]
Replace all hard coded references to the 'vendor' role so that it can be overridden with a single action. 

There are 30 references in 12 files that need to be updated to reflect this change.

**Comment by digitalchild** [comment]
This was added in this commit 4aa1ae732204785139347255f4bc29fc112bd2a4

**Comment by maxwelljvogel** [comment]
> This was added in this commit [4aa1ae7](https://github.com/wcvendors/wcvendors/commit/4aa1ae732204785139347255f4bc29fc112bd2a4)

@digitalchild Have you included this use in your documentation?  I would like to use a role besides "Vendor".  Thank you in advance.

**Comment by digitalchild** [comment]
You can change the label of what the vendor says which is in our settings, but the underlying internal role still needs to be 'vendor'
